### ISSUE TITLE
Torch-Lantern Duplication (0.20)

### ISSUE THREAD

**Issue by lifeofsenpai** [An-Sar/PrimalCore#10]
When you add a torch to a lantern it does not remove a torch from your inventory. However when you remove the torch from a lantern, it gives you a torch. A small bug that I wanted to point out. Thanks again, and continue doing your magic!

**Comment by An-Sar** [comment]
thank you for the bug report, this will be fixed in 0.2.3. Unfortunately I didn't notice this issue until now.

**Comment by An-Sar** [comment]
This has been released.
