### ISSUE TITLE
Lit torches don't provide dynamic light

### ISSUE THREAD

**Issue by SwordShaman** [An-Sar/PrimalCore#100]
I've noticed that primalcore's lit torches don't work with optifine's dynamic lights option.  They work fine when placed and provide light, but when in hand they do not.

**Comment by Krhymez** [comment]
Same with Dynamic Lighting. Although players can edit to config to possible add the torches.. it would be cool to just be able to install and use. 

@SwordShaman I would not recommend Optifine while playing with other mods. If you are looking for a performance boost, try "FoamFix"   If you are on an older version of minecraft then "FastCraft".  I find optifine causes more harm than good.

**Comment by An-Sar** [comment]
Not sure what would be involved in supporting this out of the box, i am opening to doing so if/when i have time =D

**Comment by RiverC** [comment]
It looks like Optifine will at some point add a feature where dynamic lights can be added via some sort of resource pack. to allow for compatibility and adding custom dynamic lights, but it's not yet implemented.

https://github.com/sp614x/optifine/issues/182 

My only objection is I spent like 2 hours searching for this answer, didn't know where to look, optifine doesn't have much documentation on the dynamic lights feature, I wish it would say explicitly "for now only vanilla light sources are dynamic." To make matters more confusing the other dynamic light (the laggy one) DOES allow you to add/remove sources at will, iirc, and there's nothing indicating you can't in optifine (unless you know where to search!)
