### ISSUE TITLE
Making Split Wood

### ISSUE THREAD

**Issue by Kleeppoo** [An-Sar/PrimalCore#101]
How does one make Split wood? It is needed to make brick Form/mold.

**Comment by An-Sar** [comment]
should work with most axes by right clicking on a stripped log, which you strip by sneak clicking with a work blade or in a crafting grid.

**Comment by Kleeppoo** [comment]
thanks

**Comment by Krhymez** [comment]
@Kleeppoo https://www.youtube.com/watch?v=X6wGD4wKdu8  A great guide to the "basics" of PrimalCore  i highly recommend watching it.
