### ISSUE TITLE
hi An-Sar and PrimalCore Community

### ISSUE THREAD

**Issue by trilexcom** [An-Sar/PrimalCore#103]
hi An-Sar and PrimalCore Community

this is just a feature request! 

thanks for making PrimalCore happen i really appreciate everything you have done. We are using PrimalCore in the Trilex Pack i wanted to know if their is a config option you can add please to enable lava bucket hurting the player when they pick it up? just like GregTech does? 

Thanks again for everything 

Mat (TrilexCom)

**Comment by An-Sar** [comment]
Hello, thank you for your comment!

Short answer is yes. 

This is more or less planned, in a previous mod I had buckets of different materials, some of them allowed for safely moving lava while others would set the player on fire, or potentially drop the lava, etc.

I am planning on bringing the buckets types back, along with corresponding configs.

**Comment by trilexcom** [comment]
thank you! your awesome!

**Comment by An-Sar** [comment]
Update: 0.6.10 has added a number of fluids, fluid based crafting, and related features. The custom bucket types will be sure to follow.
