### ISSUE TITLE
Hornblende Idolum teleports in creative

### ISSUE THREAD

**Issue by davqvist** [An-Sar/PrimalCore#106]
Forge 2537
PC 0.6.0.11

Hornblende Idolum teleports away when breaking even in Creative which means you can't really get rid of it.

**Comment by An-Sar** [comment]
In creative if you break it with an empty hand it should break normally

**Comment by davqvist** [comment]
Interesting, that seems to work indeed. I would still recommend to disable that function in creative. Would have never thought of trying it with empty hand.

**Comment by An-Sar** [comment]
yeah that makes sense, as of 0.6.10 this will now  be disabled when player is creative
