### ISSUE TITLE
[1.12.2] Crash with Mud Brick Hibachi

### ISSUE THREAD

**Issue by GWSheridan** [An-Sar/PrimalCore#107]
MC Version 1.12.2
Forge Version 14.23.0.2540
PrimalCore Version 1.12.2-0.6.3

When placing the Mud Brick Hibachi minecraft will crash to the launcher

Crash report https://pastebin.com/JYgpGEef

**Comment by An-Sar** [comment]
the hibachi isn't properly implemented yet, it should be coming in one of the next few updates after some of the larger 0.6.x bugs are worked out.

**Comment by An-Sar** [comment]
Crash has been fixed, hibachi is still not actually implemented but will be coming very soon.
