### ISSUE TITLE
1.12.2 Crash on world load

### ISSUE THREAD

**Issue by xAlicatt** [An-Sar/PrimalCore#108]
Attempting to start a singleplayer world, and get this crash. This is happening with versions 0.6.2-0.6.5

https://gist.github.com/xAlicatt/dd080cff1afbbbcb66db62ada1c1394a

**Comment by xAlicatt** [comment]
Just an FYI, upon further testing, I seem to be able to load up the world after restarting the client, and it doesn't always happen. I just created a new world with the 0.6.5 version and it did not crash. I have also been able to create a new world in some of the other versions without the crash.

**Comment by xAlicatt** [comment]
Get this same crash on a loaded world when generating chunks sometimes.

**Comment by An-Sar** [comment]
This appears to be a conflict with EssentialCraft, i am planning on adding it to my dev environment for testing.

**Comment by Hypsellis** [comment]
It can happen on an already loaded world when loading more chunks while playing.

**Comment by xAlicatt** [comment]
Just for further info, I have rolled back Primal to the last release candidate (0.5.22) and the Forgecraft (0.3.25) that works with that, and this crash has not happened so far. Definitely seems to be something with the Beta code.

**Comment by Speiger** [comment]
@xAlicatt this was the pregenerator 1.4 bug its fixed in pregenerator 1.5 you can close it.
It was because i unloaded playerloaded chunks accedently.

**Comment by xAlicatt** [comment]
@Speiger Eh? Pregenerator?

**Comment by Speiger** [comment]
@xAlicatt yes you have the ChunkPregenerator in your pack. When a  task is executed and the game crashes it will auto restart the task when you rejoin the world. Causing the same crash again.

**Comment by xAlicatt** [comment]
@Speiger Oh yeah....but I have version 1.5? Unless it came out after I rolled back my PrimalCore on the 17th.

**Comment by Speiger** [comment]
@xAlicatt no you dont:
	| UCHIJAA | chunkpregenerator | 1.4 | Chunk Pregenerator V-1.12-1.4.1.jar | None |

**Comment by xAlicatt** [comment]
@Speiger Twitch app and curseforge both say "3 days ago" or the 17th. And that crash log at the top of the thread was posted 5 days ago. I will try updating though and report back if it's still happening. Thank you

**Comment by Speiger** [comment]
@xAlicatt i ran around 50 tests to ensure that the bug is gone in 1.5 xD

**Comment by Hypsellis** [comment]
What are you talking about ? We are already on the 0.6 version since the 11th, and the crash still occurs.

**Comment by Speiger** [comment]
@Hypsellis no it was my pregenerator that caused that issue. It unloaded chunks inside of the player which basically causes this problem.

**Comment by Speiger** [comment]
You can close this issue because its not yours!

**Comment by xAlicatt** [comment]
@Speiger I just loaded up a brand new world with the latest version of your mod and this one and, yes, the crash is still happening. 

https://gist.github.com/xAlicatt/70c685720f1cfaf137abddcf7958cb71

**Comment by Hypsellis** [comment]
No it's an incompability with EssentialCraft, and the crash has still not be solved, otherwise the thread would have been closed by the devs.

**Comment by Speiger** [comment]
ok i was thinking you had a pregeneration running in the meantime.

**Comment by An-Sar** [comment]
i haven't really tested yet as i was kind of watching this thread unfold, i am still planning on testing with essentialcraft.

**Comment by An-Sar** [comment]
this should be resolved with the next release
