### ISSUE TITLE
crash when loading chunks

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#109]
I get this crash often when loading chunks while I load a world or travel it. It seems there is an incompability with EssentialCraft. https://pastebin.com/YqiqCfaM

**Comment by An-Sar** [comment]
this is a duplicate with https://github.com/An-Sar/PrimalCore/issues/108

You are correct it does appear to be a conflict with EssentialCraft, i am planning on adding it to my dev environment.

**Comment by Hypsellis** [comment]
Oh sorry I wasn't sure it was the crash since the crash log looked different. Anyway I close this one.
