### ISSUE TITLE
[1.12.2] Work blade doesn't work on logs with metadata 12+

### ISSUE THREAD

**Issue by Kiyaku** [An-Sar/PrimalCore#113]
Heya,

i have a mod that generates custom trees and the logs use meta data 12 and up, for the all sided bark logs. Unfortunately the work blade doesn't seem to work on it (its shift+right click ability). 

Could that be added?

Thanks!
-SC

**Comment by An-Sar** [comment]
Yes i am interested in looking into supporting logs like this. What is your mod called?

**Comment by Kiyaku** [comment]
Not my mod but i use Recurrent Complex which adds a couple of custom made trees that use said log blocks. 
Adding the mod should spawn those trees by default, in case you want to use it for testing!

**Comment by An-Sar** [comment]
debarking logs at other angles than horizontal is on hold until 1.13
