### ISSUE TITLE
Aconite Growth crash

### ISSUE THREAD

**Issue by Nachtflame** [An-Sar/PrimalCore#114]
Having an issue on my server, where every so often (every few days or so) we suffer a rash of crashes, that all point to "nmd.primal.core.common.blocks.plants.invasive.Aconite.canUpdate(Aconite.java:95)
	at nmd.primal.core.common.blocks.plants.AbstractPlantGrowing.func_180650_b(AbstractPlantGrowing.java:312)" which I find odd, since I've had plant spread turned off in our world since the start.  Double checked my configs to be sure, but they still indicate that it's disabled.

Here are the crash logs from this evening, 4 in the space of just under a half hour.
[crash-2017-12-10_22.14.07-server.txt](https://github.com/An-Sar/PrimalCore/files/1546563/crash-2017-12-10_22.14.07-server.txt)
[crash-2017-12-10_22.21.44-server.txt](https://github.com/An-Sar/PrimalCore/files/1546564/crash-2017-12-10_22.21.44-server.txt)
[crash-2017-12-10_22.23.07-server.txt](https://github.com/An-Sar/PrimalCore/files/1546565/crash-2017-12-10_22.23.07-server.txt)
[crash-2017-12-10_22.40.12-server.txt](https://github.com/An-Sar/PrimalCore/files/1546566/crash-2017-12-10_22.40.12-server.txt)

The configs also have WorldGen for the end disabled, though there was generation there before that was disabled.  Not sure if that would cause the problem, just thought it should be noted.

PrimalCore-1.12.2-0.6.4
Forge 2544

**Comment by An-Sar** [comment]
I believe this was fixed in 0.6.5

**Comment by Nachtflame** [comment]
aha, okay then, will update.  Thank you for the rapid response. :)
