### ISSUE TITLE
Terra Clay Clump texture issue ? / i dont know how to craft terracotta block?

### ISSUE THREAD

**Issue by trilexcom** [An-Sar/PrimalCore#115]
hi An-Star / PrimalCore team

when i mined some Terra Clay clump i see a texture issue i have added few screenshots so you can check it out plus using JEI i can't find out how to craft Terracotta block from terra clay ? sense i get clump when i mine i can add a recipe using crafttweaker to fix that but is this intentional or is their a way of getting block like Silk touch?

Mat (Trilex Pack (Pre-alpha)

screenshot : https://imgur.com/a/tvZX3
Forge : 2556
PrimalCore 0.6.9
1.12.2

**Comment by An-Sar** [comment]
this is a bug, i am changing the recipes a bit for the next release. the clumps will cook or dry into the item bricks, which will craft into the blocks.

the textures were using the wrong json parent, making the size extra large.

both issues are now fixed for 0.6.10, which is hopefully releasing very soon

**Comment by trilexcom** [comment]
you are awesome thank you very much!

**Comment by An-Sar** [comment]
thank you for reporting bugs!
