### ISSUE TITLE
Fire pit and kiln

### ISSUE THREAD

**Issue by jonevance** [An-Sar/PrimalCore#118]
I cannot figure out how to build a fire pit, and I cannot figure out how to use the kiln.  I can get sticks to light in the base, but cannot get any dryable items into the top.

**Comment by kitsushadow** [comment]
The firepit will go out if you place a block over it. It just makes fire.

**Comment by jonevance** [comment]
Suppose I wasn't clear.  There's no recipe in JEI and I cannot figure out how to make the fire pit.  Are you saying it has no use even if I do figure it out?

Also, though I've made a kiln, I can find no way to use it to dry items.

**Comment by kitsushadow** [comment]
U use a hoe or shovel on gravel. That gives u a type of gravel. U then hoe
or shovel it again and you get a fire pit. Add tinder and sticks the light
it

**Comment by kitsushadow** [comment]
The kiln takes a few furnace recipes like clay or sand or cobblestone. Use
different grades of charcoal to increase the temperature. That will be
going away soon and just any old charcoal will do then

**Comment by RiverC** [comment]
I'm using the latest version in 1.12 and can't get this to work... shovels don't do anything to gravel on right-click, and right-click with a hoe does change the gravel, but then another use seems to do nothing more... does one need a specific level / material of shovel or hoe for it to work?

**Comment by kitsushadow** [comment]
its hoe then shovel then tinder then sticks then light with something
