### ISSUE TITLE
Question regarding getting other kinds of flakes (diamond, obsidian, etc)

### ISSUE THREAD

**Issue by RiverC** [An-Sar/PrimalCore#119]
I don't see any issues wrt to knapping other stone/gem materials, so I'm wondering if it has been implemented... I tried knapping a diamond the same way as flint and nothing happened (but this sort of makes sense, I guess.) 

I also saw a question in the project page regarding getting obsidian flakes -- is it a matter of the material you strike it against, or is there another method (not shown in JEI?) 

Any general hints as to how to get the higher tier gem materials?

Also: is it supposed to require a quartz Gallagher to get an iron plate? 

Thanks, and apologies if these have been previously addressed. 

I also noticed that about a year ago there were questions regarding saws, and as a person who works with wood, the way to get planks without a saw is to split a straight section of wood with a heavy work knife (like a big bowie knife) by first forcing the knife into place by either chopping or sawing with it, and then using something heavy like a hammer to split the wood more precisely than is possible with an axe. You could also do the same with an axe, but it's a bit more awkward due to the fact that axe-blades are usually too short and their weighting/balance doesn't favor using them that way. 

Thus an adjustment to the normal process of getting planks could be to take the flint hatchet and a stone to get two or three plank blocks from a log. 

I think however balance-wise that might be pushing the time table, that was a problem I often had in TerraFirmaCraft; unless you lengthen the minecraft day, you end up not having enough time to get yourself started.

Anyway, thanks for the work on this mod, it plays very well with other mods for the most part and adds good aesthetic qualities to the world.

**Comment by kiwifrogg** [comment]
It is a case of working out what is harder than diamonds; clue it can be found or made in the overworld by mixing water with lava  ;)  Also it can be done on a diam block or with the anvil and forge hammer from kitsu's

**Comment by RiverC** [comment]
That's not purely logical, but thanks for the hint.

**Comment by An-Sar** [comment]
i've considered adding plank recipes to the hatchet and work blades with output lower than any of the saws before, and i think i like the idea.

**Comment by RiverC** [comment]
Anything on the Gallagher? I've a mind to use crafttweaker to allow the iron gallagher to make plates since you can make plates using the iron engineer's hammer in Immersive Engineering and I'm trying to balance it.

**Comment by An-Sar** [comment]
Gallaghers should be able to make the primal version of plates, which are ore dictionaries , depending on the config. But probably a good idea to crafttweak if you want a uniform set of plate items.

**Comment by RiverC** [comment]
I think that's part of the UniDict issue then. I disabled the Gallagher plate recipes for now, as I was also seeing the "convert an ingot into a plate with no tool" recipes.

**Comment by An-Sar** [comment]
yeah i'm not sure what's happening with that, will need to get uni in my dev environment and try to see whats happening.
