### ISSUE TITLE
Stone Grill Dupe

### ISSUE THREAD

**Issue by Toktha** [An-Sar/PrimalCore#123]
If you cook something on the grill and have a full inv and you try to retrieve the "cooked" item and don't have that item in your inv it will just constantly spit out that cooked item on the ground and give you exp.

MC 1.12.2 
PrimalCore 1.12.2-0.6.9.7

**Comment by An-Sar** [comment]
Do you happen to be using SevTech? the Stone Grill is from PrimalTech not PrimalCore

**Comment by Toktha** [comment]
Yeah, haha i went to the site but i guess i hit PrimalCore by mistake.  My bad :D

**Comment by An-Sar** [comment]
no worries =D
