### ISSUE TITLE
Crash withdrawing water from PrimalCore barrel

### ISSUE THREAD

**Issue by LightningAvenger** [An-Sar/PrimalCore#124]
Dumping water into a PrimalCore barrel functions properly, however when you try to withdraw said water using a bucket or fluid bladder, you get a crash. The crash occurs even when PrimalCore is the only mod installed.

Minecraft version 1.12.2, Forge 14.23.1.2575, PrimalCore 0.6.9, Java 1.8.0_151

Crashlog: https://paste.ee/p/Ph2D0

Gif: https://i.imgur.com/16ly93a.mp4

**Comment by An-Sar** [comment]
0.6.11 is the most current version, and the barrel has been changed significantly, are you able to recreate the error with that version?

**Comment by LightningAvenger** [comment]
Seems to be working properly on 0.6.11, sorry for wasting your time with my derp

**Comment by An-Sar** [comment]
no worries at all, reporting bug is always a good thing
