### ISSUE TITLE
[1.12.2 / Suggestion] Compact with Tinkers Hatchet

### ISSUE THREAD

**Issue by Kiyaku** [An-Sar/PrimalCore#128]
Heya,

i was trying to use the tinkers hatchet on stripped logs to get split logs, but that doesn't seem to work. 

Perhaps using the Mattock as a work blade on wood (to debark them) could be nice as well? Seems like mattocks can usually be used for that kind of work (in real life). 

Cheers,
SC

**Comment by An-Sar** [comment]
this is an interesting idea, it would require some adjustment with how the current logic works, but it would be possible.

**Comment by Kiyaku** [comment]
Awesome to hear.
The tinkers shovel currently also can't create a firepit. Commenting just in case!

**Comment by Alan19** [comment]
How is the tinkers' compatibility going?

**Comment by TimGoll** [comment]
any new updates on this topic?

**Comment by An-Sar** [comment]
this should be working

**Comment by TimGoll** [comment]
Okay. I'll try it later and give a feedback

**Comment by TimGoll** [comment]
It does work!
