### ISSUE TITLE
crash with pickaxes

### ISSUE THREAD

**Issue by bdudek** [An-Sar/PrimalCore#129]
crashing with the custom pick axes since they came from forgecraft I'm assuming that's where the problem lies because it's after I updated to primal core 6.11 that its happening. posting at both primal and forgecraft

https://pastebin.com/wqDL55mt

**Comment by An-Sar** [comment]
@kitsushadow looks like i changed a method name being used by KFC

**Comment by kitsushadow** [comment]
should I use the new name or do you want to rename it back?

**Comment by An-Sar** [comment]
it would be interesting to see what the error says in KFC dev bc the main method name in question appears to be the same..

**Comment by An-Sar** [comment]
also might want to update from maven as 0.6.12 is about to drop and has some changes intended to Magnum compatibility
