### ISSUE TITLE
Ash Bin

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#13]
Ash is useful, and a little hard to collect. I'd like a bin you can put  under furnaces (or other things which burn fuel) which has a chance to collect ash from burning fuel.

**Comment by An-Sar** [comment]
I like this idea especially in context of your previous mention of a smoke "api" of sorts.

My immediate vision is filling the block with layers of ash, where each layer represents an ash block.

I am interested in further feedback

**Comment by kitsushadow** [comment]
Would be good to see if some functionality could be added to support other block types that burn fuel.

**Comment by An-Sar** [comment]
I am adding a basic version of this in the next release (0.2.6), overall mechanics should be expanded on as we go forward.
