### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by TitusArmillius** [An-Sar/PrimalCore#132]
In my log there are statements alike the cascading world-gen lag which was reported a month back. At 7:22:07 my game froze till I forcible closed it. 

statement-
"PrimalCore loaded a new chunk (26, 22  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker."

Log: https://gist.githubusercontent.com/TitusArmillius/ab9ccc3eae40f7647bdca4e8381d9d58/raw/919df713867ed10b15a3a201db801be738a4b85c/gistfile1.txt

**Comment by An-Sar** [comment]
https://github.com/An-Sar/PrimalCore/issues/110
