### ISSUE TITLE
Primal tools are disappearing? 

### ISSUE THREAD

**Issue by trilexcom** [An-Sar/PrimalCore#134]
hi An-Sar and PrimalCore team

when i use the Fire Bow on torch, Spruce log stack, adobe Brick kiln my Fire Bow disappears sometimes it comes back to me after i disconnect and sometimes it comes back to me if i remake it 

if you could please let me know if its my fault or if its bug it would be appreciated it

Mat (Trilex)

Primal Version : 0.6.13
Forge : 2583

Trilex Pack version 1.3

**Comment by trilexcom** [comment]
it might be server lag ? but i wanted to let you know about this at least 

Mat

**Comment by An-Sar** [comment]
is this still happening on your server?

**Comment by trilexcom** [comment]
it was when i using the fire bow i dont need to use that anymore, but i am not sure if others having the issue but no one has reported so i guess we can close the ticket sense i dont see anyone else reporting this matter mat

**Comment by trilexcom** [comment]
i am going to close this for now if i see it again i will let you thanks again mat

**Comment by An-Sar** [comment]
sounds good thank you
