### ISSUE TITLE
[Question] Crafttweaker support

### ISSUE THREAD

**Issue by Smartaros** [An-Sar/PrimalCore#135]
Is it planned? I think couldron has an interesting mechanics and its customization will expand the gameplay

**Comment by An-Sar** [comment]
This is planned yes, i will update this issue with further information

**Comment by Fireztonez** [comment]
Do you have any idea when the Crafttweaker support will be added for the cauldron and possibly for the Adobe Brick Kiln and other thing... I have lot of thing I want to do in my pack, and I have lot of ideas for use thats mechanics, but if you don't think you can make it reality soon, I think I will need to find other way to do the tings...

**Comment by An-Sar** [comment]
Cauldron and Drying Rack should be very soon, i have an almost working implementation, and someone else has working code they made for an add on, which they are planning to contribute back to Primal itself.

Kiln i would like to do some reworking on first, for example the ability to process full stacks.

**Comment by An-Sar** [comment]
in 0.6.45 CT support has been released for Drying Racks, Hibachi, and In-world Flaking recipes.
Cauldron support will be coming within a release or two.

**Comment by Fireztonez** [comment]
Can edit your wiki, to try explaining more the recipes examples for each things.

I would say, probably add information about the data type or object type want for each recipe.
By example; 
`mods.primal.DryingRack.addNonRottingRecipe(String name, Integer (time), IItemStack input, IItemStack input);`

And I don't know if the syntax in the wiki is ok for your mod, but possibly using the standar syntax should be a great idea...
Using ; <minecraft:diamound> and not just 'minecraft:diamound'
or  <ore:stone> not 'ore:stone'

About "addNonRottingRecipe", what does it mean? Does the recipe have any chance of not succeeding and rotting?? Or are there recipes that have no chance of rot??

Other thing, I see `mods.primal.Flake.removeRecipe("flint");`, I imagine you erase the recipe using the recipe name?
Possibly it should be great to give possibility to remove recipes using the input or output item, like any other mod do!

I really think that this section of the wiki needs more attention, question of added explanations, possibly use script tags for the codes, question to make more visual, to add explanations and to classify each recipes by type and not to put all the recipes deleted in a single block ...

But for sure, that is a realy realy great add to your mod!! You should, when the work level is more advanced, speak in the description of the mod on Curse, you have a CraftTweaker support, with the link to the section of your Wiki!!

Fireztonez

**Comment by An-Sar** [comment]
yeah i just copy pasted the sample scripts i was using as a place holder, will be updating that section for sure, you're input is useful in this regard.

**Comment by Fireztonez** [comment]
Perfect, I just see the revised section in your wiki, this is a lot better, no comparison possible!!!!
