### ISSUE TITLE
[Question] please regarding Iron Cauldron making Tannin

### ISSUE THREAD

**Issue by trilexcom** [An-Sar/PrimalCore#136]
hi PrimalCore team 

i have a little question i have my Iron Cauldron sitting on a netherrack with fire like this 

https://imgur.com/a/vyOql

i see some white flakes coming from the Cauldron i am going to guess its steam but i dont see it turning in to Tannin ?

do i need a better heat source to make the Tannin or netherrack with fire on the top is enough ?

Mat

**Comment by trilexcom** [comment]
after putting the lid on it i got tannin lol i guess when you contact support it works lol

**Comment by trilexcom** [comment]
i guess we can close this ticket lol

**Comment by An-Sar** [comment]
it takes time for the cauldron to heat up. There is a "Cauldron Ladle" item that allows you to see the current heat level, fluid, and items that are in the cauldron at any given time.

You sneak click the side of the cauldron to see the contents, and sneak click the top to fish out items, including ingredients and items that recipes output as a product.

Additionally you can fish items out by hand, but doing so on a hot cauldron will harm the player

**Comment by trilexcom** [comment]
thanks An-Sar you are awesome. i really love your mod.

**Comment by An-Sar** [comment]
for heat sources you can also place the cauldron on iron slats or on a drain block, with a heat source below, closing or opening the drain will effectively turn the heat on or off.

thank you, i've glad you like the mod!

**Comment by trilexcom** [comment]
hey An-Sar i have another question for this.

so when i put in dried hide in the iron Cauldron for some reason after saying i have dried hide with tannin in the cauldron i lose my tanned hide in the cauldron is this a bug ? or am i doing something wrong ? or is their a chance of losing your dried hide in the cauldron when its making ?

Mat

**Comment by An-Sar** [comment]
there is a recipe bug causing secondary runs to loose the output item.

**Comment by trilexcom** [comment]
i am going to close this ticket its working beautifully thank you very much.
