### ISSUE TITLE
OpenBlock SleepingBag won't work if you click it ?

### ISSUE THREAD

**Issue by trilexcom** [An-Sar/PrimalCore#139]
hey An-Sar when we have PrimalCore with OpenBlock installed in the Trilex Pack if you click on the sleeping bag when you click it, it doesn't let you sleep? but if you put sleeping bag in your chest area it lets you sleep?

and if you remove PrimalCore from the modpack openblocks works fine ?

how do i get a log for this issue for you ? 

I am running Trilex Pack

OpenBlock version: -1.75
PrimalCore: 0.6.21 or if you download the latest version of the pack does the same 
OpenModsLib Version : 0.11.5
Forge version: 2607
MC : 1.12.2

**Comment by trilexcom** [comment]
boq from openblock told me its armorswap let me try that

**Comment by trilexcom** [comment]
that worked i can close this ticket now

**Comment by trilexcom** [comment]
for some reason when i put armor swap false in a test pack i just made open blocks sleeping bag is working but if i do in my pack the bag won't work i cant click it ? am i doing something wrong?

**Comment by trilexcom** [comment]
if i set to false in my test pack i can sleep if its set to true it won't let me sleep. in my pack i put to false i went in a test world it let me sleeping if i click on it but if you put it in my chest place its working when i restart the pack with true enabled the bag goes in my chest place but it won't let me lay down to down? 

so is this primal issue or openblock issue ? in my log i don't see anything that i can show you regarding this problem? 
[2018-01-31-7.log](https://github.com/An-Sar/PrimalCore/files/1683383/2018-01-31-7.log)

**Comment by An-Sar** [comment]
i've added a blacklist for armor items to the config, and added openblocks:sleeping_bag as a default

BLACKLIST_ARMOR_SWAP

**Comment by An-Sar** [comment]
i believe this is resolved

**Comment by trilexcom** [comment]
Awesome i will be play through the pack again tonight with the new update i
have prepared should be fun to test

Thanks again

Mat

**Comment by trilexcom** [comment]
Should i wait for you to release that before i package her up for curse
upload ? I mean i am not in rush to push the new update

Thanks

Mat

**Comment by An-Sar** [comment]
could do, hopefully releasing in a few hours

**Comment by trilexcom** [comment]
Awesome
