### ISSUE TITLE
Bug With Tinkers Tools

### ISSUE THREAD

**Issue by kitsushadow** [An-Sar/PrimalCore#14]
When placing an un-upgraded Tinkers Stone Tool in the Birch Shelf it causes it to turn white upon use the block it breaks returns nothing and it becomes broken.

**Comment by An-Sar** [comment]
I think the shelves are loosing the item NBT, this means enchanted tools would loose their data as well. Will need to test and rework.

**Comment by An-Sar** [comment]
this has been fixed and will be pushed as part of the next release, 0.2.3

**Comment by An-Sar** [comment]
This has been released.
