### ISSUE TITLE
Lit torches change status to unlit when underwater

### ISSUE THREAD

**Issue by dariusfontan** [An-Sar/PrimalCore#141]
First of all: Awesome Mod, I really love what you guys are doing!
I have a small request:
Is it possible to make it so, that when you hold lit torches in the left or right hand
they would automatically change their status to unlit when going underwater ?
I mostly play with dynamic lights on and explore dark areas with a torch in hand.
Sadly when going underwater the torch keeps lit and still emits light, so this kinda breaks the immersion.
Maybe there could also be a small chance, that a torch goes unlit when being outside while its raining.
Just some thoughts, keep up the great work!

**Comment by An-Sar** [comment]
Good Idea. 
i have implemented this for the primal torches, currently lit wood and nether torches anywhere in your inventory will go out if the player is fully in water, if the player is rained on wooden torches in the hotbar or a hand will have a chance of going out. this also effects torches dropped as items in world.

currently handling for the vanilla torch block in player inventories is kind of looking overly heavy, so i'm not sure if it's worth while attempting.

**Comment by cScotPlay** [comment]
Oh this is evil but sounds like a realistic enhancement.

**Comment by An-Sar** [comment]
This has been released with 0.6.25 for testing

**Comment by dariusfontan** [comment]
Wow, that was fast, thank you so much! 
I'll try it out ASAP!

**Comment by An-Sar** [comment]
let me know how it works out. i need to figure something out for handling the vanilla item

**Comment by RiverC** [comment]
Seems like it puts torches out when you touch water rather than when you are submerged. Can anyone else confirm this behavior? (Not sure how 'submerged' you need to be)

**Comment by An-Sar** [comment]
yeah i am going fix the water issue, right now its pretty much just looking at your feet
