### ISSUE TITLE
Cauldron issues

### ISSUE THREAD

**Issue by RiverC** [An-Sar/PrimalCore#142]
I know Cauldrons are still in development, so I don't know if these issues have already been identified and plan to be fixed. In any case, I've been messing around extensively with Cauldrons in my modpack and found some issues/possibly reasonable changes.

1. If the player has no inventory room when drawing with the ladle, the item is deleted. I'd expect either to fail to remove or to spit the item out like it is thrown with the "q" key. 

2. I had weird behavior where I had 3750 mb of water and 15 tannin (ground) - I ended up with 3000 liquid tannin and 3 ground tannin, when I expected 3750 mb of tannin (liquid.) The rest of the water was deleted.

3. the recipe for muck to mud and slime balls works, but instead of converting 3 muck to 2 mud + 1 slimeball, it converts 1 muck to 2 mud + 1 slimeball, leaving 2 muck unprocessed. After that the recipe doesn't work (presumably due to insufficient muck!) I think this might allow some slime arbitrage but I didn't test that far.

**Comment by An-Sar** [comment]
1, so what i think is happening is that the item is dropping directly back into the cauldron, i could try to offset it to a side maybe

**Comment by An-Sar** [comment]
3, this should now be fixed in 0.6.28

**Comment by RiverC** [comment]
Can confirm all three:

1, it now tends to actually fly out and then back in, which although makes the item difficult to retrieve the second time (now it is an ingredient rather than a result) at least doesn't delete the item. This actually makes sense for what would happen trying to remove something from a pot while your hands are full

2. Definitely working with 250mb units now

3. Muck recipe now consumes all muck.
