### ISSUE TITLE
PrimalCore stone chunks,sand lakes...override other mod bushes, trees, and structures

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#143]
The PrimalCore different stone chunks, sand lakes, or even trees, seems to generate after every other mod generations, without caring about all bushes, trees, and structures that could have spawn at this place. It has for consequence many removed bushes, crops, saplings, and flying trees and bushes appear.

**Comment by WrongWeekend** [comment]
In addition to this it seems that the sandstone in desert village buildings (probably wells and desert temples as well, but I have not found any examples of those) gets replaced by Primalcore blocks as well.
