### ISSUE TITLE
Grass Roots for sheared grass 

### ISSUE THREAD

**Issue by cScotPlay** [An-Sar/PrimalCore#145]
When shearing vanilla tall grass it leaves the grass roots attached.  We have disabled this in the config file but it still appears to happen.  Lines of the config file are as follows:

    # Certain perennial plants will leave roots behind allowing the plant to regrow.
    B:PERENNIAL_PLANTS_ROOT=false
    B:PLANTS_ARE_PERENNIAL=false
    B:PLANTS_AUTO_MAGIC=false
    B:PLANTS_ENABLE_INVASIVE=false
    D:PLANTS_RUSH_MOVEMENT=0.45
    B:PLANTS_TALL_GRASS_GROWTH=false
    B:PLANTS_TALL_GRASS_RAIN_SPREAD=false
    B:PLANT_AUTO_MAGICALLY=false

Curious if this was meant to be this way if so would it be possible to get a config setting to turn off shearing of grass leaves grass roots.
PrimalCore ver - 1.12.2-0.6.28

**Comment by An-Sar** [comment]
this is actually intended, as some of the plants are impossible to farm when the invasive and perennial features are disabled.
