### ISSUE TITLE
Disable Vanilla Iron No functionnal

### ISSUE THREAD

**Issue by roulito** [An-Sar/PrimalCore#147]
I'm doing a modpack hardcore and based on your mod except that I don't want people to have once make the flint pickaxe directly mine and advance suddenly in the modpack. In a modpack, iron = do everything.
So, I wanted to disable iron ore and give people the opportunity to get them with a quarry, but unfortunately, by activating the option, the iron ore doesn't disappear from the map.
![2018-02-19_16 22 34](https://user-images.githubusercontent.com/8797474/36395250-7f0401c8-15b8-11e8-98d0-9b570f241fbd.png)
![2018-02-19_16 22 48](https://user-images.githubusercontent.com/8797474/36395254-81c17256-15b8-11e8-99aa-7c2c4f12252d.png)

**Comment by An-Sar** [comment]
this has been fixed and will be released with 0.6.29
