### ISSUE TITLE
Visual issue extending day using SURFACE_PROVIDER_OVERRIDE

### ISSUE THREAD

**Issue by SwordShaman** [An-Sar/PrimalCore#148]
When setting SURFACE_PROVIDER_OVERRIDE to true and using  SURFACE_DAY_LENGTH=96000.0, I'm getting a strange issue that I don't remember having earlier when you initially implemented this feature.  The sun moves slowly across the sky as expected, however the ambient light slowly acts as if day is the normal vanilla minecraft speed.  The stars come out a little after the ten minute mark, even though the sun is only a quarter of the way through the sky.  Mobs don't spawn even though it appears dark, and the moon obviously hasn't come up since the sun is still in the sky.

I do run shaders, however I've attempted to disable them to see if they are the issue, however I get this same problem with or without them.  I am running optifine.

**Comment by An-Sar** [comment]
nothing has mechanically changed with this feature. Do you have a complete mod list?

**Comment by SwordShaman** [comment]
animania
AutoRegLib
BackTools
Baubles
BetterFoliage
Biome_Bundle
Bloodmoon
Blur
Boitania
CarryOn
chameleoncreepers
coroutil
CraftStudio
CreativeCore
DynamicSurroundings
environmentalcreepers
FancyBlockParticles
iChunUtil
ItemPhysics
jei
LevelUp
MobAmputation
MobDismemberment
MultiMine
OpenTerrainGenerator
Optifine
OTG-Core
PotionCore
QualityTools
Quark
QuickLeafDecay
RealFirstPersonRender
RealBench
SmoothWater
SoundFilters
SwingThroughGrass
Survivalist
zombieawareness

**Comment by SwordShaman** [comment]
The only thing I could think of that may be conflicting was Open Terrain Generator and Biome Bundle, as they modify terrain generation obviously.  I removed them and with vanilla terrain gen, I still get this issue.

**Comment by An-Sar** [comment]
is this on a dedicated server?

**Comment by SwordShaman** [comment]
It is singleplayer currently.

**Comment by An-Sar** [comment]
it's interesting, i am currently using the primal extended days on a server without any issues, however i experienced almost identical problems when i tried to switch to use StellarSky, which changes the sky rendering and has a similar tick control over time.

i wonder if there is some common mod interaction, will have to do some testing.

**Comment by An-Sar** [comment]
this is just a shot in the dark but have you tested without DynamicSurroundings?

**Comment by SwordShaman** [comment]
Just tested it with a new world and without DynamicSurroundings, same result.  Good suggestion, though.  Hmmm...I really don't know where to go from here.

I could try hosting my same mod build on a forge server and see if it's just local singleplayer that has this bug.  I'll get back to you with the results.

**Comment by SwordShaman** [comment]
Well, unfortunately my server had the same problem.  Sorry I haven't been able to nail this down any more for you.  Could it be a forge issue?  Currently I'm playing on the latest recommended build, 1.12.2 - 14.23.2.2611.

**Comment by An-Sar** [comment]
i'm using the same forge version on my server so that shouldn't be playing a role in the issue.

**Comment by An-Sar** [comment]
can you test without blood moon?
