### ISSUE TITLE
Crash while exploring; something about pumpkins?

### ISSUE THREAD

**Issue by belathus** [An-Sar/PrimalCore#15]
http://pastebin.com/raw/bHr8XRu1

I admit, I don't know who to report this to. I've gotten this crash 3 times now, and a different mod is referenced in each of them. Always, though, with the pumpkins.

**Comment by An-Sar** [comment]
I was never able to recreate this issue, I'm going to go out on a limb and assume it's not directly related to primal and close this issue. Please report if this is still a thing. Thank You
