### ISSUE TITLE
[1.12.2] Grass on NetherEx mushrooms

### ISSUE THREAD

**Issue by NotAVerb** [An-Sar/PrimalCore#150]
I think this looks really ugly. Is there any chance of generation being tweaked to prevent this from happening?
![2018-02-27_07 03 35](https://user-images.githubusercontent.com/30223331/36727775-65122912-1bb6-11e8-82a1-66e7f18576f6.png)

**Comment by An-Sar** [comment]
yes, actually i was meaning to add a config that would limit the worldgen to only netherrack type blocks. it will most likely not be on by default but easily enabled.

**Comment by An-Sar** [comment]
i've added the config GEN_CINERIS_NETHERRACK_ONLY, it keeps the vast majority of the grass of non-netherrack type blocks, there is currently a little tiny bleed over here and there, which could be considered a feature? =D

**Comment by An-Sar** [comment]
added GEN_CINERIS_IS_WILD boolean that enables the current generate on everything functionality, default "false"

added GEN_CINERIS_WHITELIST that includes a number of default blocks that the cineris is allowed to generate on

**Comment by An-Sar** [comment]
this has been added in 0.6.36
