### ISSUE TITLE
Tough As Nails integration breaking armor warming effects.

### ISSUE THREAD

**Issue by MastrPancake** [An-Sar/PrimalCore#151]
I first thought this was a problem with TAN but i discovered this mod is causing the Wool and Slime armor not to take effect.

**Comment by An-Sar** [comment]
what versions are you using?

**Comment by MastrPancake** [comment]
Tough As Nails: 3.1.0
Primitive Core: 0.6.35

**Comment by MastrPancake** [comment]
https://youtu.be/rHI9LK_BQ88

**Comment by MastrPancake** [comment]
Its part of Tough As Nails. Just do /tan tempinfo

**Comment by An-Sar** [comment]
that's good to know haha, thanks for all the info

**Comment by MastrPancake** [comment]
Glad i could help!

**Comment by An-Sar** [comment]
this has been fixed in 0.6.36
