### ISSUE TITLE
[1.12.2] Game Crashed when right-click on Ceramics armor to put it on...

### ISSUE THREAD

**Issue by Fireztonez** [An-Sar/PrimalCore#152]
Hello, I have a problem with the Fired Clay Armor and unfired Clay Armor by Ceramics...
When I right-click whit one pieces of the armor in my hand, the game completely crash and I need to restart the complete Modpack. This armor is needed for my Modpack, where the leather is take a multiple multiple day's to have, so the Fired Clay Armor and unfired Clay Armor is the 2 realy early game in my pack.

I test with a new pack, where I just install Ceramics, CraftTweaker and JEI and the everything work's fine! When I add PrimalCore, the game start crashing when I do the same-thing...

Minecraft 1.12.2
PrimalCore v. 1.12.2-0.6.39
Ceramics v. 1.12-1.3.3b
Forge 14.23.2.2616
Java: 8 (1.8.0_161-b12 64bit)

Crash Log: https://gist.github.com/Fireztonez/124fc08ec5a5cf38f332533ffa9fd80b

**Comment by KnightMiner** [comment]
Issue from my tracker is KnightMiner/Ceramics#34. I currently have a null sound for my armor types which causes vanilla to just play no sound, but apparently crashes here.

**Comment by An-Sar** [comment]
as an immediate fix you can add the armor to a blacklist in the config BLACKLIST_ARMOR_SWAP

also i will look at adding a check for null sounds, thanks for the info!

**Comment by Fireztonez** [comment]
ok thank's for the reply, I add that in the config just now!

**Comment by An-Sar** [comment]
the null check fixed the crash, will be part of the next release

**Comment by Fireztonez** [comment]
For the armor, my problem is fixed by adding into the blacklist!
Thank's again!
