### ISSUE TITLE
[Suggestion] Additional cauldron/food recipes

### ISSUE THREAD

**Issue by WrongWeekend** [An-Sar/PrimalCore#153]
Some ideas (mostly food) that I think would make this mod's cauldron more useful:

Ground wheat + water = gruel

Ground corn + water = grits

Raw potato + water = baked potato (technically boiled, but there probably isn't much sense in creating an extra item for this)

Raw beef + brine = corned/cured beef

Beetroot + brine = pickled beetroot

Fish + brine = pickled fish

Sugar + water = molasses (fluid)

Grits/gruel + molasses = hasty pudding

Container of molasses + ground corn, ground wheat, or sugar = groundbait, can be used for fish traps

**Comment by An-Sar** [comment]
i like the idea of more common place recipes like this.

**Comment by Ash70** [comment]
Also please add crafttweaker support to the cauldron.

**Comment by An-Sar** [comment]
cauldron has CT support now, and more recipes will be added as we go along
