### ISSUE TITLE
Crash with Leather Works

### ISSUE THREAD

**Issue by CobaltRealm** [An-Sar/PrimalCore#155]
Hey!

The game crashes with Leather Works instaled

https://pastebin.com/h67dq202

**Comment by CobaltRealm** [comment]
Cleverpanda told me that he fixed it in the 1.65.7 version of the mod, sorry....

**Comment by An-Sar** [comment]
no worries, i am linking the leatherworks issue here https://github.com/MinecraftModDevelopmentMods/LeatherWorks/issues/14
