### ISSUE TITLE
[JEI] Tooltips misinformation about Urushi to Lacquer wood

### ISSUE THREAD

**Issue by alxcool** [An-Sar/PrimalCore#156]
PrimalCore-1.12.2-0.6.40
ForgeCraft-1.4.06

Hi! While playing, I have encountered quite an issue concerning the use of Urushi to create lacquer woods. I don't remember why but my single-player game is configured in a way that the easy way to craft a Urushi stick is disabled, the cauldron is mandatory.
Also, JEI suggest a recipe who is not accurate. When you watch the Forgecraft video, the recipe suggest to use one ground Urushi per sticks. JEI suggest to use 1 mb of liquid Urushi (250mb) per sticks or 10/5 mb of liquid Urishi per planks.

What happen is also weird. When I place 250 mb of water with 1 ground Urushi in a properly heated cauldron, it take between 2-4 min to dilute, then start cooking with sticks if present for the same amount of time. Then, after 4-8min 1 lacquer stick is created, 1mb of liquid Urushi is removed from the cauldron's inventory, then the cauldron enter on a disabled state like if he way empty of any liquids. Visually I still see the purple liquid in the bottom of the cauldron. The only recipe possible to complete after that is a cauldron slag.

If I want an another Lacquer stick in order to fix my Iron pickaxe, I have to break the cauldron, and configure it again...  pour 250 mb of water, drop, a ground urushi and a stick and wait for 8 more min.

So could someone explain me how to config the game to allow me, once again, to craft lacquer stick again simply by using a crafting table, and, could I suggest to increase the cauldron cooking speed by let say... 4 time?

**Comment by An-Sar** [comment]
There is currently a bug that makes the cauldron fail to process recipes when the fluid level is below 250mb, this is currently being fixed. 

Also the way cauldron recipes are timed is getting some internal changes, there is a config to adjust the speed with the current system, but the precise nature of that config will likely change as a result of the coming changes.

The urushi amounts per stick and plank are also changing a bit in the upcoming release. JEI reflects the actual in-game recipe, so is and will be more accurate than recipes shown in videos.

**Comment by alxcool** [comment]
I hope I din't send too much of my irritation while writing, both mod are on my favorite list. I don't know if this could help, but similar bug have been fixed with item return in a recipes who takes damage point. Most likely tool. As example, in older version of Animalia, the knife used to cut a cheese, could only be used once because as soon as he took damage, the item needed to be fix to full heal before being used again. That might be the same logic that apply to liquid lower than 250 mb (mean can't be stored in bucket or glass bottle) as the result is too small.
