### ISSUE TITLE
[Suggestion] Some new crafting items/forms

### ISSUE THREAD

**Issue by WrongWeekend** [An-Sar/PrimalCore#157]
I was thinking of some ways to craft familiar items that make more sense as components to finished products already in Minecraft.

Wool: sheared in bunches of dirty raw wool rather than blocks. Must be boiled in limewater (obtained by mixing slack lime from portlandite with water in a cauldron) in a cauldron to clean the impurities from the wool. The cleaned raw wool is then sun-bleached on a drying rack to become fully processed wool sheets. This processed wool can be combined into blocks, boiled in water and pressed/dried into felt, or spun into yarn which can be then woven into cloth. These products can then be used to make beds, carpets, banners, etc.

Silk: Cloth which can be crafted from spider silk string, usable in the same manner as wool cloth or felt.

Flower Pots/Other potential ceramics: must be molded from one or more wet clay balls on a pottery wheel to form an unfired shape. The shape must then be fired in a kiln to create the finished product.

Glass: The sand or glass is heated into molten glass, which is then blown into the mold of a bottle or other object with a glassblowing pipe. Panes and blocks may simply be created from molten glass inserted into molds without blowing.

Paper: Made by boiling/drying plant/papyrus/wood pulp in water, then pressing and drying. Parchment may be obtained by boiling raw animal hides in limewater then placing them on a drying rack. This material, when dried, then may be cut up to make sheets of parchment, usable in place of paper.

(Flat)bread: Ground wheat/corn is mixed with water and salt to make unleavened wheat/corn dough, then cooked on a hibachi to make flatbread. The dough may also be combined with yeast (from apple skins) to produce leavened dough for existing leavened bread, cooked in a furnace or oven.

**Comment by Fireztonez** [comment]
That's is exactly what I looking for and what I whan't in my modpack... I already started to make real multiple of all that features, with better with mods and better with addons and other mods, but for sure adding your way should be cool and probably more realistic!

But, again, I think is really important to give more control to modpack dev and integrate as fast is possible the crafttweaker support in priority to all other additional features I think.

Thanks again for your amazing mod!
Fireztonez

**Comment by An-Sar** [comment]
There is definitely going to be a paper process, integrated into the book system, and will get additional use in MagnumOpus for purposes of crafting scrolls and similar.

@Fireztonez CT support is coming in the next release, 0.6.45
