### ISSUE TITLE
[Compatibility] Duplication Bug when pickup Cauldron with Carry-On

### ISSUE THREAD

**Issue by Fireztonez** [An-Sar/PrimalCore#158]
When I take the Cauldron with Carry-on, a Cauldron falls to the ground, as if I was mining it, and I have the original in my hand ... So it is really easy to reproduce it in infinite quantity in a few seconds !

For sure, I can blacklist the pickup cauldron by Carry-On, but I think it's really helpful to pick up the cauldron when there is a liquid in it.

**Comment by Fireztonez** [comment]
I just test that with a new pack with only PrimalCore, Carry-On and JEI install, and the same bug appen.

Minecraft: 1.12.2
Primal-Core : 0.6.41
Carry-On: 1.7.2
Forge 14.23.2.2632

Fireztonez

**Comment by Fireztonez** [comment]
I just report to Carry-On, if you want the link:
https://github.com/Tschipp/CarryOn/issues/88

**Comment by An-Sar** [comment]
i can look into carry-on to see what i can do to support it.

My inclination would be to disable the pickup function entirely, and make it so the cauldron can carry its contents when the lid in on, similar to the primal barrels.

**Comment by An-Sar** [comment]
it would be interesting to see if the dup bug exists with a covered barrel also

**Comment by Fireztonez** [comment]
I try right-now if you whant with the covered barrel!

**Comment by An-Sar** [comment]
yeah that would be good

**Comment by Fireztonez** [comment]
I just try, and the Cauldon and the Cover is duplicate in that case...

**Comment by Tschipp** [comment]
If you want to look at it, you need to look here:

```  public void dropItemsAndBlock(World world, BlockPos pos, IBlockState state)
  {
    if ((!field_72995_K) && (world.func_82736_K().func_82766_b("doTileDrops")) && (!restoringBlockSnapshots))
    {
      TileEntity tile = world.func_175625_s(pos);
      if ((tile != null) && ((tile instanceof TileCauldron)))
      {
        float offset = 0.7F;
        



        for (int i = 0; i < ((TileCauldron)tile).getCraftingHandler().getSlots(); i++) {
          ItemStack stack = ((TileCauldron)tile).getCraftingHandler().getStackInSlot(i);
          
          if (!stack.func_190926_b()) {
            double offsetX = PrimalAPI.getRandom().nextFloat() * offset + (1.0F - offset) * 0.5D;
            double offsetY = PrimalAPI.getRandom().nextFloat() * offset + (1.0F - offset) * 0.5D;
            double offsetZ = PrimalAPI.getRandom().nextFloat() * offset + (1.0F - offset) * 0.5D;
            EntityItem item = new EntityItem(world, pos.func_177958_n() + offsetX, pos.func_177956_o() + offsetY, pos.func_177952_p() + offsetZ, stack);
            item.func_174869_p();
            world.func_72838_d(item);
          }
        }
        

        for (int i = 0; i < ((TileCauldron)tile).getOutputHandler().getSlots(); i++) {
          ItemStack stack = ((TileCauldron)tile).getOutputHandler().getStackInSlot(i);
          if (!stack.func_190926_b()) {
            double offsetX = PrimalAPI.getRandom().nextFloat() * offset + (1.0F - offset) * 0.5D;
            double offsetY = PrimalAPI.getRandom().nextFloat() * offset + (1.0F - offset) * 0.5D;
            double offsetZ = PrimalAPI.getRandom().nextFloat() * offset + (1.0F - offset) * 0.5D;
            EntityItem item = new EntityItem(world, pos.func_177958_n() + offsetX, pos.func_177956_o() + offsetY, pos.func_177952_p() + offsetZ, stack);
            item.func_174869_p();
            world.func_72838_d(item);
          }
        }
      }
      




      PlayerHelper.spawnItemOnGround(world, pos, new ItemStack[] { func_185473_a(world, pos, state) });
      
      if (isCovered(state)) {
        PlayerHelper.spawnItemOnGround(world, pos, new ItemStack[] { getLid(state) });
      }
    }
  }```

You also need to test if the TileEntity is invalid, not just if it is null. I think that will fix the issue. The alternative is that I add the mod to the default blacklist.

**Comment by An-Sar** [comment]
yeah there is some non-standard drop code for a grip of blocks that have tile entities, this is on my list for the next release, got carry-on in my dev environment now, i will update here how that goes.

i do ((tile instanceof TileCauldron))), where you thinking of an additional check?

**Comment by Tschipp** [comment]
yes, `tile.isInvalid()`

**Comment by An-Sar** [comment]
ah, interesting, i will def check that out.

**Comment by An-Sar** [comment]
checking tile.isInvalid() corrects the duplication, so that's very good

a few other things i notice when testing drying racks, the blocks facing get's lost or is inverted upon placement. possibly my facing code is strange.

and then the block's woodtype texture is not displayed while the block is in hand, the blockstate responsible for the texture is determined by NBT, again possibly strange code on my part.

**Comment by Tschipp** [comment]
Great!
For the facing, maybe check out how chests are placed.
For the render, if your model is dependent of NBT, a model override needs to be made in the CarryOn config.

**Comment by An-Sar** [comment]
dup bug fixed with 0.6.43

**Comment by Fireztonez** [comment]
Super, thank's!

**Comment by An-Sar** [comment]
it's possible i've missed a few blocks, so if you come across anything else just update this issue.

thanks
