### ISSUE TITLE
Dust Bin is not named

### ISSUE THREAD

**Issue by d7u8d9e** [An-Sar/PrimalCore#159]
The dust bin is named "tile.dust_bin.name" on mouseover. SevTech: Ages modpack is used.
![image](https://user-images.githubusercontent.com/23158681/37880570-6c3a29c0-3050-11e8-9da1-1fb127dd9993.png)

**Comment by An-Sar** [comment]
This is actually a bug with the crafting recipe, producing an generic bin without a proper wood type.

That being said the bins are currently under development, so they are not currently functional, the recipe wasn't meant to be left active for the release.

**Comment by An-Sar** [comment]
this is related to https://github.com/An-Sar/PrimalCore/issues/13

**Comment by An-Sar** [comment]
recipes have been fixes, but are disabled until the bins are fully functional.
