### ISSUE TITLE
Crash related to EarthWax's Flammability

### ISSUE THREAD

**Issue by belathus** [An-Sar/PrimalCore#16]
I've got another crash for you. Pretty sure this one is PrimalCore.

pastebin.com/raw/C3yF2x1L

**Comment by An-Sar** [comment]
At first glance it looks like this is a conflict with abyssalcraft BlockMimicFire. I am going to add abyssal to my dev environment and debug further.

**Comment by An-Sar** [comment]
We accidentally recreated this crash on a server, I am going to rework the earthwax class and will push as part of 0.2.3

**Comment by An-Sar** [comment]
This has been released.
