### ISSUE TITLE
Rustic fluid bottles do not interact properly with Primalcore's barrels

### ISSUE THREAD

**Issue by WrongWeekend** [An-Sar/PrimalCore#160]
From the mods I've tried, Rustic's fluid bottles seem to work fine interacting with any fluid container, but they do not work with primalcore's barrels.

**Comment by An-Sar** [comment]
to clarify is the problem you ran into extracting a rustic fluid by bottle? i was able to insert fluids from the bottles without issue.

**Comment by WrongWeekend** [comment]
That's the problem, filling the bottle doesn't work, but emptying into the barrel does.

**Comment by An-Sar** [comment]
ok, good, in that case this has been resolved

**Comment by An-Sar** [comment]
fixed with 0.6.43
