### ISSUE TITLE
Stacked buckets wont pull water from barrels

### ISSUE THREAD

**Issue by justinrusso** [An-Sar/PrimalCore#163]
When using a bucket that is in a stack, it does not pull the liquid out of the bucket. Once un-stacking the bucket, it does work.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/1281

---
#### Versions:
Primal Core: 0.6.44
Forge: 14.23.2.2641

**Comment by An-Sar** [comment]
this has something to do with detecting the bucket's fluid capability while it's stacked, i will need to do some testing to see what the best solution is.

**Comment by An-Sar** [comment]
this has been resolved in recent versions
