### ISSUE TITLE
[12.2] Hang on chunk population causing cascading world gen lag (Sevtech)

### ISSUE THREAD

**Issue by longtomjr** [An-Sar/PrimalCore#164]
While moving around (possible creating new chunks) the game hanged. Had to force exit it.
Here is the log: [Log](https://paste.ee/p/xrx1k)

Thanks
**Versions:** 
Primal Core: 0.6.44
Forge: 14.23.22635
Minecraft: 12.2
SevTech Ages: 3.0.4

**Comment by longtomjr** [comment]
Can I get the issue number of the one this is a duplicate of. I searched (prolly like my rear) and could not find it. Sorry for the dupe

**Comment by An-Sar** [comment]
there are a few actually, i wish there was a better way to merge issues.

https://github.com/An-Sar/PrimalCore/issues/154
https://github.com/An-Sar/PrimalCore/issues/41

at some point soon i will be looking at worldgen as a whole, and hopefully working over the entire system.
