### ISSUE TITLE
This is a Question in regards to Drying Racks.

### ISSUE THREAD

**Issue by Dietz8** [An-Sar/PrimalCore#166]
I've been messing around with the Primal Core mod the last few days and for some reason I am unable to get wet thatch to dry on the drying racks. I've checked the wiki page and found no real useful info there. I've tried many different things so far, leaving racks in direct sunlight, putting a torch beneath the rack. I'm at a loss any info would be much appreciated.

**Comment by thaimichael** [comment]
It takes a long time for thatch to dry.  You can check the settings in the primal.cfg to see what the settings are depending on the modpack:

>     # Modifier for how long it takes wet thatch to dry, this values is reduced by half when thatch is exposed to the sun, however rain will pose a problem
    # Min: 0
    # Max: 100
    I:DRY_TIME_THATCH=40

Hope this helps

**Comment by An-Sar** [comment]
there is a debug tool "Dirt Stick" in game that will show you the drying status of a rack, basically counters for each slot. If you see the counters decreasing that will at least verify the rack is working correctly.

the I:DRY_TIME_THATCH config is actually for drying wet thatch blocks in world.

**Comment by An-Sar** [comment]
next release has a new config DRYING_RACK_DRY_TIME_MODIFIER, which is % modifier to decrease or increase the base recipe times.

**Comment by Vyraal1** [comment]
Sorry for the necro, but would it be possible to also have the Dirt Stick also say whether or not if the drying rack has a bonus or not? It could say something along the lines 'The drying rack is currently warm" or "The drying rack is currently cold."

**Comment by An-Sar** [comment]
that's a good idea

**Comment by codewarrior0** [comment]
I set some breakpoints and noticed that the drying rack block is not scheduled for updates when first placed, and not scheduled when I place an item on it. It is only scheduled for updates for the first time when I whack it with a dirt stick.

Using the stick on it shows the counter values like you say, but both a newly-placed rack and a rack that has been sitting for days both show counter values from 10 to 12.

PrimalCore-1.12.2-0.6.48

**Comment by An-Sar** [comment]
i noticed this also when watching the video that cscot just released, he was demonstrating the dirt stick and it was restarting updates. working on .51 right now and expect this will be fixed.
