### ISSUE TITLE
Yew gate has no recipe, and the ironwood gate has an additional, wrong recipe.

### ISSUE THREAD

**Issue by neothiamin** [An-Sar/PrimalCore#169]
![primalissue1](https://user-images.githubusercontent.com/8920936/38592355-97c0e7e4-3d09-11e8-8d8e-5ad9172938f5.png)

As you can see, the recipe that would be the yew gate actually makes an ironwood gate, and the yew gate has no recipe.

Also, it looks like the yew gate's name isn't localized correctly or something, because it's appearing as tile.gate_yew.name.

**Comment by An-Sar** [comment]
doh, i forgot to change the output item in the json recipe. fixed on both accounts.

thank you for reporting
