### ISSUE TITLE
Can't recover Lit Torches

### ISSUE THREAD

**Issue by kitsushadow** [An-Sar/PrimalCore#17]
When attempting to recover a lit torch the torch does not get added to the player's inventory.

**Comment by An-Sar** [comment]
I can't recreate this in dev or on a server, further information about how you encounter/recreate the bug is needed.

**Comment by kitsushadow** [comment]
1. Place an unlit torch
2. Light it with a lit torch
3. With an empty hand shift right click to recover the torch.

After retrying these steps it seems the torches are recovering normally. If I encounter it again I'll create a new issue for it.
