### ISSUE TITLE
[Suggestion] Early beds

### ISSUE THREAD

**Issue by Ash70** [An-Sar/PrimalCore#171]
Early bedding with limitations for more survival 'fun'.

Place 2 dried thatch next to each other and right click with an animal pelt to make a bed.

Have 3 config options:
THATCH_BED_SET_SPAWN = true|false  (sets spawn when used)
THATCH_BED_SKIP_NIGHT = true|false  (skips night or not)
THATCH_BED_BREAK_CHANCE = 0-100  (chance the bed breaks after use)

This would also mean making the vanilla bed recipe somehow harder to obtain (later game).

**Comment by An-Sar** [comment]
more bed/sleep related stuff is planned for the future
