### ISSUE TITLE
[Suggestion] Add the ability to turn grass blocks with rush seeds on them into grass paths

### ISSUE THREAD

**Issue by neothiamin** [An-Sar/PrimalCore#172]
Currently, if a grass block has rush seeds on it, you can't turn it into a grass path without breaking the block, placing the dirt back, and waiting for it to turn into grass. With a mod like Dirt2Path this becomes a little less cumbersome, but it would still be nice to be able to turn a grass block with rushes into a path and just have the rush seeds pop out of the block or something.

**Comment by An-Sar** [comment]
This works now, also applies to hoes making farmland, and to other types of plants, vanilla, etc.

Also primal has been able to make paths from dirt blocks itself for quite a while, there is a config hook to disable it, in the event it conflicts with other mods adding similar functionality.
