### ISSUE TITLE
Hibachi clown & pufferfish cooking

### ISSUE THREAD

**Issue by Ash70** [An-Sar/PrimalCore#173]
Version 0.6.46

Clownfish and pufferfish can be cooked on the hibachi, but they result in nothing since MC does not have cooked variants of them.

Also: removing Hibachi recipes with crafttweaker can only be done by recipe name. Can you provide the names of the existing (default) recipes you used?

**Comment by An-Sar** [comment]
Fixed missing fish items.

Also i have added the existing recipes to the relevant [wiki pages](https://github.com/An-Sar/PrimalCore/wiki/CraftTweaker)
