### ISSUE TITLE
[Bug] Sometimes items dropped in cauldron is simply eat 

### ISSUE THREAD

**Issue by Fireztonez** [An-Sar/PrimalCore#176]
Sometimes the items toss in the cauldron are only eat, without added to the item list contained. Last night, I threw in a cauldron filled with 2x16 water from Ground Resin, without any of them being counted, only the 3rd battery of 16 to work and was counted.

Another thing, it would be nice if the items inside appear on a line by calculating the total quantity, because only the last 4 lines are said, very often I see slag on 3 of them. I can never really know how many things I actually have inside because of the fact that it does not add up correctly to other numbers.

**Comment by An-Sar** [comment]
Already fixed in dev

**Comment by An-Sar** [comment]
the cauldron only holds four slots, that is the crux of the bug, in that it was eating items beyond that limit, now if it's full the items wont go inside at all.

This means periodically, between recipes, slag will need to be removed to accommodate new items. The slag generation rate is also going to get some adjustment, i think it's a bit high atm.

**Comment by Fireztonez** [comment]
Ok, perfect!
Thank's for that information!
