### ISSUE TITLE
[Suggestion] Configs to Disable Redundant Metal Blocks / Plates / Ingots

### ISSUE THREAD

**Issue by Vyraal1** [An-Sar/PrimalCore#179]
Low priority because modpack dev's can easily use crafttweaker to remove / hide these items, or remove them from ore dictionary, but having these configs could also save us time.

As for the metal blocks, it could also reduce the block id usage of the pack.

As for suggested config template, you could type it as:
```
Config
#Disable if you already have a mod that handles these microcrafting ingredients such as TConstruct or Thermal Foundation
B:Metal Parts - Copper: false
B:Metal Parts - Lead: false
B:Metal Parts - Pig Iron: false
B:Metal Parts - Gold: false
B:Metal Parts - Silver: false
etc.
```

**Comment by An-Sar** [comment]
ENABLE_SHARED_METALS

it will disable the registration of the common shared plate, ingot, dust, nugget types. Not including things that seem to be mostly specific to primal and already have extended crafting uses within primal (pig iron, tamahagane, wootz, etc)

there are some crafting recipes that returned plates and related items  as output, these should now pull the first ore dictionary match. we may need to tweak and bit with play testing etc. (0.6.69)
