### ISSUE TITLE
Primal Enchanting?

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#18]
Any chance for an enchanter for early game?

**Comment by An-Sar** [comment]
I might do something in MagnumOpus, but I also haven't really looked at the vanilla system since before they adding the use of lapis and such, so I need to get up to speed.

**Comment by An-Sar** [comment]
most likely content related to enchanting will either end up in MagnumOpus or the magic add-on @kitsushadow was planning, bits that do end up in primal i would most likely serve as foundation to be expanded by one of the add-ons.
