### ISSUE TITLE
Custom recipes with oredict entries do not show in JEI

### ISSUE THREAD

**Issue by Ash70** [An-Sar/PrimalCore#185]
Using an oredict ingredient in a custom recipe (e.g. <ore:foodVegetables>) shows an empty slot in JEI. I am uncertain this means it is either not displayed or not recognised (still struggling with cauldron recipes to get them to work).
BTW: what does 'cook_chance' do in the recipe?

**Comment by An-Sar** [comment]
was the empty slot issue specifically with adding cauldron recipes?

cauldron recipe syntax has changed in the most recently version .48, the inputs and outputs are now passed as arrays, making the recipes a bit cleaner to look at.

updated information is on the [wiki](https://github.com/An-Sar/PrimalCore/wiki/CraftTweaker:-Cauldron) , can you see if the problems are still occurring with the new version?

in regards to cook_chance, this is currently the RNG % chance each time the cauldron updates that the recipe will complete. i am very interested in feedback about how recipe times feel, it is a possibility that i will switch the cauldron from straight RNG over to a timer.

**Comment by Ash70** [comment]
No, I checked and it also doesn't work with the Hibachi.
I did a few tests with .48

`
Cauldron.addRecipe("itf_cooked_rice", 1.0, 
    <liquid:water> * 100, null,
    [<ore:foodRice>, <ore:foodRice>, null, null], 
    [<realworld:food_cooked_rice>, null]);
`
Shows as follows in JEI:
![2018-04-28_10 59 30](https://user-images.githubusercontent.com/22838247/39394610-3a4f764c-4ad4-11e8-82c9-a156e2d6735f.png)

Removing a Hibachi recipe like so:
`Hibachi.removeRecipe("Primal.CORN_BREAD");`
Still shows it in JEI, and still works:
![2018-04-28_11 02 50](https://user-images.githubusercontent.com/22838247/39394624-5fea850e-4ad4-11e8-9337-891526bc2437.png)
![2018-04-28_11 04 10](https://user-images.githubusercontent.com/22838247/39394627-65c5d51e-4ad4-11e8-8d7d-80c495174cc8.png)

**Comment by An-Sar** [comment]
For removing recipes, it currently uses the name, so your example above would be 

```
Hibachi.removeRecipe("ground_corn");

```

For the empty recipe it's possible those ore dict names are being added too late, the recipes register through the forge event system, so it more or less takes place between pre-init and init phases. i will do some testing.

**Comment by Ash70** [comment]
Did another test. Instead of using existing oredict entries, I made new ones with crafttweaker and now it almost works. So i does seem to be a problem with another mod(s).
The only thing still not working entirely is clicking on the result in JEI, it still shows twice the same recipe instead of both individual ones (like in the last screenshot in my other reply). Rightclicking on the ingredient does show the correct recipe however.

**Comment by Ash70** [comment]
Also, not sure if this is relevant, but it seems there is a recipe-event in forge that should be used. See https://github.com/BluSunrize/ImmersiveEngineering/issues/2458

**Comment by Ash70** [comment]
Okay, everything seems to work fine except for the JEI display-thing with the Hibachi (not showing all oredict entries when rightclicking the hibachi in JEI, just one. And showing a duplicate when looking up a recipe. Seems a minor issue.

In regard to your question about cook time. Personally I would prefer a timer instead of an RNG. Seems more consistent with the Hibachi as well.

**Comment by An-Sar** [comment]
should be resolved
