### ISSUE TITLE
PrimalCore loaded a new chunk during chunk population causing cascading Worldgen lag

### ISSUE THREAD

**Issue by Rayzerfang** [An-Sar/PrimalCore#186]
Playing Sevtech: Ages(v. 3.0.6) and I see this in my console continuously all the time.

**Comment by EEwing** [comment]
For reference, this is a duplicate of #110

**Comment by kiwifrogg** [comment]
The message is just a warning but in reality is not causing any issues, I have 2 primal core servers (one 7 months old) and neither have any issue related to this world gen message.
