### ISSUE TITLE
Shift right clicking with a work blade places vanilla torches from inventory

### ISSUE THREAD

**Issue by Alan19** [An-Sar/PrimalCore#192]
When I shift-right click a log with a work blade to strip it, it places a torch from my inventory onto the log. I can't shift-right click to remove it and it's only placing vanilla torches, not the lit torches from primal core.

**Comment by An-Sar** [comment]
this sounds like mod interaction, do you have a mod list?

**Comment by Alan19** [comment]
-   1.12.1-CustomOreGen
-   advancedmortars-1.12.2-1.6.20
-   AdvancedRocketry-1.12.2-1.4.0-79
-   AppleCore-mc1.12.2-3.1.1
-   AppleSkin-mc1.12-1.0.9
-   appliedenergistics2-rv5-stable-11
-   Aroma1997Core-1.12.2-2.0.0.0.b150
-   AromaBackup-1.12.2-2.1.1.3.b98
-   artisanworktables-1.12.2-1.18.5
-   astralsorcery-1.12.2-1.8.8
-   athenaeum-1.12.2-1.14.0
-   AutoRegLib-1.3-17
-   base-1.12.2-3.7.1
-   Baubles-1.12-1.5.2
-   BedBugs-1.12-1.0.1
-   BetterAdvancements-1.12.2-0.0.7.42
-   BetterBuildersWands-1.12-0.11.1.24569d0d70
-   BetterFps-1.4.8
-   BetterQuesting-3.5.256
-   BiblioCraft[v2.4.3][MC1.12.0]
-   BiomesOPlenty-1.12.2-7.0.1.2387-universal
-   blockcraftery-0.1.3
-   BloodMagic-1.12.2-2.2.12-97
-   Botania r1.10-354
-   ChatFlow-1.4-7
-   Chisel-MC1.12.2-0.2.0.31
-   chiselsandbits-14.16
-   ChunkPregeneratorV1.12-1.8
-   CoFHCore-1.12.2-4.4.1.12-universal
-   CoFHWorld-1.12.2-1.1.1.12-universal
-   ContentTweaker-1.12.2-4.5.0
-   Controlling-3.0.6
-   CosmeticArmorReworked-1.12.2-v1
-   CraftingTweaks_1.12.2-8.1.8
-   CraftTweaker2-1.12-4.1.8
-   CTM-MC1.12-0.2.3.12
-   CustomMainMenu-MC1.12.2-2.0.8
-   cyberware-1.12.2-0.2.10.12
-   CyclopsCore-1.12.2-0.11.5
-   DimensionalDoors-3.0.9-287
-   DungeonTactics-1.12.2-0.14.2
-   DynamicSurroundings-1.12.2-3.4.9.13
-   ElectroblobsWizardry-4.1.1-MC1.12.2
-   elulib-0.1.12
-   EnchantmentDescriptions-1.12.2-1.1.8
-   Enchiridion-1.12.2-3.3.3
-   EnderCore-1.12.2-0.5.22
-   EnderIO-1.12.2-5.0.22
-   EnderZoo-1.12.1-1.4.0.49
-   Erebus-1.0.22
-   EvilCraft-1.12.2-0.10.56
-   extraalchemy-0.3.8.4-release
-   foamfix-0.9.9-1.12.2-anarchy
-   forestry_1.12.2-5.8.0.285
-   Forgelin-1.6.0
-   Guide-API-1.12-2.1.5-60
-   ImmersiveEngineering-0.12-81
-   ImmersiveEngineering-0.12-81-core
-   InventoryTweaks-1.64-dev
-   IvToolkit-1.3.3-1.12
-   jei_1.12.2-4.9.1.175
-   jeibees-0.9.0.5-mc1.12.2
-   journeymap-1.12.2-5.5.2
-   librarianlib-1.12.2-4.9
-   LibVulpes-1.12.2-0.2.8-30-universal
-   llibrary-1.7.9-1.12
-   Login_Shield-1.12.2-1-g24c2a5e
-   LootTweaker-1.12.2-0.0.7
-   lostcities-1.12-2.0.7
-   MagicBees-1.12.2-3.1.9
-   MagnumOpus-1.12.2-0.0.17
-   Mantle-1.12-1.3.2.24
-   Mekanism-1.12.2-9.4.10.345
-   MetalChests-v1.2.2.g3d3d54b
-   modtweaker-4.0.5a
-   moreoverlays-1.13-mc1.12.1
-   Morpheus-1.12-3.3.2
-   MTLib-3.0.4
-   NaturesCompass-1.12.2-1.5.1
-   NetherEx-1.12-2.1.14.15
-   NetherPortalFix_1.12.1-5.3.13
-   NoFov-MC1.12-1.0.1
-   plustic-6.4.0.0
-   PrimalCore-1.12.2-0.6.50
-   Quark-r1.4-123
-   QuickLeafDecay-MC1.12.1-1.2.4
-   RecurrentComplex-1.4.7
-   RedstoneFlux-1.12-2.0.1.2-universal
-   Reliquary-1.12.2-1.3.4.760
-   ResourceLoader-MC1.12.1-1.5.3
-   ReWIRED-1.0.3
-   rockhounding_core-1.12.2-3.08
-   rockhounding_oretiers-1.12.2-3.05
-   RoguelikeDungeons-1.12.2-1.8.0
-   rustic-1.0.3
-   StandardExpansion-3.4.141
-   TConstruct-1.12.2-2.9.1.65
-   tellme-1.12.2-0.5.6
-   Thaumcraft-1.12.2-6.1.BETA13
-   TheBetweenlands-3.3.8-core
-   TheBetweenlands-3.3.8-universal
-   theoneprobe-1.12-1.4.22
-   topaddons-1.12.2-1.6.0
-   TrashSlot_1.12.1-8.4.6
-   twilightforest-1.12.2-3.6.345-universal
-   ValkyrienWarfareRevamped-1.12.2-v0.9_alpha-full (1)
-   VanillaFix-1.0.1-6
-   VTweaks-1.12.2-1.4.12b
-   Waystones_1.12.2-4.0.42
-   wizardry-0.8.5
-
