### ISSUE TITLE
Endless Chum

### ISSUE THREAD

**Issue by courseofra** [An-Sar/PrimalCore#193]
Hi dear Team,

there is a receipe making possible to produce 3 Chum from 1 Chum. But I don't actually know if it is from a mod which unifies receipes (Like UniDict for ores) or from PrimalCore itself. So I give it to you to check.

Minecraft 1.12.2
Forge 14.23.3.2675
PrimalCore-1.12.2-0.6.53
Chum-Id: 9432

Please see attached screens. If other logs are neccesary, let me know.

Best regards

Christian

![2018-05-08_12 00 41](https://user-images.githubusercontent.com/38578716/39751234-d384d984-52b7-11e8-9556-d00d992fce3e.png)
![2018-05-08_11 49 49](https://user-images.githubusercontent.com/38578716/39751235-d3bd9774-52b7-11e8-9d8b-79a8b93672a7.png)

**Comment by An-Sar** [comment]
this has been fixed and will be in the next release

**Comment by courseofra** [comment]
Thanks a lot.
