### ISSUE TITLE
Issue with Cauldron and CarryOn

### ISSUE THREAD

**Issue by Tschipp** [An-Sar/PrimalCore#194]
This is a follow up to CarryOn#88. I gave you some advice in https://github.com/An-Sar/PrimalCore/issues/158 on how to fix the issue, and that also did fix the issue. However, I have since made some changes to my code (I no longer set the TileEntity to null, but I clear every IItemHandler that exists on it.)

Sadly this caused your cauldron to again not be pickup-able. The problem lies here:
```
if (te.hasCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null))
{
	IItemHandler itemHandler = te.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null);
	for (int i = 0; i < itemHandler.getSlots(); i++)
	{
		itemHandler.extractItem(i, 64, false);
	}
}
```
This is the code that I call to clear the itemHandler. The cauldron returns true for hasCapability, but then returns null when I try to get it, which it should never. I'm not sure how your code looks like, but you should make sure that you have the same condition for returning the Capability, as you have for returning if the Capability exists.
I thought I would just give you a heads up, as issues like these can arise when connecting pipes to the block, for example. I've had this issue myself when working on the Animania trough.

Edit: I have once again made some changes with my code, because I was having other issues. It now works with your cauldron. You should probably still check out that capability issue though.

**Comment by An-Sar** [comment]
the null facing value wasn't being handled properly, i am testing a fix
