### ISSUE TITLE
[random suggestion] native compat with bwm

### ISSUE THREAD

**Issue by meelock** [An-Sar/PrimalCore#2]
It would be so awesome if primal core and its dependants had natural support for better with mods, (ie adding iron as a progression point that you need a crucible to turn slag iron into iron.) imagine the possibilities. :P

**Comment by meelock** [comment]
like [this ](http://pastebin.com/9WcusHKW)(I'm working on a modpack)

**Comment by meelock** [comment]
excuse my derpy syntax.

**Comment by meelock** [comment]
updated: [thing](http://pastebin.com/dV6tGKvm)

**Comment by An-Sar** [comment]
I'm all for compatibility and from what I have seen BWB is quite good. I would have to look into what native support would entail, but generally I like the idea yeah.

**Comment by meelock** [comment]
BWB? do you mean better with mods? or something different?

**Comment by An-Sar** [comment]
yeah I meant BWM.

**Comment by An-Sar** [comment]
also interested to see how the mod pack is going.

**Comment by meelock** [comment]
[here ](https://minecraft.curseforge.com/projects/darkmill)is a link to my pack if you want to check it out.

**Comment by An-Sar** [comment]
I added compatibility between the BWM knife and the Primal workblades. Additional feedback would be useful. thanks

**Comment by An-Sar** [comment]
Are there any specific suggestions for things that could be improved beyond what has already been added?

Thank You

**Comment by meelock** [comment]
I was more thinking of mill compatibility/extra features for cross-mod compat or even add turntable compatibility, by way of special recipes when better with mods is installed.

thanks!

**Comment by meelock** [comment]
bump
