### ISSUE TITLE
Sharpened bone, why?

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#20]
So I'm running around with sharpened bones to try to see how  they work as weapons.
This is honestly just painful.
Suggestions:
1. A slowness /poison effect from the rotten marrow would make this a great "run away" weapon. 
2. Sharpen bones on stone like chipping flint, if you want it craftable, make it use a flint which isn't consumed.
3. faster attack speed. Frankly it needs either this or damage and this is a little  more fitting.

**Comment by kitsushadow** [comment]
I personally feel they need two stages. 

Sharpen Bone 1: Sharpen on stone no flint
Sharpened Bone 2: Sharpen on stone then same crafting as current sharp bone but +1 damage. 

Something like that would give it more entry level use while still having some use a little later.

**Comment by An-Sar** [comment]
Actually I just checked the material stats and bone was accidentally set to 0 for damage. I'm changing it for further testing in the next release.

The knapping recipe is a good idea I think.

There were sharp bones in MagnumOpus that could be laced with potion effects, I was planning on brining those back.

**Comment by An-Sar** [comment]
I kind of like the idea of being able to get bone shards from knapping that could be used for other things..

**Comment by kitsushadow** [comment]
Like arrow heads

**Comment by An-Sar** [comment]
most of this has been addressed
