### ISSUE TITLE
Not getting planks

### ISSUE THREAD

**Issue by Jedibobawesomeness** [An-Sar/PrimalCore#203]
I have an issue, every time I put a log into my crafting, I don't get planks from it, so I can't make progress.

**Comment by Jedibobawesomeness** [comment]
Never mind, I found out how to get planks.

**Comment by An-Sar** [comment]
let me know if you run into any further questions, especially if its something lacking from the wiki, i am sure there are areas i still need to fill in.

**Comment by Jedibobawesomeness** [comment]
Ok!
