### ISSUE TITLE
[Suggestion] Items from FIRE_SOURCE_ITEMS can light Log Stacks

### ISSUE THREAD

**Issue by Charnuz** [An-Sar/PrimalCore#207]
Allow items in the FIRE_SOURCE_ITEMS config to light Log Stacks

**Comment by Adarcer** [comment]
They already can O.o

**Comment by Charnuz** [comment]
For some reason trying to light them with a lit fibre torch from primal tech isnt working. Not sure what is happening...

**Comment by An-Sar** [comment]
there are issues with certain items/blocks, not exactly sure what's causing it

**Comment by An-Sar** [comment]
this has been fixed (0.6.68)
