### ISSUE TITLE
Throwing Stones

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#21]
Stones are wierd  as  a  throwing weapon. 
They don't deal appreciable damage, maybe add a sling to increase windup but increase speed and  damage?

**Comment by An-Sar** [comment]
The other day I was thinking about tweaking the gravity that gets applied, currently you're right its pretty pointless to throw a rock.

**Comment by An-Sar** [comment]
The sling with a bag to hold rocks could be pretty good.

**Comment by kitsushadow** [comment]
It would be a good entry projectile instead of bow and arrow

**Comment by An-Sar** [comment]
i believe this has more or less been satisfied, i am still planning to implement a "rock sack" item and a sling, but for purposes of throwing rocks on their own i am going to close this issue
