### ISSUE TITLE
[Bug] Exoria modpack- flaked flint bug

### ISSUE THREAD

**Issue by StarsPath** [An-Sar/PrimalCore#210]
I was playing on the Exoria modpack and VanillaFix caught a bug for PrimalCore.
Bug: When left clicking the stone/basalt with flint, it consumes the flint, but does not give flaked flint at all.
Recreate: Try spamming the stone/basalt with flint.
Here is a crash file.

[crash-2018-06-05_13.29.24-server.txt](https://github.com/An-Sar/PrimalCore/files/2073373/crash-2018-06-05_13.29.24-server.txt)

**Comment by An-Sar** [comment]
Exoria seems to be several versions behind (0.6.51)
i believe this has been fixed for awhile. At the time of this comment current version is 0.6.56

**Comment by An-Sar** [comment]
this issue can be revisited if/when Exoria updates
