### ISSUE TITLE
Barrel capacity tooltip doesn't fit with the real capacity of the barrel

### ISSUE THREAD

**Issue by Fireztonez** [An-Sar/PrimalCore#212]
The Wooden Barrel can contain 8000mb of fluid, but the tooltip said 4000. When the barrel is full is mark 8000/4000mb...
![image](https://user-images.githubusercontent.com/19277301/41614427-76f61ef0-73c6-11e8-96eb-0f68a04434a1.png)

Version:
Minecraft 1.12.2
Forge 14.23.4.2708
PrimalCore 0.6.56

**Comment by An-Sar** [comment]
barrel was accidentally referencing the fluid capacity of the cauldron, fixed in dev (0.6.57)

**Comment by Fireztonez** [comment]
Oki, perfect 👍
