### ISSUE TITLE
Charcoal Stack Localization Errors (All in-world charcoal stacks are Poor Grade)

### ISSUE THREAD

**Issue by Vyraal1** [An-Sar/PrimalCore#213]
Hey An Sar,

It seems like there is a localization issue with charcoal stacks after they have formed in world. All of them seem to be labeled as 'Poor Grade' Charcoal stacks as shown below, whereas the meta and the actual charcoal quality they produce is different.

![image](https://user-images.githubusercontent.com/26587049/41803914-7cf249a8-765c-11e8-9349-b53a37262bb8.png)

**Comment by An-Sar** [comment]
fixed in dev (0.6.58)
