### ISSUE TITLE
Duping items with worktable

### ISSUE THREAD

**Issue by scigeotech** [An-Sar/PrimalCore#214]
I was using a spruce worktable and accidentally duped a used flint handsaw.
Steps:
Craft a spruce worktable
Put used flint handsaw in worktable
Break the worktable with flint handsaw still inside (oops, my bad)
Worktable drops 2 flint handsaws, and the worktable itself.

**Comment by An-Sar** [comment]
just to clarify was this with the worktable shelf? and was the saw in a shelf slot or in the crafting grid?

Also which version are you using?

**Comment by scigeotech** [comment]
Latest version. It was in a shelf slot.

**Comment by An-Sar** [comment]
cool thank you for the report, the drop code was accidentally accessing the handler for the shelf slots twice rather than the crafting slots.

**Comment by An-Sar** [comment]
PrimalCore-1.12.2-0.6.61 has been pushed to curse
