### ISSUE TITLE
Bitumen and Boiling Bitumen can't be placed in the Nether

### ISSUE THREAD

**Issue by shadinx2** [An-Sar/PrimalCore#215]
Boiling Bitumen spawns naturally in the nether, but when I try to place it down it acts like water and just vanishes. I am using the latest version in minecraft 1.12.  My guess is that one of the following mods is conflicting somehow: NetherEx, Biomes O' Plenty or Tinkers Construct.

Full mod list: Animania, Astral Sorcery, Avaritia, Baubles, BetterFps, Biomes O' Plenty, Botania, CodeChickenLib, Coroutil, Craft studio api, Dynamic trees(with addons for thaumcraft and biomes o' plenty), electroblob's wizardry, energy convertors, farseek api, foamfix, forgelin, guide api, hwyla, ice and fire, immersive engineering, industrialcraft, infernal mobs, jei, llibrary, Mantle, Mekanism, NetherEx, primal core, roughmobs2, scling health, serene seasons, silentlib, streams, Tinkers Construct, texfix, thaumcraft, torohealth, toughasnails, undergroundbiomeconstructs, weather2, xaerosminimap, zombieawareness.

**Comment by An-Sar** [comment]
This is a legit bug, now fixed in dev. there are some special mechanics that effect actively flowing bitumen and other fluids in the nether. Feedback is very welcome once the changes are released (0.6.62)

**Comment by shadinx2** [comment]
Tested it. Liquids can now be placed int the nether. I might have found a new bug. When flowing blocks decay after removing the source block, they leave behind fire. Also great work and thanks for fixing the original bug.

**Comment by An-Sar** [comment]
this is actually an intended feature, flowing bitumen actively catches on fire and is consumed in the process. Mechanic should still allow for safe construction of cobble-style block gens if you only allow vertical flow. Let me know your overall impression.
