### ISSUE TITLE
Iron Cauldron JEI lookup doesn't find usages

### ISSUE THREAD

**Issue by codewarrior0** [An-Sar/PrimalCore#217]
For example, looking up the recipe for Hard Boiled Egg will show the Iron Cauldron recipe for creating it, but looking up the *usages* for Egg will *not* show the Cauldron recipe for hard-boiling it.

This seems to be because `CauldronRecipeWrapper.getIngredients()` is missing a line like `ingredients.setInputs(ItemStack.class, this.item_input);`

PrimalCore-1.12.2-0.6.61.jar

**Comment by An-Sar** [comment]
you were correct, the ItemStack input slots where missing from the JEI wrapper.
fixed and seems to be working (0.6.64)
