### ISSUE TITLE
Duplicate Language key with a lot of mods

### ISSUE THREAD

**Issue by TartaricAcid** [An-Sar/PrimalCore#219]
Here is a list, have 4 duplicate key with 3 mods and vanilla:

`tile.cauldron.name`
- Minecraft: `Cauldron`
- Primal: `Iron Cauldron`

`item.bark_jungle.name`
- Primal: `Jungle Wood Bark` 
- Roots: `Jungle Bark`

`item.silver_dust.name`
- Primal: `Silver Dust`
- Tiny Progressions: `LightGray Glowstone Dust`

`item.void_seed.name`
- Primal: `Equisetum Ineris Spore`
- Thaumcraft: `Void Seed`

**Comment by An-Sar** [comment]
i have gone through and added the mod prefix to all the language keys, i think this should resolve any possible conflicts (0.6.64)
