### ISSUE TITLE
Dupe bug with work blade.

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#22]
Work blade repairing where you put two in the crafting grid dupes them

**Comment by An-Sar** [comment]
This has been fixed and will be released for both branches with upcoming updates, 0.2.8 and 0.3.1

Looking at the tool crafting handler makes me realize it needs to be entirely reworked, but this fix should plug the hole for now.

**Comment by An-Sar** [comment]
This should now be fixed in the current 1.10.2 release

**Comment by An-Sar** [comment]
there is still some bits of this lingering around..

**Comment by An-Sar** [comment]
Crating tool code has been rewritten and this should now be fixed.
