### ISSUE TITLE
[Suggestion][1.12.2] Tone down the BOOM with paraffin barrels please?

### ISSUE THREAD

**Issue by 63502** [An-Sar/PrimalCore#220]
I love big explosions as much as the next guy, but you know something is wrong when a pile of cheap oak barrels and about 76 buckets of liquid of wax explode with destructive power comparable to a draconic reactor meltdown.

Completely ignoring game balance, I would suggest toning down the explosion strength just for the sake of stopping the world killing lag that happens with multiple explosions of power 10 and up.

I would have included a picture of the crater, but I couldn't get one due to my games ability to run my test world exploding along with the unfortunate village I planted the barrels in.

**Comment by An-Sar** [comment]
i will look at adding a modifier to the config so the volume calculation on the barrels can be scaled

**Comment by An-Sar** [comment]
adding new configs (0.6.64)

PARAFFIN_FLUID_EXPLOSION_MODIFIER
PARAFFIN_BARREL_EXPLOSION_MODIFIER
