### ISSUE TITLE
[Suggestion] Add a entity blacklist to prevent pelt drops

### ISSUE THREAD

**Issue by LukeSkywaIker** [An-Sar/PrimalCore#223]
I´m creating a modpack with totemic and its not cool that the buffalo drops buffalo and a cow hide.  
Maybe u can add a blacklist for entities that shoudnt be affected by the primal extra drops.

Thank you in advance!

**Comment by An-Sar** [comment]
i am going to rewrite the drop code to use proper loot tables, in the mean time i've added specific support for not dropping cow parts from totemic buffalo
