### ISSUE TITLE
Furnace Recipe cannot be changed

### ISSUE THREAD

**Issue by CritFlaw** [An-Sar/PrimalCore#224]
When changing the furnace recipe with craft tweaker (doing a remove, and then a hide), the furnace recipe still shows as 8 stacks of 16 cobblestone blocks in JEI. In a crafting table, the adjusted craft tweaker recipe works, and displays an output, but the JEI entry still shows the primal core default. Removing the mod fixes this, so it's definitely a primal core related bug.

**Comment by An-Sar** [comment]
Which furnace recipe?

Also can you include the CT lines?

**Comment by An-Sar** [comment]
Can you include your CT lines?

**Comment by tedmihu** [comment]
`recipes.remove(<minecraft:furnace>);
//mods.jei.JEI.removeAndHide(<minecraft:furnace>.withTag({Type: "minecraft:furnace"}));
recipes.addShaped(<minecraft:furnace>, [
[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>], 
[<ore:cobblestone>, null, <ore:cobblestone>], 
[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>]
]);
//mods.jei.JEI.addItem(<minecraft:furnace>.withTag({display:{Name: "minecraft:furnace",}}));*/

recipes.addShaped(<minecraft:grass>, [
[<minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>], 
[<minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>], 
[<minecraft:dirt>, <minecraft:dirt>, <minecraft:dirt>]
]);`

Commented out lines was me tryng an alternative where I hide it from JEI and add it back, but that doesn't work.

This seems to be a visual bug but it only happens with primal core. Tested with a pack that's just JEI, PrimalCore and CraftTweaker, still shows up. Also, when adding cobblestone in the center slot, it also shows up as 16. Happens to other recipes that involve cobblestone as well.

**Comment by CritFlaw** [comment]
ETA on when that'll be in a release version?

**Comment by An-Sar** [comment]
very soon as it's a pretty visible bug
