### ISSUE TITLE
mud spawns are fixed height

### ISSUE THREAD

**Issue by Efimero** [An-Sar/PrimalCore#227]
what I expected: mud and bog iron (and bitumen and satetsu?) spawn at the surface on wet biomes and replace dirt and grass, wherever that is

what happens: mud spawns at a fixed height in the world and can get placed inside the rock layers, no matter where the actual surface is

in a customized world where the surface is set to be 40 blocks higher, you can't see any mud even if it's a constant swampland biome

spawning logic should look for the first dirt/grass block from the sky instead of using a fixed height, otherwise it can spawn buried in the above case or not at all on a world with surface and sea level lower than usual

**Comment by An-Sar** [comment]
what are you using for the custom surface height? i can setup a test world.

It should work as is, if i just adjust the Y range on certain features.

**Comment by Efimero** [comment]
a customized world with these parameters changed
seaLevel:100.0
riverSize:6
biomeDepthOffset:2.5
upperLimitScale:2516.0
biomeDepthWeight:1.5

biomeDepthOffset is the one that raises the land up, seaLevel sets the water level, which can be independent

**Comment by An-Sar** [comment]
so just the build in customized world type, i've never actually messed with those settings. i will do some testing.

**Comment by An-Sar** [comment]
as a quick fix i have added configs for min/max height values. down the road i want to completely pull the worldgen configs out into json, but that's a larger project.

GEN_MUD_MIN_MAX, GEN_CLAY_MIN_MAX, GEN_SATETSU_MIN_MAX
