### ISSUE TITLE
Create a fire pit block for entry level fire

### ISSUE THREAD

**Issue by kitsushadow** [An-Sar/PrimalCore#23]
1. Determine optimal means for producing the block
  - Right click grated gravel with a shovel.
  - Create a new gravel well block
  - Gravel well block has a few states 
  - At the correct depth its capable of receiving dry tinder 

2. Optimal means of lighting the block
  - Dry tinder is added to the grated gravel via right click
  - The tinder can be lit through the use of the fire-bow, torch, or flint-steel 
  - The lit tinder only stays lit for a few seconds
  - A player must:
    1. [ ] throw sticks into the pit
    2. [ ] Add sticks to the pit inventory through a right click

3. The fire-pit only accepts sticks? or should it accept 1/4 split logs?
  - Probably best to only accept sticks for now until a higher tech version is made.

4. Optimal means of the fire going out and relighting the fire
  - When the sticks are consumed from the inventory a new item is created that can't be removed from the inventory called hot coals which if sticks are added to it can rebuild the fire.
  - If the hot coals time limit ends an ash item is left instead which must be cleaned from the inventory before tinder can be added.

**Comment by kitsushadow** [comment]
@An-Sar let me know what u think of these mechanics

**Comment by kitsushadow** [comment]
Current progress:
- [x] Create the Firepit model *Model json is checked in cubic as firepit2*
- [x] Create the Firepit texture: *Using grated_gravel_top.png texture*
- Is this block sided?
  - [ ] Yes
  - [ ] No
- [ ] Add inventory slot for tinder and sticks
- [ ]

**Comment by XvSkItZvX** [comment]
I've recently taken an interest in this mod, and have been testing it as part of a mod-pack I'm privately working on. I've been using it in conjunction with the "Tough as Nails" mod which provides a "Campfire" Block. 

They introduce an interesting mechanic to lighting it, not too dissimilar from your "Firebow" mechanic, by using sticks with right click. 

I take the time to mention this here in case there is any interest for you and the devs of "TaN" would like to work on compatibility. I'll have a list of other issues suggestions I noticed in another thread if I don't find the individual issues in a thread on their own already.

**Comment by kitsushadow** [comment]
@XvSkItZvX Thanks for ur interest in Primal. If you had a specific list of compatibility issues that stick out feel free to create issues for each of them and we can address them accordingly. On the topic of working with TaN devs what method of communication do they prefer? irc, discord, git?

They are ofc invited to use our discord as its intended purpose was for collaboration between devs and players.

Thanks for your interest and hope to work with you more!

**Comment by An-Sar** [comment]
It would be nice to have that level of compatibility. Would need to take a closer look at TaN code base and if they have anything relevant in an API or not...

**Comment by An-Sar** [comment]
Even better would be to register our blocks as heat sources, etc

**Comment by An-Sar** [comment]
this was merged from kitsu's branch
