### ISSUE TITLE
Error with Monk Mod

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#233]
The Monk Mod creates a unique way of being able to mine blocks with your bare hands, when I last tried the mod with PrimalCore all the mod does is make blocks take longer to break and since your hands are technically functioning as tools you do not take damage from breaking blocks like wood or stone, however you still do not receive an output and mining blocks takes longer

**Comment by An-Sar** [comment]
this should be resolved, i've added a check that skips the logic for harvesting if monk is loaded and the players hand is empty. 

we may need to make some further adjustments so please update here once the next release is out

(0.6.69)

**Comment by UnlimatedStone9** [comment]
ok then, thanks An-Sar!

**Comment by UnlimatedStone9** [comment]
is there any estimated time to release the test version?

**Comment by An-Sar** [comment]
np. release should be dropping within the next 24 hrs
