### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException Crash w/ AutoPlant & Bamboozled

### ISSUE THREAD

**Issue by WenXin20** [An-Sar/PrimalCore#235]
Forge v14.23.4.2747-1.12.2
PrimalCore v0.6.69
I got this crash while playing in the world. I was in a[ candy world ](https://minecraft.curseforge.com/projects/candy-world)mod biome, if that helps.
[Crash Report](https://gist.github.com/WenXin20/ef6e7ae22075e24111281f6a20efd5ff)
[Latest Log](https://gist.github.com/WenXin20/e40ab92847f1ebfaf7126755352de97b)

**Comment by An-Sar** [comment]
i couldn't immediately reproduce this crash.

try adding bamboozled:bamboo to the config PLANT_AUTO_MAGIC_BLACKLIST, under the plants section.

**Comment by WenXin20** [comment]
I removed it from the blacklist tried it to see if the bamboozled:bamboo would auto plant, and it doesn't, it just despawns, so I don't think that was the problem.

**Comment by WenXin20** [comment]
After a little more investigating, I got the crash to happen again after adding the mod [Autoplant](https://minecraft.curseforge.com/projects/autoplant) back into the test pack. I got it to happen after throwing the bamboozled:bamboo on the grass block. So it looks like the a combination of Bamboozled, Autoplant, and PrimalCore causes this. Before this crash, I was unaware that PrimalCore had an auto plant feature. If I remove PrimalCore, the crash does not happen. The Autoplant mod will plant the bamboo, but PrimalCore doesn't.
[Crash Report](https://paste.dimdev.org/rebepihucu.mccrash)

**Comment by An-Sar** [comment]
Yeah i will add auto-plant to my dev environment and see if i can reproduce the issue. 
Thank you for the debugging

**Comment by WenXin20** [comment]
Thanks, and it was no problem!

**Comment by An-Sar** [comment]
i still cant reproduce the crash,  [but i have a dev build](https://www.dropbox.com/s/336mfep6xl13iyj/PrimalCore-1.12.2-0.6.69.1.jar?dl=0)

**Comment by WenXin20** [comment]
Yes, the dev build fixed it for me, so did v0.6.70 of PrimalCore. Thanks!
