### ISSUE TITLE
Crash w/ the Plated Mod

### ISSUE THREAD

**Issue by WenXin20** [An-Sar/PrimalCore#236]
Forge v14.23.4.2747-1.12.2
PrimalCore v0.6.68
[Plated](https://minecraft.curseforge.com/projects/plated) v0.1.0
I received the following crash after creating a new world.
[Crash Report](https://gist.github.com/WenXin20/580797ddd97f3ef58b10ee0520038076)
It was also reported to SleeplessDevelopment/Plated#1.

**Comment by An-Sar** [comment]
fixed (0.6.70)
