### ISSUE TITLE
Primal Version 0.6.69 Crashing

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#237]
Upon updating the mods in my Modpack I noticed the game started to crash at the first initialisation phase, I suspected this to be caused by Primal's latest fix for compatibility with the Monk Mod and its new release, after downgrading the version number back to 0.0.68 the game loaded perfectly again, here is the crash report, the logs and the forge version number.

Forge Version: 14.23.4.2749
Crash Report: https://pastebin.com/Re7inpji
Latest Logs: https://pastebin.com/xDHsP3nx

Thanks!                     -UnlimatedStone9

**Comment by An-Sar** [comment]
looks like its due to ENABLE_STAIRS being disabled, some of the work blade recipes craft stairs in-world. i just need to add the config check to the recipe additions

**Comment by UnlimatedStone9** [comment]
so enabling the stairs config should resolve this for now?

**Comment by An-Sar** [comment]
yes i think so. Please try that and let me know, just to make sure.

**Comment by UnlimatedStone9** [comment]
ok will do, it'll be a minute, the packs large so it takes a fair amount of time

**Comment by UnlimatedStone9** [comment]
The game loaded correctly as desired

**Comment by UnlimatedStone9** [comment]
The game reported missing gallagher recipes for ancient ice and obsidian when loading a world

**Comment by An-Sar** [comment]
i think that should be ok, check JEI to see if a recipe for ancient ice shows up? a bunch of recipe stuff changed in the last version.

i have added a config check to the blade recipes so with 0.6.70 you should be able to disable safely

**Comment by UnlimatedStone9** [comment]
I'll check JEI, got stuck at building terrain when loading a new world to see if it was specific to that  one world itself
