### ISSUE TITLE
Bug with Cauldron crafttweaker script?

### ISSUE THREAD

**Issue by wormzjl** [An-Sar/PrimalCore#246]
I've been trying to add custom recipes for the cauldron but encountered some issues.
Normally the syntax should be

`addRecipe(String recipe_name, int cook_time, ILiquidStack fluid_input, ILiquidStack fluid_output, @NotNull IIngredient[] item_input, @NotNull IItemStack[] item_output, @Optional IItemStack catalyst)`

or

`addRecipe(String recipe_name, int cook_time, ILiquidStack fluid_input, IIngredient[] item_input, IItemStack[] item_output, @Optional IItemStack catalyst)`

With my script as follows

```
val item = <contenttweaker:scrap1>;
mods.primal.Cauldron.addRecipe("test", 6, <liquid:water>, item, <contenttweaker:scrapmetal4>);

```
 I got the following error:

```
[SERVER_STARTED][SERVER][ERROR] primal.zs:7 > 2 methods available but none matches the parameters (string, int, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IItemStack, ZenTypeNative: crafttweaker.item.IItemStack)
This is usually an error in your script, not in the mod
addRecipe(string, int, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.liquid.ILiquidStack, NotNull ZenTypeNative: crafttweaker.item.IIngredient[], NotNull ZenTypeNative: null.null[], Optional ZenTypeNative: crafttweaker.item.IItemStack)
addRecipe(string, int, ZenTypeNative: crafttweaker.liquid.ILiquidStack, ZenTypeNative: crafttweaker.item.IIngredient[], ZenTypeNative: null.null[], Optional ZenTypeNative: crafttweaker.item.IItemStack)
```

Seeing `ZenTypeNative: null.null[]` as requirement, I think something might be broken...
I'm using PrimalCore-1.12.2-0.6.78 and CraftTweaker2-1.12-4.1.9

**Comment by An-Sar** [comment]
try this

```
val item = <contenttweaker:scrap1>;
mods.primal.Cauldron.addRecipe("test", 6, <liquid:water> * 250, [item], [< contenttweaker:scrapmetal4 >]);
```

**Comment by wormzjl** [comment]
It does work now, thanks!
However I'd recommend updating the wiki page since the parameters there are not correct
https://github.com/An-Sar/PrimalCore/wiki/CraftTweaker:-Cauldron
