### ISSUE TITLE
Vanilla torch render is broken in hand and inventory

### ISSUE THREAD

**Issue by darthvader45** [An-Sar/PrimalCore#249]
Seems as soon as I updated to 0.6.80, the vanilla torch render in my hand and in my inventory (I'm guessing this means when it is dropped as well, will test) is nothing but a big pink box.  Went back to 0.6.78 and its fine.  I'm guessing something changed in PrimalCore that broke something with the lit torch.

Edit: Also, when shift-clicking to pick torches up, they disappear instead of going into my inventory.

![2018-09-09_10 17 00](https://user-images.githubusercontent.com/2816420/45265496-a201a900-b419-11e8-9f29-7df614047ff4.png)
![2018-09-09_10 16 49](https://user-images.githubusercontent.com/2816420/45265497-a201a900-b419-11e8-8c2d-ab01b5826c46.png)
![2018-09-09_10 16 55](https://user-images.githubusercontent.com/2816420/45265498-a201a900-b419-11e8-9481-591e206be506.png)

**Comment by An-Sar** [comment]
are these pre-existing primal lit torches or vanilla torches?

**Comment by An-Sar** [comment]
i still can't recreate the problem, what happens if you just run Primal by itself?

**Comment by darthvader45** [comment]
Testing that now.  Can you not recreate it in dev, or not even outside dev?  Btw, Forge updated, might affect testing.

**Comment by An-Sar** [comment]
both dev and a test pack constructed off the list you provided. i've been using the most recent forge version (14.23.4.2760) in both cases.

**Comment by darthvader45** [comment]
Huh, just PrimalCore and its fine.  I'll send you a zip with my configs.  Maybe a config messed things up.

**Comment by darthvader45** [comment]
Weird, I just updated Forge on that set of mods I provided, and I straight up crashed.  No idea what happened.

**Comment by darthvader45** [comment]
Okay, turns out it was Forge.  Dropped Voxelmap in favor of Journeymap so I could reliably get rid of Liteloader and update Forge, and the issue cleared itself out.  Should remind people to update Forge, and when they do, remove Liteloader as it has a conflict with 14.23.4.2760 Forge.

**Comment by An-Sar** [comment]
i got a crash with NEI when i was setting the mods up

**Comment by darthvader45** [comment]
Did you have JEI as well?  NEI now requires JEI, as it is now a JEI plugin.  I made sure of that, and had no problems.

**Comment by An-Sar** [comment]
i think i had, unless curse didn't pull JEI down. i didn't look too closely at the crash just removed NEI.

what version of forge were you on previously?

**Comment by darthvader45** [comment]
14.23.4.2759.  Also, it seems something broke regarding torches and Optifine's dynamic lighting.  Might have to update it.
