### ISSUE TITLE
No possibily to create Whittled Fire Sticks with PrimalTech 0.3.3

### ISSUE THREAD

**Issue by Prelart** [An-Sar/PrimalCore#256]
There is no possibily to create a Whittled Fire Sticks (#8165) with stick when updating the mod PrimalCore 1.12.2-0.6-57 and Primal Tech 0.3.3.

(On Sevtech sever)

**Comment by An-Sar** [comment]
this is most likely an issue that needs to be handled by sevtech.

what version are you trying to update to?

**Comment by Prelart** [comment]
We own a server and we have see than the primalcore wemas causing lag on the server console, we update the old verdion to the new. The lag is way lesser, but we have crafting issue.

Hope it will help a bit!

**Comment by An-Sar** [comment]
i cannot reproduce this with just the two primal mods installed, crafting works as expected. this means the problem is likely within the sevtech scripts/game stages
