### ISSUE TITLE
Game Crash caused by DryingRack (?)

### ISSUE THREAD

**Issue by Fireztonez** [An-Sar/PrimalCore#257]
Hello An Sar,
I just ggot a Game crash on my game, just after finsih placing Salted Hide in drying rack when I look the Crash log, I see multiples times java error like; `java.lang.ClassCastException: nmd.primal.core.common.tiles.machines.TileDryingRack cannot be cast to nmd.primal.core.common.tiles.AbstractTileTank`

So I think the problem is with the drying rack but i'M not totally sure...

Version: 
PrimalCore: 0.6.82
Forge: 14.23.4.2760
Java 8 update 1.8.0_181

Crashlog:
https://gist.github.com/Fireztonez/ae166cbfb617a63e829bb8cb36e12530

**Comment by An-Sar** [comment]
fixed (0.6.83)

**Comment by Fireztonez** [comment]
thank's I think you can claused the issue, I have no more problem with the Drying rack ;)

Fireztonez
