### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MechWarrior99** [An-Sar/PrimalCore#26]
Not sure quite what is causing this. But it crashes, so here. 

PrimalCore: 0.2.9
Forge: 12.18.3.2185
Crash Report: [Here](http://pastebin.com/N5vuah3N)

Sorry I can't help more than this.

**Comment by MechWarrior99** [comment]
I updated primalcore to 0.2.10 and it was still crashing. But after I disabled the wolf that PrimalCore adds, I stopped getting crashes. Hope this helps. If there is anything else I can do to help please let me know.

**Comment by An-Sar** [comment]
Thank you for the follow up.

I saw it was related to the wolf targeting AI from the original crash report. I was going to ask if it was regularly reproducible so I guess this answers my question. I will try to recreate this in my environment.

**Comment by MechWarrior99** [comment]
No problem. I am not quite sure how to reproduce the crash, as it seems to happen randomly.

**Comment by An-Sar** [comment]
are you playing on a server or single?

**Comment by MechWarrior99** [comment]
Singleplayer

**Comment by An-Sar** [comment]
I am still investigating this, so most likely will still be a problem in 0.2.11..

**Comment by An-Sar** [comment]
Can you confirm if this crash is still taking place with version 0.2.21 or later?

Thank you

**Comment by An-Sar** [comment]
Im going to assume this is fixed
