### ISSUE TITLE
PIck-up non-harvestable block with Carry-On give damage and damage the armor

### ISSUE THREAD

**Issue by Fireztonez** [An-Sar/PrimalCore#260]
Hello,
I already talk to you about that on discord, but here the Issue.

When I pickup thing's who can not be harvest with the hand, the player get damage, like when he try to break the block, and it damage at the same time the armor...

I think you should fix the thing to not damage armor when you break block, and possibly look for make sure the player have broke the block and not just pick-up with Carry-On... In minecraft there have an event for block breaking if I don't mistaking... I don't think carry-on call that event, but I'm not a Java Programmers, so I can't really confirm that...

If you can fix that, it would be really nice!! I always use carry-on, in my modpack it is really useful...

Fireztonez

**Comment by An-Sar** [comment]
armor damage has been fixed. (0.6.91)

carry-on compatibility appears to be a bit more complex and will take some deeper testing. it's not clear to me that there is a trivial fix for this.

**Comment by An-Sar** [comment]
officially the fix for taking damage with carry-on is to not use the hard block feature. 

@Fireztonez i know we talked about this, just updating the issue in case anyone else comes looking for information.
