### ISSUE TITLE
[1.12.2] Forge Crashes While Loading

### ISSUE THREAD

**Issue by PulseBeat02** [An-Sar/PrimalCore#265]
The full report is here: https://github.com/SteveKunG/MorePlanets/issues/49
Please click on the link above to see the problem.

The main Issue Here: 
There seems to be a mod conflict.

**Comment by An-Sar** [comment]
try adding **_moreplanets:cheese_food_** to the config Machines.HIBACHI_FURNACE_BLACKLIST

**Comment by An-Sar** [comment]
this has now been fixed without the use of the blacklist (0.6.93)

**Comment by PulseBeat02** [comment]
So I have to remove item blacklist for this to work?

**Comment by An-Sar** [comment]
once the next version is released (0.6.93) it should just work as it, in the current version adding the item to the blacklist should avoid the crash.

93 should release later today

**Comment by PulseBeat02** [comment]
Ok
