### ISSUE TITLE
Primal Core Crashed the Game for The Player

### ISSUE THREAD

**Issue by Jasondia16** [An-Sar/PrimalCore#268]
https://github.com/Jasondia16/AlIinOne/issues/3
Link to the conversation it includes the crash report 

Thanks And Have a Nice Day

**Comment by An-Sar** [comment]
are you able to reliably reproduce this crash?

also can you put your Betweenlands config up on pastebin or something similar?

**Comment by An-Sar** [comment]
i believe this has been resolved, closing for now
