### ISSUE TITLE
Crash with last recomended Forge

### ISSUE THREAD

**Issue by Bulldog83** [An-Sar/PrimalCore#269]
Game crashes with last recomended Forge 14.23.5.2768

Crash report: https://gist.github.com/Bulldog83/1b96dda28423d72f7e34381b75ab92fa

Minecraft: 1.12.2
Forge: 14.23.5.2768
PrimalCore: 0.6.94

**Comment by An-Sar** [comment]
there is a [dev build available](https://www.dropbox.com/s/h2c84db4tglwcvo/PrimalCore-1.12.2-0.6.94.1.jar) with a possible fix, if you are able to test please let me know how it turns out

**Comment by An-Sar** [comment]
This issue is related to the following
https://github.com/An-Sar/PrimalCore/issues/268
https://github.com/Jasondia16/AlIinOne/issues/3

**Comment by Bulldog83** [comment]
Yes, with this fix game starts.  Now I need to remove the crashes from other mods ... Thanks. :)

**Comment by An-Sar** [comment]
ok, cool. however i just realized this is likely related to changes in the forge universal bucket. i will update the dev build again with a more complete fix

**Comment by An-Sar** [comment]
can you test the primal core clay bucket and see if it is working on that dev build with the new forge?

**Comment by Bulldog83** [comment]
Sorry, I still can not run the modpack because of the crashes from other mods. I want to wait a couple of days before fixes releasing.

**Comment by An-Sar** [comment]
no worries, it seems like a lot of things may have been effected. i tried to test my workspace with the RB of forge and the thaumcraft api was causing a crash...

**Comment by An-Sar** [comment]
maybe safer to go back to 14.23.4.2765 for the moment
