### ISSUE TITLE
Register saws in the ore dictionary.

### ISSUE THREAD

**Issue by MechWarrior99** [An-Sar/PrimalCore#27]
Could you make it so all the saws added by PrimalCore are registered in the ore dictionary. Then edit the recipes that use saws to use the ore dictionary instead of individual item? The way it is right now when look up recipes is quite messy imo.

**Comment by An-Sar** [comment]
Hm, I can look at this yeah. I'm not entirely sure it will work with the way I am doing the tool recipes currently but it sounds like it should.

**Comment by MechWarrior99** [comment]
Cool, thank you very much! :)

**Comment by An-Sar** [comment]
Looks like this will work with some minor refactoring.

**Comment by MechWarrior99** [comment]
Yay, glad to hear it will work!

**Comment by An-Sar** [comment]
This has been released as part of 0.2.11

**Comment by MechWarrior99** [comment]
Seems to work fine :) 

Thank you!

**Comment by An-Sar** [comment]
This is fixed and has been tested, thank you
