### ISSUE TITLE
Crafttweaker Sariras problem

### ISSUE THREAD

**Issue by TimGoll** [An-Sar/PrimalCore#270]
Recipes like this
![image](https://user-images.githubusercontent.com/13639408/46583723-5c0d2480-ca5b-11e8-9e92-3d24eabfd5a3.png)
do not work because I have the same item twice. It detects it is in there twice, but I'm unable to light the sariras

**Comment by An-Sar** [comment]
have you tried increasing the stacksize on the plates rather than putting the itemstack in twice?

**Comment by TimGoll** [comment]
yes, but if I write *2 like with the coal it doesn't even detect it. It still stays at 1

**Comment by An-Sar** [comment]
what version are you using?

**Comment by An-Sar** [comment]
and can you post your CT script?

**Comment by TimGoll** [comment]
The newest, 0.6.94

The working one:
```
mods.primal.Smelter.addRecipe(
    "iron_mechanical_component_sariras", 
    10, 
    [<ore:plateIron>, <immersiveengineering:metal>, <minicoal:minicharcoal> *5, <ore:ingotIron>], 
    [<immersiveengineering:material:8>, <primal:slag> *4]
);
```

The not working one:
```
mods.primal.Smelter.addRecipe(
    "iron_mechanical_component_sariras", 
    10, 
    [<ore:plateIron>, <immersiveengineering:metal>, <minicoal:minicharcoal> *5, <ore:plateIron>], 
    [<immersiveengineering:material:8>, <primal:slag> *4]
);
```

**Comment by An-Sar** [comment]
i'm reworking how the CT ingredients get converted from ore dictionary names, the amount was getting lost along the way, so using the standard * operator will work in the next version

**Comment by TimGoll** [comment]
cool!

**Comment by An-Sar** [comment]
i believe this has been resolved, closing for now
