### ISSUE TITLE
I got a crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [An-Sar/PrimalCore#272]
Hello!

 

I got an issue with the mod:

https://paste.ee/p/xITci

**Comment by RodrigoTaipe93** [comment]
All of the latest version of the mods:
 
- https://paste.ee/p/voQ0P

**Comment by An-Sar** [comment]
@RodrigoTaipe93 the first bug was fixed in 0.6.95, updating primal should fix your problem.

second crash @kitsushadow

**Comment by kitsushadow** [comment]
this is fixed in .25
