### ISSUE TITLE
Where do I find Netjry Salt?

### ISSUE THREAD

**Issue by RavenChan1023** [An-Sar/PrimalCore#279]
Hello, I'm having trouble finding netjry salt blocks. Is there a specific biome they spawn in? If I can't find it in the overworld, my only option would be to look in the nether, but that would mean going in before I can even make armor.

**Comment by An-Sar** [comment]
Biomes that are DRY, SANDY, MESA, SAVANNA, WASTELAND

**Comment by RavenChan1023** [comment]
Ok, thanks.
