### ISSUE TITLE
Server crash on TNT explosion near loam

### ISSUE THREAD

**Issue by Falconloft** [An-Sar/PrimalCore#28]
Only one user on the server, so I'm sure it was the explosion that crashed it. Crash log attached. I don't really know what to make of it.
[crash-2017-01-04_14.13.47-server.txt](https://github.com/An-Sar/PrimalCore/files/685661/crash-2017-01-04_14.13.47-server.txt)

**Comment by An-Sar** [comment]
Thank you for the bug report, I will look into this for the next release. 

Also, Loam is actually kind of experimental and is not entirely functional at the moment.

**Comment by An-Sar** [comment]
This should be fixed as part of 0.2.22 and 0.3.1

**Comment by An-Sar** [comment]
0.2.22 is released and this was tested and passed on a server.
