### ISSUE TITLE
Cauldron Not Creating Tannin

### ISSUE THREAD

**Issue by RavenChan1023** [An-Sar/PrimalCore#280]
As the title states, for whatever reason my cauldron isn't making tannin. I have ground resin in, I have water in, cauldron is hot with a heat source right under it, and I've been waiting for several minecraft days for this cauldron to create tannin so I can finally get armor. The only reason I have an armor rating at all is because of another mod that adds an exceptionally difficult ore to find.

I have PrimalCore version 0.6.98
This is the image of my cauldron setup: https://ibb.co/cGq0wV

**Comment by An-Sar** [comment]
the amount of tannin is 1 per 250mb of water, so  4 per bucket.

**Comment by RavenChan1023** [comment]
Thanks
