### ISSUE TITLE
Getting launched of thatch

### ISSUE THREAD

**Issue by EvertX** [An-Sar/PrimalCore#286]
So here I was building my primitive hovel out of logs and dried thatch slabs, when I suddenly found myself mid-air while putting on the roof. The ground didn't like me hitting it that hard so it killed me.
Then it happened again, and again. When I investigated, it seemed that thatch functions as a trampoline? Is this intended, if so I'd like to turn it off please :)

**Comment by An-Sar** [comment]
thatch has similar bounciness to a vanilla bed, possibly there is a bad mod interaction exaggerating the effect, do you have a mod list?

**Comment by An-Sar** [comment]
Can you also test jumping on a block of Ovis Atre wool?

**Comment by EvertX** [comment]
I'll test Ovis wool later, here's my modlist:

[Advanced Mortars](https://minecraft.curseforge.com/mc-mods/283777">)
[Animania](https://minecraft.curseforge.com/mc-mods/261199)
[AppleCore](https://minecraft.curseforge.com/mc-mods/224472)
[AppleSkin](https://minecraft.curseforge.com/mc-mods/248787)
[Aroma1997Core](https://minecraft.curseforge.com/mc-mods/223735)
[AromaBackup](https://minecraft.curseforge.com/mc-mods/225658)
[AutoRegLib](https://minecraft.curseforge.com/mc-mods/250363)
[B.A.S.E](https://minecraft.curseforge.com/mc-mods/246996">)
[Backpacks!](https://minecraft.curseforge.com/mc-mods/223957">)
[Baubles](https://minecraft.curseforge.com/mc-mods/227083">)
[Bed Patch](https://minecraft.curseforge.com/mc-mods/282963)
[Better Animals Plus](https://minecraft.curseforge.com/mc-mods/303557">)
[Better mobGriefing GameRule](https://minecraft.curseforge.com/mc-mods/238361">)
[Better With Mods](https://minecraft.curseforge.com/mc-mods/246760">)
[BetterFps](https://minecraft.curseforge.com/mc-mods/229876)
[BetterWithLib](https://minecraft.curseforge.com/mc-mods/294335">)
[Canny Composter](https://minecraft.curseforge.com/mc-mods/297884">)
[Carry On](https://minecraft.curseforge.com/mc-mods/274259)
[Ceramics](https://minecraft.curseforge.com/mc-mods/250617">)
[Chisel](https://minecraft.curseforge.com/mc-mods/235279">)
[Chisels & Bits](https://minecraft.curseforge.com/mc-mods/231095">)
[CoFH Core](https://minecraft.curseforge.com/mc-mods/69162">)
[CoFH World](https://minecraft.curseforge.com/mc-mods/271384">)
[Comforts](https://minecraft.curseforge.com/mc-mods/276951">)
[ConnectedTexturesMod](https://minecraft.curseforge.com/mc-mods/267602">)
[ContentTweaker](https://minecraft.curseforge.com/mc-mods/237065">)
[CraftStudio API](https://minecraft.curseforge.com/mc-mods/268704)
[CraftTweaker](https://minecraft.curseforge.com/mc-mods/239197">)
[Culinary Construct](https://minecraft.curseforge.com/mc-mods/296676)
[Daring Debug](https://minecraft.curseforge.com/mc-mods/297606">)
[DrCyano's Lootable Bodies](https://minecraft.curseforge.com/mc-mods/240968)
[Dynamic Surroundings](https://minecraft.curseforge.com/mc-mods/238891)
[Dynamic Trees - Traverse Compat](https://minecraft.curseforge.com/mc-mods/296604)
[Dynamic Trees](https://minecraft.curseforge.com/mc-mods/252818)
[Engineer's Doors](https://minecraft.curseforge.com/mc-mods/291126">)
[Farseek](https://minecraft.curseforge.com/mc-mods/229708)
[Ferdinand's Flowers](https://minecraft.curseforge.com/mc-mods/282077">)
[FoamFix for Minecraft](https://minecraft.curseforge.com/mc-mods/278494)
[Food Funk](https://minecraft.curseforge.com/mc-mods/296430">)
[Friendly Fire](https://minecraft.curseforge.com/mc-mods/255105)
[Geolosys](https://minecraft.curseforge.com/mc-mods/271856)
[Grappling Hook Mod](https://minecraft.curseforge.com/mc-mods/238911">)
[Hardcore Darkness](https://minecraft.curseforge.com/mc-mods/225957">)
[Harvestables](https://minecraft.curseforge.com/mc-mods/267959">)
[Hunger Overhaul](https://minecraft.curseforge.com/mc-mods/224476)
[Immersive Engineering](https://minecraft.curseforge.com/mc-mods/231951">)
[Immersive Petroleum](https://minecraft.curseforge.com/mc-mods/268250">)
[Inspirations](https://minecraft.curseforge.com/mc-mods/284007">)
[jabelar's Moving Light Sources](https://minecraft.curseforge.com/mc-mods/304439">)
[Just a Few Fish](https://minecraft.curseforge.com/mc-mods/235261">)
[Just Enough Items](https://minecraft.curseforge.com/mc-mods/238222">)
[LootTableTweaker](https://minecraft.curseforge.com/mc-mods/261339">)
[Mantle](https://minecraft.curseforge.com/mc-mods/74924">)
[Material Changer](https://minecraft.curseforge.com/mc-mods/268643">)
[ModTweaker](https://minecraft.curseforge.com/mc-mods/220954">)
[More Cauldrons](https://minecraft.curseforge.com/mc-mods/290545">)
[Mouse Tweaks](https://minecraft.curseforge.com/mc-mods/60089">)
[MTLib](https://minecraft.curseforge.com/mc-mods/253211">)
[No Recipe Book](https://minecraft.curseforge.com/mc-mods/284904)
[Open Glider](https://minecraft.curseforge.com/mc-mods/252354">)
[Particle generator](https://minecraft.curseforge.com/mc-mods/251578">)
[Placebo](https://minecraft.curseforge.com/mc-mods/283644">)
[Plants](https://minecraft.curseforge.com/mc-mods/257229">)
[PrimalCore](https://minecraft.curseforge.com/mc-mods/247907">)
[Quark](https://minecraft.curseforge.com/mc-mods/243121)
[Redstone Flux](https://minecraft.curseforge.com/mc-mods/270789)
[Redstone Gauges and Switches](https://minecraft.curseforge.com/mc-mods/296686">)
[RTFM](https://minecraft.curseforge.com/mc-mods/268344">)
[Ruins](https://minecraft.curseforge.com/mc-mods/227873">)
[Rustic](https://minecraft.curseforge.com/mc-mods/256141">)
[Serene Seasons](https://minecraft.curseforge.com/mc-mods/291874)
[StepupFixer](https://minecraft.curseforge.com/mc-mods/248028)
[Streams](https://minecraft.curseforge.com/mc-mods/229769)
[SwingThroughGrass](https://minecraft.curseforge.com/mc-mods/264353)
[Switch-Bow](https://minecraft.curseforge.com/mc-mods/257820">)
[The Disenchanter Mod](https://minecraft.curseforge.com/mc-mods/245769">)
[The One Probe](https://minecraft.curseforge.com/mc-mods/245211">)
[The Weirding Gadget](https://minecraft.curseforge.com/mc-mods/258914">)
[Thermal Foundation](https://minecraft.curseforge.com/mc-mods/222880">)
[Thirsty Bottles](https://minecraft.curseforge.com/mc-mods/263498">)
[Tool Belt](https://minecraft.curseforge.com/mc-mods/260262">)
[Tool Progression](https://minecraft.curseforge.com/mc-mods/266550">)
[Tough As Nails](https://minecraft.curseforge.com/mc-mods/246391)
[Traverse](https://minecraft.curseforge.com/mc-mods/267769)
[UBC - Reworked and Fixed](https://minecraft.curseforge.com/mc-mods/300938)
[Waddles](https://minecraft.curseforge.com/mc-mods/251767)
[Water Control Extreme](https://minecraft.curseforge.com/mc-mods/277890)
[Wumple Util Library](https://minecraft.curseforge.com/mc-mods/298323">)
[Zen: Foundry](https://minecraft.curseforge.com/mc-mods/303857">)

**Comment by EvertX** [comment]
Ovis wool doesn't show the behaviour. But I did some more tests and all I can say is that it is inconsistent. Sometimes I get launched, and sometimes I don't. It seems to happen randomly?

**Comment by An-Sar** [comment]
i have a [dev build](https://www.dropbox.com/s/ariqz04h6p938mt/PrimalCore-1.12.2-0.6.103.1.jar?dl=0) with some related changes, if you can test, let me know if the issue is still happening.

**Comment by EvertX** [comment]
Yes, that seems to have solved it!

**Comment by Moroz-jpeg** [comment]
i like this feature bro
does not need to be fixed
