### ISSUE TITLE
[Question?] Craftweaker Flaking Recipes

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#288]
I appear to be having an issue with the crafttweaker flaking recipes, I am attempting to create a recipe as follows;
mods.primal.Flake.addRecipe(CopperClusterToClump, 1.5, 20, 2, <geolosys:cluster:2>, <mekanism:clump:3>);

The issue I have is that when I load a world ingame this appears in chat;
ERROR: Primal Flaking.zs:14 > Could not find CopperClusterToClump

I assume this is because I need to define the string somewhere so it knows what string to use for each script however the wiki you have does not let me know of any such feature, Also it would be useful if a completed example existed alongside the already provided one, Thanks!          -UnlimatedStone9

**Comment by UnlimatedStone9** [comment]
I also cannot find where the already existing strings are so I can remove existing recipes

**Comment by UnlimatedStone9** [comment]
From my understanding this command is suppose to help;
/primal recipes flaking
however it only displays the message: Usage: " invalid recipe catecory
(Misspelled too if that's your doing)

**Comment by An-Sar** [comment]
try putting CopperClusterToClump in quotes

i'll double check the recipe command for flaking recipes.

**Comment by UnlimatedStone9** [comment]
Ok it no longer displays an error but it does not import any recipes either so I cannot knapp inworld

**Comment by An-Sar** [comment]
put geolosys:cluster:2 and mekanism:clump:3 each inside <>, I assume the numbers are meant to be meta data?

**Comment by UnlimatedStone9** [comment]
Yes the numbers are metadata and they are in <>

**Comment by UnlimatedStone9** [comment]
![configsforflaking](https://user-images.githubusercontent.com/40124890/48443129-0f1e1b80-e788-11e8-9182-aba310b726de.PNG)
This is my scripts file

**Comment by An-Sar** [comment]
the second two values after the recipe name are floats and should be much lower, 
here is an example that flaked poppies into red dye

```

mods.primal.Flake.addRecipe("dye_red", 1.5F, 0.45F, 0.9F, <minecraft:red_flower>, <minecraft:dye:1>);

```

the correct recipe command is:
```

/primal recipes flake

```

running just /primal recipes will show you all the available recipe handlers

**Comment by UnlimatedStone9** [comment]
Sorry to bother you An-Sar but I believe the inworld knapping does not work at all, I couldn't get the scripts to work

**Comment by UnlimatedStone9** [comment]
I am going to run another quick test and if it does not work I shall let you know

**Comment by UnlimatedStone9** [comment]
Ok I tested your example in a new modpack with only PrimalCore and Crafttweaker installed and it worked like a charm, I must have written something wrong, thanks again!
