### ISSUE TITLE
[Suggestion] Configurable Block Breaking Physics

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#289]
I was curious to know if the block breaking physics added in this mod could become configurable?
(Eg: when I break a log with my fists it hurts me and returns no drops)
I would like to disable this feature and allow the player to obtain its drops with their fists again, thanks!

                                                                                                                                            -UnlimatedStone9

**Comment by An-Sar** [comment]
**_Survival.HARD_BLOCKS_HARDNESS_** set to 0 will disable the block damage
**_Survival.HARVEST_LOGS_REQUIRE_TOOLS_** to se false should disable needing a tool to harvest logs

**Comment by UnlimatedStone9** [comment]
Thank you, I shall test to see if this works for me

**Comment by An-Sar** [comment]
Survival is the section of the config, just search for the latter part of the config name

**Comment by UnlimatedStone9** [comment]
I just did and located it, sorry to bother you

**Comment by An-Sar** [comment]
no problem

**Comment by UnlimatedStone9** [comment]
Ok, That worked! Issue closed!
