### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by shortybsd** [An-Sar/PrimalCore#29]
Minecraft 1.11
Forge 2199
PrimalCore-0.3.0

Would it be possible to disable your mods ore dust entirely that or add all of your ore in the ore dictionary? I am having major issues with tin from Forestry & TechReborn. Actually Additions grinder converts all tin to PrimalCore tin dust which is unusable.

**Comment by An-Sar** [comment]
That's interesting the dusts are registered in the ore dict, I wonder why they aren't usable by the other mods. Also adding a config option to disable the ore items is possible. 

I am currently working on a merging all the recent changes from the 1.10 version to 1.11.

**Comment by shortybsd** [comment]
Awesome, I cannot wait til you do so! Yeah, all my ores I can no longer double in a grinder it makes the PrimalCore ores which cannot be smelted, Everyone was raising heck about it so I made a CustomNPC trader trade for a temp fix. I absolutely love the limestone bricks in the mod so had to grab it! 1.11 and 1.11.2 are missing insane decoration blocks so might be a thing to consider down the road :P

**Comment by An-Sar** [comment]
this has been addressed
