### ISSUE TITLE
[Quality Of Life Suggestion] Torches

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#291]
Hey AnSar, I was curious to know if you could implement something, configurable or not
I was wondering if you could make it a feature that when clicking on a torch with the fire bow, or flint and steel etc, whatever is used to light them, they would not go out.
The reason for this is because I have had many times where I would be lighting a torch and have it go out almost instantly, Thank you!
          -UnlimatedStone9

**Comment by UnlimatedStone9** [comment]
If it was configurable it could be named
Awkward_first_torch, or something similar, as after getting the first lit you can light the rest off of it, so it's not the most needed feature but it is something that drives me mad

**Comment by An-Sar** [comment]
this actually used to be a feature, but was take out during a rewrite of the ILit interface logic. i can do some testing and possibly re-add it.

**Comment by inkdear** [comment]
I believe this still happens when lighting the hibachi.

**Comment by UnlimatedStone9** [comment]
Great, glad this was resolved, however, what's wrong with the hibachi?

**Comment by inkdear** [comment]
I'm (pretty) sure you can put it out with the item used to light it.
