### ISSUE TITLE
Ironwood barrel lid not displayed as Fireproof

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#294]
It's as simple as that, the ironwood barrel itself is displayed as fireproof, like the corphyry barrel but the ironwood lid is not, unlike the corphyry lid

**Comment by UnlimatedStone9** [comment]
![iwbarrel](https://user-images.githubusercontent.com/40124890/48808508-faf29500-ed18-11e8-9058-d012e51abc65.png)
![corbarrel](https://user-images.githubusercontent.com/40124890/48808513-00e87600-ed19-11e8-8574-8ae001bc646f.png)

**Comment by An-Sar** [comment]
this has been fixed (0.6.105)

**Comment by UnlimatedStone9** [comment]
Thanks An-Sar!
