### ISSUE TITLE
[Feature Requst] picking up torches annoyance

### ISSUE THREAD

**Issue by TimGoll** [An-Sar/PrimalCore#296]
When you break and pickup torches they are unlit. It is a bit annoying to have two stacks of torches in your inventory every time you break a torch. Therefore I'd recommend to pick them up as lit torches as long as you carry lit torches in your inventory.

**Comment by An-Sar** [comment]
you can sneak click to pick up the lit torch

**Comment by TimGoll** [comment]
Hmm, thats actually a good way of doing it but I'm pretty sure that most players don't know about this

**Comment by An-Sar** [comment]
the vanilla torch replacement used to have a tooltip but it was lost when i changed to a new override method, i've just re-added the text, so at least that should help.

**Comment by TimGoll** [comment]
that's nice, thank you!

**Comment by An-Sar** [comment]
There are actually several blocks that can be picked up in a similar fashion, most have tooltips..
i've also added a note about the feature to the Game-Play-Changes page of the wiki

**Comment by TimGoll** [comment]
Yes I know about them. But I totally forgot about it while picking up torches
