### ISSUE TITLE
(missing config option) oregen

### ISSUE THREAD

**Issue by meelock** [An-Sar/PrimalCore#3]
One of the main issues I have been experiencing while working on my modpack is that primal core is missing just about any control over its oregen in the config, the main oregen option I want to change is for carbonate stone, as i am using it in my modpack for a progression step point.

I hope you think about this issue, and maybe give me some feedback as to when you (if you have this planned) are going to be adding this.

-meelock

**Comment by An-Sar** [comment]
I can add hooks for each type of worldgen.

**Comment by An-Sar** [comment]
I have added hooks for each individual worldgen feature. This will be pushed as part of the 0.20 release.

**Comment by An-Sar** [comment]
This has been released.
