### ISSUE TITLE
[1.11] [PrimalCore-0.3.0] Breaking grass crashes server - UnsupportedOperationException

### ISSUE THREAD

**Issue by shortybsd** [An-Sar/PrimalCore#30]
Minecraft 1.11
Forge 2199
PrimalCore-0.3.0

Breaking grass crashes server with the following error:
http://pastebin.com/DFYHT5B5

**Comment by An-Sar** [comment]
0.3.1 has been released with a fix for this crash

**Comment by ivardensphere** [comment]
http://pastebin.com/xfYRkNtX

Per request

**Comment by An-Sar** [comment]
I believe this has been resolved.
