### ISSUE TITLE
PrimalCore/Vanilla beds not working

### ISSUE THREAD

**Issue by Blinky-Dorf** [An-Sar/PrimalCore#307]
Both the Tatami and Vanilla beds are not working, despite changes to the configurations. Are there more than the three attached configs that affect sleeping through the night? I've tried all combinations of the attached configs, and neither Vanilla nor PrimalCore beds are functioning, and they are also not resetting the spawn point. Beds were tested in several fresh singleplayer worlds at various times in the day/night cycle.

Forge Version:
1.12.2-forge1.12.2-14.23.2.2628

I understand if my forge version may be causing the issue. I am, however, not an experienced modder, so please be gentle.
 Modlist is attached. Hopefully the PNGs will go through.
![troubleshoot 1](https://user-images.githubusercontent.com/47131873/51882975-efda6780-234e-11e9-80c0-b7c3a3a6de1e.PNG)
![troubleshoot 2](https://user-images.githubusercontent.com/47131873/51882980-f963cf80-234e-11e9-9171-10ab68c9bc3a.PNG)
![troubleshoot 3](https://user-images.githubusercontent.com/47131873/51882989-02ed3780-234f-11e9-97a4-01dfc52ce00d.png)
![troubleshoot 4](https://user-images.githubusercontent.com/47131873/51883009-1bf5e880-234f-11e9-9b37-817b2c1de1b9.PNG)

**Comment by Blinky-Dorf** [comment]
I updated the Forge version to 1.12.2-14.23.5.2768 (newest stable), and beds have restored functionality. You were right, older Forge versions conflict with beds.

**Comment by An-Sar** [comment]
that's good to know, thank you for testing
