### ISSUE TITLE
Errors About Language And Textures.

### ISSUE THREAD

**Issue by cinsiian** [An-Sar/PrimalCore#308]
I found errors about language and textures. Can you fix these errors?
![2019-02-03_11 30 54](https://user-images.githubusercontent.com/44293974/52175662-5aecc980-27a7-11e9-8c39-de5e1b4bcf84.png)
![2019-02-03_11 31 47](https://user-images.githubusercontent.com/44293974/52175666-60e2aa80-27a7-11e9-9974-26088f332816.png)
![2019-02-03_11 31 40](https://user-images.githubusercontent.com/44293974/52175670-67712200-27a7-11e9-847f-5280cfa26d24.png)

Very thanks if you fix these errors. - Nov4e

**Comment by An-Sar** [comment]
thanks for the report. these have been fixed (0.6.105)
