### ISSUE TITLE
[Suggestion/Fix] Mud Sariras Lid uncraftable from Betweenlands Mudbrick unlike Mud Sariras

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#312]
It's basically all in the title, the mud sariras can be made from betweenlands mudbricks but the lid is not possible to make from them, making it awkward to obtain in the dimension/impossible by default
![image](https://user-images.githubusercontent.com/40124890/53665001-1ea37080-3c62-11e9-8efb-ca146b0f280a.png)
![image](https://user-images.githubusercontent.com/40124890/53665019-26631500-3c62-11e9-9742-b0641b03725d.png)

**Comment by An-Sar** [comment]
resolved for next release
