### ISSUE TITLE
Crafting of sticks doesn't work because of conflict

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#314]
I don't even understand how this happens, but I suppose it did, would appreciate if it worked as intended

![image](https://user-images.githubusercontent.com/40124890/55690178-ef310380-5985-11e9-980c-8331cf7ed029.png)

![image](https://user-images.githubusercontent.com/40124890/55690183-f526e480-5985-11e9-81c9-51aaf172e2d6.png)

**Comment by An-Sar** [comment]
resolved for next release

https://i.imgur.com/XcoeJ3P.png

**Comment by UnlimatedStone9** [comment]
Perfect, Thanks An-Sar!
