### ISSUE TITLE
[Mild Issue] /primal recipes (Category) returns gramatically incorrect message

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#315]
![image](https://user-images.githubusercontent.com/40124890/56095390-437f3a80-5ed4-11e9-98aa-52d1da226216.png)

Returns the word "Catacory" instead of "Category", not really an issue, just though I'd let you know

**Comment by An-Sar** [comment]
this has been resolved for 0.6.105, thank you

**Comment by UnlimatedStone9** [comment]
You're welcome, thanks!

**Comment by An-Sar** [comment]
0.6.105 has been released
