### ISSUE TITLE
[Suggestion] Cauldron lids use pins instead of buttons

### ISSUE THREAD

**Issue by UnlimatedStone9** [An-Sar/PrimalCore#317]
Wouldn't the wooden pin make more sense as a handle on the lid?
![image](https://user-images.githubusercontent.com/40124890/56472829-66bd6300-645b-11e9-98c8-39b2e9218e3a.png)
![image](https://user-images.githubusercontent.com/40124890/56472843-881e4f00-645b-11e9-84d6-ed1c9faec53b.png)

**Comment by An-Sar** [comment]
yeah or at least as an option. i originally used a button just bc it looks similar.

**Comment by An-Sar** [comment]
for now i've added pins as an alternative recipe
