### ISSUE TITLE
Crash relating to Primal Core.

### ISSUE THREAD

**Issue by dalekfan** [An-Sar/PrimalCore#318]
I am currently using the latest version of Primal Core, with forge 14.23.5.2768 for 1.12.2. The game seems to be crashing due to a "itemexpire" rule revolving around a "ender_flower." The only two flowers with a similar name would be the ones from Enderman Evolution and Bionisation 3. I'm working on a massive modpack, so that's why I have a crapload of mods. Here is the pastebin info for the crash: https://pastebin.com/tcexmD19

**Comment by An-Sar** [comment]
i cannot reproduce this crash using the bionistation 3 plants, do you have any idea what block the plant might be trying to plant itself on?

as a quick fix you could set **PLANT_AUTO_MAGIC_CHANCE** to 0 or add _bionisation3:enderflower_ to **PLANT_AUTO_MAGIC_BLACKLIST**.

**Comment by dalekfan** [comment]
It has to be enderman evolution then. I have no idea what "plant_auto_magic_chance" is or where to even find it.

**Comment by An-Sar** [comment]
actually now that i'm looking at my own change log i think i fixed this a few months back in dev, 

check your primal.cfg file for a Plants section and **PLANT_AUTO_MAGIC_BLACKLIST** and add _endermanevo:ender_flower_, below you can see the full entry as it exists in the upcoming release.

```
    S:PLANT_AUTO_MAGIC_BLACKLIST <
        coralreef:reef
        coralreef:coral
        bamboozled:bamboo
        endermanevo:ender_flower
     >
```
