### ISSUE TITLE
1.10.2 - Testing and noted issue.

### ISSUE THREAD

**Issue by XvSkItZvX** [An-Sar/PrimalCore#32]
I have been working, privately, or compiling a mod-pack that delivers a more involved and realistic early game. To that end I am extremely interested in this mod as serves that need very well. 

For your Information, if it is useful, this is the current list of [mods](http://www.modlister.com/user/XvSkItZvX ).

I have been testing within that pack for the past few days, setting configs and seeing what type of player experience it provides. 

During that time I noticed the following quirks;

(suspected to not be fully implemented)
- Config has an option to "Disable Vanilla Coal" but however does not prevent it from spawning. 
- Config has an option to "Enable Stone Anvils" yet have been unable to find a recipe to craft one.
-And option to provide a list of blocks to be treated as logs, but what's the format?

(Actual issues noted in game)
- When crafting the "Log Work Table" using both the hatchet and the axe the tool is consumed regardless of it's durability. 
- Lighting/Picking up torches;
     The controls regarding torches are not consistent. When using the Fire bow you are able to light a torch in the world only by holding 'sneak' and right clicking, Lighting a torch with a lit torch in your hand can only be done when not holding the sneak key. And once you have lit a torch in the world, you are only able to pick it up if both hands are empty while holding the sneak key. The over all placing, light, and picking up of the torches in both states seems to be a bit awkward.
- Generation 'wax', 'paraffin' and 'clay' spawns are huge and excessive. The concept was quite useful but was overly abundant to not be over powered. 

--Quality of Life Suggestion: 

-Ash Generation: The pile of ash, for the most part, seems useless and inconvenient having to run around and collect it from random places around where you're living. I like the concept but it seems to have use other than annoyance at this point and time. I'd like to suggest the ability to use it as a fertilizer (not like bone meal even that is done wrong) that will increase it's growth rater per tick. Additionally the ability to turn this off all together would be appreciated as well.

-Torches: As a matter of convenience being able to light a stack of torches by placing a lit torch into the crafting matrix what a stack of unlit torches would definitely counter having to light either a stack one at a time to carry, or light each one as they're placed. I use "Dynamic Lights" mod, but without that I would find myself in absolute darkness trying to light torches in the world which is highly inconvenient. Additionally the ability to light a torch in the world with a lit torch in the off hand would be useful as well.

-Compatibility Tinkers Construct: I have used the config to disable all of the vanilla tools, which works how I expected. However using TiC in combination with PrimalCore leaves the ability to make wooden and stone weapons possible. Not to mention paper, but because of the benefit of paper I don't know what to say other than talk with them. Is it possible for you to make a setting in your config to disable wooden and stone tool heads (leave the sword blades)?

I have additionally been keeping an eye on Kitsu's ForgeCraft though haven't began testing with it. I really like the direction you guys are taking with mods. If there is anything I can be of assistance with in the future feel free to ask. Now, while I've been typing this you released a new build so I'm off to up date.

**Comment by An-Sar** [comment]
Thank you for the feedback. 
- "Disable Vanilla Coal" -- are you sure another mod isn't doing some custom generation?
- "Enable Stone Anvils" -- not yet implemented 
- The format for logs should be "modid:the_block_name"
- "Log Work Table" -- this has been fixed and will be released as part of 0.2.19
- 'wax', 'paraffin' and 'clay' spawns are meant to be very large, maybe the frequency is too high, how often are you encountering the wax, also maybe the wax should require some level of processing before it can be used as a fuel...
- I have added a config hook to disable smoke creation, it will be released as part of 0.2.19
- Torches, currently you can light an entire stack in-world by clicks a lit torch with an unlit stack. Also I am messing around with the interaction mechanics now.. may or may not have some changes for the next release.
- Tinkers, Primal does have a builtin recipe remover, it might be possible to block those tool parts, I would have to mess around a little bit to see how that works. Ideally tinkers would provide those config hooks but I realize that might not be something the current dev is interested in.

I expect to push 0.2.19 later today

**Comment by XvSkItZvX** [comment]
-Vanilla Coal: My best guess would be the "Realistic Generation" option provided by the "Quark" mod which was added at the time.

Wax, Paraffin, Clay: Honestly I only tested this specifically in one world before disabling them. However in worlds where I was testing other items from the mod I was able to find numerous veins just traveling around the surface. However the one vein I did investigate, which was either within range on 3-5 other veins or much larger than I'm estimating, was large enough for me to quit counting stacks 20, dug under a river (that was 6m wide and 4m deep), and left me with the impression that I hadn't even cleared out half that vein. 

One other test in particular was the clay which was a huge vein as well, seemed to line a substantial portion of a cave entrance. However because of the need of a quick furnace for the 'Tough as Nails" to get to clean water, I opted out of rocks for cobble stone. Additionally I prefer to minimize "CraftTweaker" and because TiC requires clay for grout (which I think could be suitable replacement for mortar in cases where TiC is installed) I didn't want to have to use "CraftTweaker" to make the recipes interchangeable. 

I have done so more testing with the torches, and it seems that there are some how 3 types of torches (based on item numbers). Not sure what steps are taken exactly to get each of them and it would be a bit complicated to try and explain here. I will look into setting up to screen capture and upload to youtube so you can see what I'm running into. some how I'm ending up with "Torch 50" which seems to be vanilla torch (based on behavior with Sphax Resource pack and Dynamic Lights Mod), "Torch 5161" unlit Primal Torch I believe, and then "Lit Torch 5404" the lit torch from PrimalCore...

All torches above, when set in the world are listed as [primal:torch_wood@#] which I'm not completely familiar with how this all works but I am going to assume that the "@#" portion is metadata denoting the amount of time left before the torch burns out or if it is already out. 

I have a number of suggestions to make to the TiC developers and will include the ability to disable materials on a per part basis.

**Comment by An-Sar** [comment]
The clay is also a unique building material, I may add a config hook to determine if the clay should be registered with the ore dictionary or not, that would by pass any balance issues regarding recipes that use vanilla clay.
