### ISSUE TITLE
[question] Is it possible to disable villager trades added by primal in the config?

### ISSUE THREAD

**Issue by xkforce** [An-Sar/PrimalCore#320]
Am I missing something in the config?

**Comment by An-Sar** [comment]
no you cannot in the current version. i have just added a new config **_Compatibility.VANILLA_ENABLE_TRADES_**, this will be in the next release

**Comment by xkforce** [comment]
That was fast.  Nice work.

**Comment by An-Sar** [comment]
0.6.105 has been released
