### ISSUE TITLE
Usage: "invalid recipe catacory

### ISSUE THREAD

**Issue by Winddbourne** [An-Sar/PrimalCore#322]
When I do /primal recipes drying this is the error code I get. The command seems to work with all other categories I've tried . . . but it refuses to give me the names of drying recipes.  

I'd like to delete the drying rack recipe that turns blocks of clay into blocks of terracotta because I've got Tinker's Construct in the pack and it makes more sense to dry it into dried clay and leave the Terra Cotta recipes to the furnace type blocks.

**Comment by An-Sar** [comment]
this has been resolved, see https://github.com/An-Sar/PrimalCore/issues/300

**Comment by An-Sar** [comment]
0.6.105 has been released
