### ISSUE TITLE
B:SURVIVAL_WOOD_HARVESTING_TOOLS Doesn't respect oreDictionary 

### ISSUE THREAD

**Issue by grundyboy34** [An-Sar/PrimalCore#33]
I've noticed that the B:SURVIVAL_WOOD_HARVESTING_TOOLS is having issues with Natura. I'm not sure how you have the mod programmed, but it's respecting forestry, vanilla, and biomes'o'plenty woods. However, Natura still gives drops and I'm unsure why. All of these are entered as "logWood" in the ore Dictionary.

Could this be updated to respect all blocks that are entered as "logWood" or is this perhaps an odd issue with Natura?

**Comment by An-Sar** [comment]
I took a look at this and it should be a simple rewrite to switch over to ore dictionary. This should be released as part of the next version.

**Comment by An-Sar** [comment]
This has now been pushed as part of 0.2.21, since compatibility is now handled through the ore dictionary I have retired the old config hook to add custom log types as a list. If that functionality is still desirable I would be interested to hear about it.

**Comment by An-Sar** [comment]
Additional fixes for this are included in 0.2.23

**Comment by grundyboy34** [comment]
Hi, I can confirm that you've fixed the issue.

**Comment by An-Sar** [comment]
thanks for the feedback
