### ISSUE TITLE
Random question about open source

### ISSUE THREAD

**Issue by WolfieWaffle** [An-Sar/PrimalCore#331]
Did this mod used to be closed source? I remember a long time ago I tried to make an addon that added Biomes O Plenty variants of the wood items, but I think I had to decompile the mod and all the blocks were private so I couldn't use the constructor, leading to me having to extend the blocks but this caused some problems and I could never get it working as a result.

If this mod is now open source, would it be possible to open up those constructors? Basically every other mod does it so I don't see why it would be a problem. That way maybe I could finally get some addons working, especially for stuff like adding roots for BOP grasses which I saw a suggestion for in the issues if this GitHub.

**Comment by An-Sar** [comment]
it is source visible by way of a maven repo, i think it will open further as i get time to fully focus on 1.14+

in regards to extending blocks etc, all the blocks should be public. i might need to see exactly what you were trying to do.
