### ISSUE TITLE
Gallagher in CraftTweaker does not work

### ISSUE THREAD

**Issue by Hallowizer** [An-Sar/PrimalCore#332]
Hello! I am currently working on a modpack containing PrimalCore, and I was trying to make a Gallagher recipe:

```Gallagher.addRecipe("smash_barrel", <ceramics:clay_barrel>, <contenttweaker:clay_dust> * 7);```

I have the Gallagher properly imported, but in JEI, the recipe appears incorrectly:

![2019-07-10_11 53 58](https://user-images.githubusercontent.com/40325350/60996425-6c637000-a309-11e9-930f-eec09c123882.png)

Then, I tested the recipe, and it actually behaves like it does in JEI. It drops nothing.

Can somebody take a look at this? Thanks!

**Comment by An-Sar** [comment]
The handler is meant to have variable output, so the output amount is actually an array that follows the itemstack, it could be expressed as [0, 4] but if you want a static output amount you just put the single number. Also it's a bit awkward as it is now, you have to set null where the handler expects to get an output blockstate:

```

Gallagher.addRecipe("smash_barrel", <ceramics:clay_barrel>, null, <minecraft:clay_ball>, [7]);

```

**Comment by Hallowizer** [comment]
Thanks!
