### ISSUE TITLE
[Suggestion] Config to allow lanterns to burn out over time

### ISSUE THREAD

**Issue by grundyboy34** [An-Sar/PrimalCore#34]
I'm unsure if lanterns actually do burn out after awhile just like torches do.
Either way though, allowing that functionality to be configured would be a great addition.

**Comment by An-Sar** [comment]
If torches are set to go out naturally "LIGHTING_TORCHES_DIE", then lanterns should also go out, it just takes them a lot longer. I am going to reduce the lifespan bonus a little bit and make sure the feature is actually working before the next release.

**Comment by grundyboy34** [comment]
Thanks for the info, I can confirm they do go out, it just takes a lot longer like you said.

**Comment by An-Sar** [comment]
Does have a combined config option like that work for your use case?

**Comment by grundyboy34** [comment]
Technically yes, I would suggest a config to edit lifetimes though.

**Comment by An-Sar** [comment]
There is in the form of a secondary option LIGHTING_TORCH_LIFESPAN, it is a little convoluted, this value gets used by the weather sensitive mechanics and if torches are set to go out on their own.

The lanterns get a bonus to this base value, etc.

**Comment by grundyboy34** [comment]
Ahh I see, thanks. Making that bonus configurable might be useful.

**Comment by An-Sar** [comment]
I think It will do some clean up and try to make the configs a little more clear.

Basically right now if the torch is exposed to rain it uses the unmodified lifespan, snow gets a x2 modifier, under cover or indoors is x4, and lanterns are x8.

**Comment by grundyboy34** [comment]
Sounds good, thanks for the info on that.

**Comment by An-Sar** [comment]
Thanks for the feedback. At some point I am going to clean up the configs and the code behind it, but that basic lifespan logic will remain the same.
