### ISSUE TITLE
Fluid textures is gone

### ISSUE THREAD

**Issue by miuirussia** [An-Sar/PrimalCore#35]
Minecraft 1.10.2 (Without other mods)
PrimalCore-0.2.32.jar

![2017-03-05_23 38 40](https://cloud.githubusercontent.com/assets/1270028/23591142/0d27999a-01fd-11e7-9722-4a0364645c16.png)

**Comment by An-Sar** [comment]
fluids are getting entirely reworked either during 1.11 or 1.12 life cycle
