### ISSUE TITLE
Inconstant Hand Saw item names

### ISSUE THREAD

**Issue by jlbrewer** [An-Sar/PrimalCore#37]
Flint, Iron: Hand Saw
Quartz, Diamond, Emerald, Copper: Handsaw

Pick one, make life easier for JEI users and FTB Wiki writers. :D

**Comment by jlbrewer** [comment]
Came across another thing: "Oak Work Log Table" instead of "Oak Log Work Table".

**Comment by An-Sar** [comment]
this has been fixed
