### ISSUE TITLE
Ovis Atre are picky eaters

### ISSUE THREAD

**Issue by belathus** [An-Sar/PrimalCore#38]
We have Animania installed, which replaces meats dropped by cows and pigs. They won't eat that meat. Nor will they eat wolf meat, fish, or their own mutton. At least I can feed them overworld sheep. I also remember hearing that they're supposed to be able to eat dried valus stalks, but they don't.

Also, it'd be nice to be able to calm them down after you accidentally hit one. I have a pin full of ovis atre that have been angry at me for hours.

**Comment by An-Sar** [comment]
Which version are you on? withered valus stalk works in my dev environment.
Also they will generally eat any of the rotten variations of meat. I am adding a few of the missing meats. 

In terms of replacing the vanilla drops, accounting for mod meat will take some reworking. I might look at some ore dictionary support.

**Comment by belathus** [comment]
Hm. The withered valus stalks didn't work earlier, but seem to be working now. Probably something I was doing wrong. I'm running 0.2.38.

Divine suggested maybe a list of item IDs in the configs, but that seems less elegant than allowing them to eat anything from the "listAllmeatraw" oredictionary entry.

**Comment by An-Sar** [comment]
Yeah I would tend to prefer an oreDict approach over a config list.

Also I will look into ways to de-aggress the mob, maybe by feeding it again, but it seems that processing interaction gets blocked when it becomes hostile..

**Comment by An-Sar** [comment]
this has been implemented, the following dictionary names are valid foods.

            "foodOvisAtre",
            "foodPoison",
            "foodRot",
            "foodFat",
            "listAllmeatraw",
            "listAllmeatrotten",
            "listAllfishraw",
            "listAllfishrotten"

foodOvisAtre is clearly the general purpose name that should be applied to foods that do not already fall into the other categories. A builtin config list exists, OVIS_ATRE_FOOD_WHITELIST, for applying this dictionary name to arbitrary items.

Additionally OVIS_ATRE_FOOD_BLACKLIST allows removing arbitrary items.
