### ISSUE TITLE
need help with crafttweaker cauldron

### ISSUE THREAD

**Issue by AydenCadillac** [An-Sar/PrimalCore#399]
Hi, I'm rather new to crafttweaker and I'm trying to add a Primal Cauldron fluid recipe for Rustic's ale wort.
I'm working off the wiki examples of adding the recipe but I guess I have problems with syntax and the recipe doesn't get added.
I'm not sure if this is the place to ask this but I'd love to know what I'm doing wrong.

pastebin link https://pastebin.com/ALQ3YPam
(ignore much of the pastebin, the betterwithmods recipe works; I tried doing the primal one in sub-paragraphs like it shows on the wiki but I'm thinking it doesn't change much so it's all in one line, let me know if it does) #

**Comment by gatoborrachon** [comment]
remove "String", "int", "ILiquidStack", "IIngredient" and "IItemStack" from the recipe

**Comment by AydenCadillac** [comment]
it works, thanks :)
