### ISSUE TITLE
Separate control for flint and rock drops

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#4]
SURVIVAL_EXTRA_GROUND_DROPS is all well and good, but the ability to control flint and rock drops separately would be nice. If it's too much trouble, close this and I'll work around.

**Comment by An-Sar** [comment]
thank you for the feedback I am in the middle of a large update, I will add this config hook.

**Comment by An-Sar** [comment]
I have changed these values from booleans to integers, which provide some small control over how likely the drops are to occur. 0 values will disable the drop, while higher values becomes less and less likely. This will be released as part of 0.2.0.

**Comment by An-Sar** [comment]
This has been released. Thank you
