### ISSUE TITLE
Block ID usage is frankly out of control.

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#40]
with 484 block IDs used, Primal Core is by far the greatest user of block IDs. You actually outstrip Orespawn.
For reference, botania and quark use 235.

**Comment by An-Sar** [comment]
You've mentioned this in discord.

**Comment by An-Sar** [comment]
As part of an immediate fix, which may get back ported to 1.10.2. All the sub blocks, and thin slab line of crafting is going to get wrapped in config hooks so they can be completely disabled. This should be part of the next release.

**Comment by An-Sar** [comment]
block count is now below 200
