### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by GeebsRilie** [An-Sar/PrimalCore#41]
I just keep getting this message, and its crashing my world.

> [23:44:36] [Server thread/WARN]: PrimalCore loaded a new chunk (-2, 11  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [23:44:36] [Server thread/WARN]: PrimalCore loaded a new chunk (-3, 12  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [23:44:36] [Server thread/WARN]: PrimalCore loaded a new chunk (-4, 12  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [23:44:36] [Server thread/WARN]: PrimalCore loaded a new chunk (-4, 11  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
> [23:44:36] [Server thread/WARN]: PrimalCore loaded a new chunk (-5, 10  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
>

**Comment by An-Sar** [comment]
The next thing I will be working on is worldgen.

**Comment by MysticAura** [comment]
Hopefully it's addressed soon. It causes intense lag to the point of unplayable. Especially when paired with Quark.. even when I turn off Primal's overworld gen.  I understand rl comes first though. It's just making it difficult to include in any of the packs I'm working on.

**Comment by An-Sar** [comment]
I've started working on worldgen again now.

Also when you say "even when I turn off Primal's overworld gen", are you saying primal is still generating or that other mods (quark) are lagging?

**Comment by GeebsRilie** [comment]
The thing that helped me was turning off all the animal spawning. That's
what was causing most of the lag.

**Comment by An-Sar** [comment]
FYI, I am about to publish 0.4.1, but this does not include any worldgen changes, that will all come in 0.4.2 and later as required.

**Comment by An-Sar** [comment]
What versions are people running @GeebsRilie @MysticAura 

@GeebsRilie When you say animal spawning, which spawns specifically?

Thanks

**Comment by GeebsRilie** [comment]
It was the update that added the sharks. We were doing fine before that.

**Comment by NaturalHate** [comment]
This is either still or again an issue.  
Is there something we as user can do in regards to testing / reporting?
Whenever I go exploring (or testing a new world for that matter) the game becomes completely unplayable until I rejoin the world which makes modpacks since 1.11 & 1.12 very frustrating.

**Comment by kiwifrogg** [comment]
This does not actually cause any real lag, it is really just a message. Watching the tps as people explore on my server it hardly drops, if there was real cascading world lag the server would hang continually going on 5 months now with hardly any resets primalcore is not causing any world gen lag issues. Twilight on the other hand......wow 
 
 It is more a placebo effect you see cascading world lag in the logs and think it must be PC.

**Comment by An-Sar** [comment]
https://github.com/An-Sar/PrimalCore/issues/110
