### ISSUE TITLE
Add leather strips to ore dictionary

### ISSUE THREAD

**Issue by SirWindfield** [An-Sar/PrimalCore#42]
It would be nice to have the leather strips added to the ore dictionary and therefore creating some compatibility with other mods (like BetterBeginnings).
Leviathan143/betterbeginnings-MODIFIED#44

**Comment by An-Sar** [comment]
I will add the oreDict name of "stripLeather", which version are you using, 1.10 or 1.11?

**Comment by SirWindfield** [comment]
1.10.2 currently

**Comment by Leviathan143** [comment]
How does PrimalCore use leather strips? How are they made?

BB uses leather strips as bindings for tools and armour. They're obtained by cutting leather with a knife. Leather is obtained the same way as it is in vanilla.

**Comment by An-Sar** [comment]
It is very similar, you cut leather with a work blade, the strips can be combined into leather cordage which through ore dictionary is available for use in a number of recipes that accept different types of cordage.

Leather is obtained through a tanning process that uses animal hides, salt, tannin, and the drying racks. There is a config hook to disable the custom leather process. At the moment it defaults to being disabled, but that should change.

**Comment by Leviathan143** [comment]
Right, finally getting back to this issue.
@An-Sar That's what I was afraid of. It sounds like PrimalCore's leather strips are harder to get hold of than BB's leather strips. I'm not sure they should be considered interchangeable.

**Comment by An-Sar** [comment]
i am going to close this issue, it can be re-opened at which point Better Beginnings has updated to a more recently version of mc
