### ISSUE TITLE
[0.3.17-1.11] Corypha segment and stripped corypha segment are missing their textures.

### ISSUE THREAD

**Issue by DeadPigman17** [An-Sar/PrimalCore#43]
I'm using 0.317 for 1.11 version of the mod and forge 1.11.2-13.20.0.2286.

![2017-05-13_03 11 25](https://cloud.githubusercontent.com/assets/22800252/26021269/9635bd44-378a-11e7-90a3-d0fdb79d67a2.png)

**Comment by An-Sar** [comment]
This should now be fixed in 0.3.18
