### ISSUE TITLE
compatibility with other mods which modify the Nether

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#44]
It seems there is a problem of compatibility with other mods that modify the nether (BiomesOPlenty, Natura, Ad Inferos). I get this crash at each time I try to go i nether, and reload the world doesn't change anything, I continue to get this crash. https://pastebin.com/6QCM0rXc

**Comment by Hypsellis** [comment]
It seems to work now, but the primalcore nether plant spawn everywhere, including blocks where they aren't supposed to spawn. You should check if the blocks are netherrack, soul sand, tainted soil or heat sand (for natura compability).

**Comment by Hypsellis** [comment]
I noticed too the Basalt from Quark doesn't spawn more in the Nether with PrimalCore installed.

**Comment by Hypsellis** [comment]
I maybe found the source of the crash, it seems to happen only when Quark basalt generate it in the nether.

**Comment by An-Sar** [comment]
That's good to know, I will definitely test with quark. Thanks for doing the testing.

**Comment by Hypsellis** [comment]
The crash still happens with the new version. :(

**Comment by Rikshy** [comment]
I tried to enter the nether with just PrimalCore and one other mod installed.
NetherCore: no crash
AdInfernos: crash
Quark: crash

You can change the configs for quark and adinfernos for not generating basalt (quark) and ores (ad infernos) to make it not crashing, but that shouldnt be a solution

**Comment by An-Sar** [comment]
In 1.11.2 -- 
I just tested quark with basalt enabled, all default configs, no crash
and the same with ad infernos, but I think you are on 1.10 based on a comment I saw on curse, is that correct?

**Comment by Hypsellis** [comment]
Because you surely don't use BiomesOPlenty and Natura. And yes I use 1.11.2

**Comment by Rikshy** [comment]
I'm on 1.10. Sorry for not clearifying
Doing trial and error atm with the adInfernos config - so far it looks like the Obsidian Beach is causing the crash - so again i think its no PrimalCore issue here.

**Comment by An-Sar** [comment]
I've tried all the mods 1:1 with primal and then all together and couldn't reproduce a crash. I was using the most recent 1.11.2 versions of all the mods in question. 

Primal, Quark, AdInferno, Natura, BoP

**Comment by An-Sar** [comment]
@Rikshy no worries about the 1.10.2 comments, I haven't done any testing on that branch yet, but I did download the 1.10.2 versions of everything..

**Comment by Hypsellis** [comment]
I don't get more the crash now, I suppose I can close this issue.
