### ISSUE TITLE
What do i use a Stone Drain for

### ISSUE THREAD

**Issue by ItsMeUknow** [An-Sar/PrimalCore#45]
I did a lot of work making this thing and i dunt know what i does can anybody help me ?

**Comment by An-Sar** [comment]
The drains can be opened and closed. Currently the only thing they do is to pass items in world while the drain is open. There maybe some additional function later on but that's pretty much it atm.

We have a discord server that is better served for asking game-play questions than github, if you like join us here https://discord.gg/j9jwW4X
