### ISSUE TITLE
Andesite, Diorite, Granite not dropping rocks

### ISSUE THREAD

**Issue by SwordShaman** [An-Sar/PrimalCore#49]
When mining andesite, and other stone variants other than smoothstone, they are dropping in block form rather than their rock variants.  I've checked in JEI that their rock variants are indeed included in the mod, however they aren't dropping as they should be.

**Comment by An-Sar** [comment]
I have fixed this for the 1.11.2 branch and will be included in the next release, I would like to backport this to 1.10.2 but that will be awhile longer.
