### ISSUE TITLE
Incompatability with HarvestTweaks

### ISSUE THREAD

**Issue by belathus** [An-Sar/PrimalCore#5]
I initially reported this issue to Boni, and he pointed out that my problem was an incompatibility with PrimalCore. Looking over the log, I do see references to PrimalCore regarding horizontal facing and slab facing.

http://pastebin.com/raw/TBP1BnyZ

https://github.com/SlimeKnights/HarvestTweaks/issues/4

**Comment by An-Sar** [comment]
This is possible fixed, but will need some testing. =/

**Comment by An-Sar** [comment]
I've added HarvestTweaks, etc, to my dev environment and things seem to be working.

**Comment by belathus** [comment]
Very cool. We'll be testing it pretty thoroughly over the next few days/weeks as soon as we are able.

**Comment by An-Sar** [comment]
This has been released. Thank you
