### ISSUE TITLE
Feature Request: Axe Whitelist for Harvesting Log Blocks

### ISSUE THREAD

**Issue by Darkosto** [An-Sar/PrimalCore#50]
Hello,

Would you please consider adding a whitelist to the config to allow custom tools to be added for this particular config setting:

# Harvesting log blocks requires the use of appropriate tools

Outside of some modded axes that are not working (I have confirmed they are registering them correctly) I would also like to add some other items that would work well in the modpack I am creating. I appreciate you looking into this!

MC: 1.11.2
Forge: 2310
PrimalCore: 0.4.1

I really do love how well this mod is done and how it fits perfectly in the theme of my pack, great work!
Darkosto

**Comment by An-Sar** [comment]
Yes, this seems like a good feature to add. 

Do you have specific examples of mod axes that are not working?

**Comment by Darkosto** [comment]
At the moment, 1 is Tiny Progressions (available on Curse). The other is a custom mod made for the pack.

**Comment by An-Sar** [comment]
this is not directly related to the idea of an axe list, but in my dev environment both Tiny Progression axes and multitools were able to cut logs.. 

If possible I would be interested to test your custom mod in my environment also?

**Comment by Darkosto** [comment]
Interesting! I'll need to do some more testing today then and see why mine weren't properly working :)

Can I shoot you a private message somewhere to share this custom mod with you?

Thanks so much for taking the time to check this out!

**Comment by An-Sar** [comment]
Yeah I am on Discord as **_An Sar#2894_**, if that works.
