### ISSUE TITLE
Integration with JEI/Quark/other inventory mods

### ISSUE THREAD

**Issue by Efimero** [An-Sar/PrimalCore#51]
Your crafting tables don't show the [+] button when using JEI, your crates don't show the sorting buttons and don't respond to the sorting shortcuts.
I assume it is because you're not extending the right classes, hopefully it's easy to fix.

**Comment by An-Sar** [comment]
This doesn't appear to be affected by class inheritance, at least in the case of the crafting tables.
Will require some further investigation.

**Comment by Efimero** [comment]
At least for JEI, I think you have to register your "machines" as crafting grids.
https://github.com/mezz/JustEnoughItems/wiki/Recipe-Transfer-Handlers

**Comment by MysticAura** [comment]
I agree that JEI integration is pretty essential. As is inventory tweaks integration to fix the sorting issues

**Comment by An-Sar** [comment]
I haven't forgotten this issue =D I am dealing with some 1.12 bugs and hopefully getting into this sooner rather than later.

**Comment by An-Sar** [comment]
should be working with jei
