### ISSUE TITLE
Add axe recipes for vanilla axes

### ISSUE THREAD

**Issue by Efimero** [An-Sar/PrimalCore#52]
At least for iron, you don't have an iron (or gold) axe, so you should have recipes for planks/sticks etc using vanilla axes, at least optionally, or add the missing tool replacements.

**Comment by An-Sar** [comment]
There is an issue adding recipes for vanilla axes, where if a recipe from a different mod expects to consume the axe it ends up staying in the crafting grid. 

The immediate fix was to switch it to primal-only axes and hatchets.. For sake of consistency I might move these recipes to the work blade...  I'm not sure if there is an easy solution for dealing with 3rd party recipes...

**Comment by An-Sar** [comment]
the TP battle axe doesn't work, they have no tool type string registered at all. That could be a case for the list, it would be nicer if they just added a tooltype though.. =p

**Comment by Efimero** [comment]
Ah, I understand the issue! You need one of your mods items so it doesn't conflict.
Maybe you could add them in an option that is off by default at least? Just in case.

**Comment by CJL48** [comment]
I have a quick question: does the bug you mentioned occur with the axes from Kitsu's forgecraft?

**Comment by An-Sar** [comment]
Hm, I'm not really sure. that's something I should look at.
