### ISSUE TITLE
suggestion of mobs

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#53]
I wanted to suggest some ideas of mobs that could be added. This is so far everything I thought.
- Ant
- Antilope
- Bee
- Beetle
- Bird
- Boar
- Bumblebee
- Butterfly
- Caterpillar
- Crab
- Cricket
- Deer
- Dolphin
- Dragonfly
- Duck
- Elephant
- Ferret
- Firefly
- Fish
- Fly
- Fox
- Frog
- Girafe
- Goat
- Hamster
- Jellyfish
- Ladybug
- Leopard
- Lobster
- Lion
- Lizard
- Lynx
- Maggot
- Manta ray
- Marmot
- Mole
- Monkey
- Mouse
- Ostrich
- Owl
- Panther
- Penguin
- Pirhana
- Raccoon
- Rat
- Scorpion
- Shark
- Slug
- Snail
- Snake
- Squirrel
- Sting ray
- Tiger
- Turkey
- Turtle
- Wasp
- Whale

**Comment by An-Sar** [comment]
Thank you for the list. I definitely have some new mobs planned.

**Comment by Hypsellis** [comment]
Are there any news about it ? :D

**Comment by Hypsellis** [comment]
Is there any news about it ?
