### ISSUE TITLE
nether plants grow everywhere

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#54]
While they should normally only grow on netherrack, soul sand, tainted soil, head sand (natura compability), and primalcore nether blocks.

**Comment by An-Sar** [comment]
I assume you mean the nether grass. Unfortunately, it is meant to grow on _almost_ anything with a solid surface.

**Comment by Efimero** [comment]
I think it is cool that it can grow anywhere, but maybe there should be less patches? it is -everywhere- and it pushes you around in a weird way. it's a bit annoying, but it looks very nice everywhere I've seen it

**Comment by Hypsellis** [comment]
The problem is with BOP compability, it tends to break a bit the biomes unique look.

**Comment by An-Sar** [comment]
i am interested in supporting custom nether biomes, it is my intention to start with NetherEX as time allows

**Comment by An-Sar** [comment]
Config lists have been added that allow blacklisting certain blocks for the nether and end grass worldgen: _GEN_CINERIS_BLACKLIST_, _GEN_INERIS_BLACKLIST_
