### ISSUE TITLE
With SURVIVAL_WOOD_HARVESTING_TOOLS true, it is more difficult to create a tree farm

### ISSUE THREAD

**Issue by belathus** [An-Sar/PrimalCore#55]
Most block breakers seem unable to harvest logs with this option enabled. The Mechanical Miner, RFTools builder, and EnderIO farming station all cannot collect logs. I'm guessing this is because they default to using a "pickaxe" type tool string to gather blocks (even though the Farming Station requires an axe to be placed in its inventory to harvest logs). As an additional note, the farming station collects tons of sticks; possibly due to this setting: B:SURVIVAL_LEAF_STICK_DROP=true.

That said, the MineColonies lumberjack is able to collect logs.

**Comment by kitsushadow** [comment]
Doesn't that seem more of an issue with the mods whose block breaker needs to not default to pickaxe?

Also the farming stations collecting sticks seems like a reasonable thing when they are collecting the leaves.

**Comment by belathus** [comment]
I suppose. Though, I imagine that specifying that you're using an axe is something that other mods don't usually have to support. Though, I'll suggest it to the other mods anyway.

I don't expect RWTema to look at his issue tracker anytime soon, though. He seems totally unresponsive to it.

**Comment by kitsushadow** [comment]
I am implementing a type of block breaker in Forgecraft which we may move to an tech mod of some type later. Does something like that sound worth pursuing?

**Comment by belathus** [comment]
I would love to have more options for block breakers in tech mods, so I'll go with "yes."

**Comment by kitsushadow** [comment]
Provide a number of bullets with the uses you are using them for and what your expectations are for drops and interactions.

**Comment by Divineaspect** [comment]
This will also help with our move to 1.11 as we can include a functioning version of forgecraft then.

**Comment by belathus** [comment]
Alright. It depends on the capabilities.
* Take advantage of fluid interactions. IE: Collect BoP mud (quicksand + water)
* If I can apply Fortune to the block breaker: re-break silk-touched harvested ores such as diamonds, redstone.
* If I can also apply autosmelting enchantment: instead of getting mud, collect mud bricks (saves a step)
* XReliquary's altar of light produces blocks of glowstone over a period of time; a block breaker would help me automate that (even better if it can use silk touch). An object that can simulate a player right clicking on it with an item would allow me to fully automate it.

I can probably think of more uses for it later.

**Comment by belathus** [comment]
Going back to the farming station: I just looked at the code for it. It looks like it does try to use an axe. https://github.com/SleepyTrousers/EnderIO/blob/1.10/src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java#L87

**Comment by kitsushadow** [comment]
I will play with the FC block breaker and see if I can emulate your requirements. If it works i'll discuss with @An-Sar about where to put it and how to balance it.

**Comment by Divineaspect** [comment]
An option to, when breaking search for the farthest contiguous block of the same type and break it first. This would be the tree farming option, but  could also be used for mining veins, collecting mushrooms, farming crops.

**Comment by An-Sar** [comment]
I have a fix for this in the 1.11.2 branch that worked with the RFTools Builder, needs more testing.
And it would be a nice one for back porting but I have a number of things to finish before that.

**Comment by An-Sar** [comment]
I believe this has been resolved, at this point no plans of back porting to 1.10.2
