### ISSUE TITLE
Mobs only cfg option?

### ISSUE THREAD

**Issue by Seth0067** [An-Sar/PrimalCore#56]
Hi An-sar, 

Don't take this the wrong way, because I really like the early game progression of your mod content - its just not fitting in with my pack at the moment... BUT I would really love to use your mobs.  

Would it be possible to add a cfg option to enable just the mobs only? 

Thanks so much for your work either way!

**Comment by An-Sar** [comment]
I Believe you could Achieve more or less the same effect by going through and toggling off all the invasive features. Granted it's a bit more than just a single button to press, but I think it would more or less do what you want. Also I am willing to add almost any individual configs that might be missing for your specific use case.

In terms of just a single off switch, it would add a lot of complexity that overlaps with the existing config hooks. At this point I think All the game changing features should have config control in one form or another.

**Comment by Seth0067** [comment]
OK - that's what I started doing last night but wasn't sure that it would take care of "everything".  I'll let you know if I come across anything that's not there already.  Appreciate your response!

**Comment by Seth0067** [comment]
Hey - I remembered another reason that I wanted to mention: I'm running low on IDs!  You may want to consider at some point breaking the mobs into a seperate mod. Just a thought, especially since good mobs are hard to come across (I would love to use Mo' Creatures but their spawner is problematic and they don't want people using the mod in packs to begin with). And, that way, you get TWO amazing minecraft mods on your resume for the price of one, right!

**Comment by kitsushadow** [comment]
Ur running low on Mob IDs or Block IDs?

**Comment by An-Sar** [comment]
Make sure to disable the colored daub, it will prevent a bunch of blocks from being registered.
Also the upcoming version is on the path toward reducing ID consumption, as well as introducing a new config system that is compatible with the in-game gui.

I have been toying with the idea of a more modular approach to primal, but it would be a fair bit in the future if at all. 

The feedback is very much appreciated.

**Comment by Seth0067** [comment]
My pleasure!  To be clear i'm running low on block IDs, so I'm looking to reduce without cutting content.  I've tried the mod that extends the 255 limit, but it seems to cause problems with JEI.

**Comment by An-Sar** [comment]
I believe this has more or less been resolved
