### ISSUE TITLE
[Suggestion] Add ability to extend day/night cycle

### ISSUE THREAD

**Issue by SwordShaman** [An-Sar/PrimalCore#57]
I've been building specifically around your mod and 'better with mods' and in so doing I have noticed my players are experiencing quite a bit of difficulty (which is largely intended), however I wouldn't mind the capability to extend the day cycle by roughly 2 or 3 times its current amount.

I figured I'd see if you could include something along these lines as a configurable system.  It seems as it'd fit in with your theme as you are making things much more realistic in a survival sense and currently, as it stands, the day just seems to pass unrealistically fast.

Thanks for considering and for all the hard work you've put into this mod!  Take care!

**Comment by kitsushadow** [comment]
We use Stellar Sky in our dev pack for that very thing. I would suggest you try it out if you haven't already.

**Comment by SwordShaman** [comment]
Hmmm...as I understand it, that mod is unfortunately incompatible with shaders and most of my playerbase uses them.  If you know of a way to disable the graphic parts of the mod to make it compatible so I could just use it for the day cycle adjustment, please let me know.  Thanks kitsu.

**Comment by kitsushadow** [comment]
I've heard the same. I've seen conflicting results though. I know some people using shaders with Stellar Sky. Albeit on very low settings. It could be a product of the shader pack. The person I remember going through configuring it had to use a particular shader pack only. I don't know to much on the subject or the configs on Stellar. Have your reached out to the Stellar Sky author?

**Comment by SwordShaman** [comment]
I just dug through Stellar API and Stellar Sky again.  There doesn't appear to be any way to disable the sky rendering (which is understandable being one of the main directives of the mod).  My main concern with trying to use it primarily just to change day cycle is that it comes with so much overhead that I wouldn't be using.  I've tried several low spec shaders and have disabled all sky rendering in the shaders options with no effect of making them work well together.

I understand that this thread is primarily shifting from my suggestion to tech support for Stellar Sky.  If my suggestion could be done with another mod I'd happily use that method.  Unfortunately that doesn't seem to be the case.

**Comment by kitsushadow** [comment]
I know that we intended to have day night modifiers in Primal but we found that Stellar was doing a "stellar" job of managing the time that we didn't see a need to. I was just offering some of the advice from what we went through. Let's see what @An-Sar thinks as well. 

I can understand where your coming from and appreciate it. Lets get @An-Sar 's input to =)

**Comment by An-Sar** [comment]
I definitely want to add this so we're not reliant on another mod. There are more things I have planned that will make having a longer cycle pretty important so it's surely something I am planning to look into.

**Comment by SwordShaman** [comment]
Most excellent, neighbor!  Thank you for your continued support and vision.  I can't wait to see what else you have planned.

**Comment by An-Sar** [comment]
an experimental version of this will be included in the next release for both 1.11.2 and 1.12

there are two relevant config options, OVERRIDE_WORLD_SURFACE which defaults to false and will need to be changed to true. And, SURFACE_DAY_LENGTH which currently defaults to 4x time or 96000.0 ticks, while vanilla default is 24000.0

**Comment by An-Sar** [comment]
This has now been released for both 1.11.2 and 1.12 versions, feedback from live testing would be greatly appreciated.

**Comment by cosmicdan** [comment]
Doesn't seem to be working.

OVERRIDE_WORLD_SURFACE=true
SURFACE_DAY_LENGTH=60000.0

Only other mod was IngameInfoXML so I can see the clock. Each "minute" passes every second or so, just like vanilla.

Forge 1.12.1-14.22.0.2474
PrimalCore-1.12.1-0.5.8

Thanks for the fantastic mod btw!

**Comment by An-Sar** [comment]
It seems to be working for me in my dev environment, that is based on the sun/moon position and the vanilla clock. The time change code effects celestial angle and moon phase, my guess is that worldtime is not reflecting the change..

Did you observe celestial movement or just based on the IngameInfoXML clock?

Glad you like the mod.

**Comment by cosmicdan** [comment]
I'll check when I get home, but I don't see how that would be any different. We were trying in a little modpack which had some mod that showed a time popup GUI when vanilla clock is held too, it was no different to vanilla.

The clock in IngameInfoXml is just getting the time of day based on sun position, or at least that's how it was back in 1.7.10 - so it reported a slower clock correctly back then when we used HardmodeTweaks or whatever it was to extend the days. But the world appears to be ticking at the same rate as vanilla in this case, so the clocks are the same speed.

Is this change a coremod? You're sure it's correctly finding the classes/methods in the obfuscated environment? Or maybe the most recent Forge renamed some methods?

On 11 Sep 2017, An Sar <notifications@github.com> wrote:
>It seems to be working for me in my dev environment, that is based on
>the sun/moon position and the vanilla clock. The time change code
>effects celestial angle and moon phase, my guess is that worldtime is
>not reflecting the change..
>
>Did you observe celestial movement or just based on the IngameInfoXML
>clock?
>
>Glad you like the mod.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by An-Sar** [comment]
It's not a core mod, it overrides the world provider, as such it is not compatible with any other mod that does the same thing.

**Comment by cosmicdan** [comment]
Oh ok. I re-read too, this might be a case of some places still having a hard-coded assumption of day length being 24000 ticks like it was in 1.7.10 - that's why ASM was used then. Full-text search time perhaps?

I will take a deeper look into this over the next week if you like, I have mid-semester exams on for the next few days.

On 11 Sep 2017, An Sar <notifications@github.com> wrote:
>It's not a core mod, it overrides the world provider, as such it is not
>compatible with any other mod that does the same thing.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by An-Sar** [comment]
Yeah that sounds good, if you come across anything interesting let me know
