### ISSUE TITLE
Wiki entries for using items not defined in JEI.

### ISSUE THREAD

**Issue by ACIIL** [An-Sar/PrimalCore#58]
Referencing from PrimalCore-0.2.39.jar 	Beta	1.10.2.   I see change logs have touch upon tanning.

Please improve communication of features in the mod within the wiki, google hunting has not been straightforward or even good in term of direct results or wiki results. And forgive me if these game hints do appear somewhere.

A precise list of entries that will guide new players. These particularly i have not been able to solve by gameplay and JEI recipe hunting.

- Tanning, the stage of acquiring bark.  (notice. i been avoiding the special crafting table the moment i could get the regular)

- Using Fishing cage. (experimental crouch click in water works, but there was fish bait wasting until discovered)

- Acquiring tiers of string. Building hammers for making metal plates.

- Plant locations.

- All world gen behavior.

Thank you for your mod.  Flint era survival hunting is surprising more fun than instant craft table planning.

**Comment by Benjamin-Berry** [comment]
I second this. I started a pack "Primal" that features this mod heavily. I just deleted it because this mod is completely unplayable due to lack of any documentation.

**Comment by An-Sar** [comment]
i have finally started filling in pages on the wiki, the current strategy is to do a few pages a day.

**Comment by An-Sar** [comment]
https://github.com/An-Sar/PrimalCore/wiki
