### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by HeberonYT** [An-Sar/PrimalCore#63]
Many items have no texture when collected from the floor.
The funny thing is that in the NEI if they appear with texture, only that they have a different ID.
Minecraft 1.10.2
PrimalCore-0.2.39.jar
spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar

![screenshot_6](https://user-images.githubusercontent.com/13698597/27975409-a3bf9d4a-6327-11e7-8d2c-01beb6a2f7b5.png)
![screenshot_9](https://user-images.githubusercontent.com/13698597/27975408-a3bdf260-6327-11e7-9c7a-0df0e891ca89.png)
![screenshot_10](https://user-images.githubusercontent.com/13698597/27975410-a3c568b0-6327-11e7-88e2-abfa2154235f.png)

Regards!
Regards!

**Comment by An-Sar** [comment]
That's strange the items seem to be getting arbitrarily high damage values..

I haven't touched the 1.10.2 version for a long time, I am still considering a large back port that would possibly address this issue.

**Comment by HeberonYT** [comment]
I know, I've seen that the last update for 1.10.2 was a long time ago.
I would appreciate informing me when I have a solution, since I use your mod on a server and it is annoying to have those kind of problems with textures.
Thank you.

**Comment by An-Sar** [comment]
My current idea is to possibly back port the entire 1.11.2 branch, rather than trying to move specific features. I'm not 100% sure if that is the route I will go or not as it would also introduce a lot of destructive block changes etc..

I need to give this a bit more thought but will try to update related issues when I decide what route to take.

we also have a discord, which is a pretty good way to track on going changes =D

**Comment by HeberonYT** [comment]
In that case, I could not upgrade to that new version, because all blocks would be replaced and then users would lose their stored items from the mod. Not to mention the problem that might cause the map, perhaps it would be corrupt. I only speak in my case, you decide the best for you.

**Comment by An-Sar** [comment]
Maybe collecting a number of high profile bugs into a smaller maintenance release makes more sense in that case.
