### ISSUE TITLE
Improper OreDictionary Registration

### ISSUE THREAD

**Issue by KingLemming** [An-Sar/PrimalCore#64]
Hey guys, so it's been made apparent to me (and I confirmed with JD-GUI) that you are doing OreDictionary registration in PostInit.

This is bad and causes crashes and incompatibilities. Please don't do it. There is literally no reason for it. OreDictionary registration should happen as early as possible, ideally as soon as the Item / block itself is registered and non-null.

PostInit is for other mods to do blanket scans of the OreDictionary and process recipes appropriately. So this means that mods which happen to load before you will not get the correct OreDict names, hence the incompatibility.

You may have noticed the new Registration Event in 1.12 - Forge is moving to this style quite intentionally, and there's a reason that the Event fires so early - things are meant to be registered early. :)

**Comment by An-Sar** [comment]
That's true, the majority of the ore names for my own items take place during the item registration, but there is a group that gets added during post, that's a very easy fix.

The new registry stuff looks very good, it's my intention to move over as soon as I have the time.

Thank's for the heads on the ore dictionary names.

**Comment by An-Sar** [comment]
Post-init names have been moved to Pre-init for the 1.11.2. and 1.12 releases.
