### ISSUE TITLE
{1.11.2} World Gen Crash in Just Enough Dimensions Dimensions

### ISSUE THREAD

**Issue by SgtRalphie** [An-Sar/PrimalCore#70]
[crash-2017-08-23_15.09.39-server.txt](https://github.com/An-Sar/PrimalCore/files/1246742/crash-2017-08-23_15.09.39-server.txt)

I've tried disabling World Gen for the mod, but even with it all off it still crashes. Do you know any way around this?

**Comment by An-Sar** [comment]
What kind of config are you using for JED, custom dimensions?

**Comment by SgtRalphie** [comment]
[dimensions.txt](https://github.com/An-Sar/PrimalCore/files/1246898/dimensions.txt)
Just the bare minimum for a biomes o plenty overworld

**Comment by An-Sar** [comment]
Can you provide some more details on when the crash occurs? On first try I cannot reproduce this in my dev environment.

Thanks

**Comment by SgtRalphie** [comment]
its right when i try and teleport into the dimension, Am I using a version that's outdated?

**Comment by An-Sar** [comment]
You're version seems current. How do you enter the custom dimension?

**Comment by SgtRalphie** [comment]
with the command from JED /tpj name 9

**Comment by SgtRalphie** [comment]
it crashes on both the latest and recommended forges if that helps, I also have all world gen for primalcore off and JED separate world info enabled

**Comment by An-Sar** [comment]
Is this on a dedicated server? And What other mods do you have installed?

I was able to teleport in my dev environment, next I will try to setup a multimc instance and see if that makes any difference.

**Comment by SgtRalphie** [comment]
it was in single player, its just primalcore, JED, and biomes o plenty. I've tried without BOP and it doesn't change anything

**Comment by SgtRalphie** [comment]
from the look of it, it does tp me to the dimension after the crash, and it works fine afterwards. Its only when the mod is generating the land initially that it crashes

**Comment by An-Sar** [comment]
I have a fix that I am working on. Do you have discord? I can give you a dev build for testing.

**Comment by SgtRalphie** [comment]
Yeah Username is Thomas#8783

**Comment by SgtRalphie** [comment]
just wanted to say the version you linked worked, and fixed the crash

**Comment by An-Sar** [comment]
Nice, that's good to hear. I am going to mark this as resolved but open until I push the official release. Thanks for the help testing.

**Comment by An-Sar** [comment]
I believe this has been resolved
