### ISSUE TITLE
dirt and grass slabs and stairs issues and suggestions

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#71]
I noticed the grass, grass path, dirt, coarse dirt, mycelium and podzol slabs miss, the mycelium, podzol, coarse dirt stair as well. Otherwise the grass stair texture displays incorrectly, the grass appears white, and the recipe is unavalaible. Another thing is some blocks from PrimalCore like dirt and grass stair display in the Minecraft creative tab, and not in the PrimalCore one.

**Comment by Hypsellis** [comment]
Now the grass stair isn't more available, the other stairs still display in the wrong creative tab.

**Comment by An-Sar** [comment]
I'll check on the creative tab issue. 

Grass stairs are disabled until I can fix block rendering for coloring the grass by biome 
And in 0.6.x I am doing a bunch of block ID changes and internal refactoring, so the stairs will return in a proper working form.

**Comment by Hypsellis** [comment]
Eh now the grass stair display correctly, but the stair still display in the wrong creative tab, and it still misses grass, grass path, dirt, coarse dirt, mycelium and podzol slabs miss, the mycelium, podzol, coarse dirt stair as well.

**Comment by An-Sar** [comment]
that's my bad actually, I forgot to look at the creative tab issue =(

**Comment by Hypsellis** [comment]
Eh it's fine don't worry. :)

**Comment by An-Sar** [comment]
stairs are going to be entirely reworked in the upcoming 0.6.x branch, so will def look at it while I am doing that

**Comment by Hypsellis** [comment]
I hope slabs will come too. :)

**Comment by An-Sar** [comment]
yeah I would like to have stair and slab variants for all the primal blocks. It's looking like I will have to use non-ticking tile entities due to block ID limitations.

**Comment by Hypsellis** [comment]
Block ID limitations aren't a big problems thanks to NotEnoughID, and it won't be more a problem with 1.13 with the supression of id limit and metadata.

**Comment by An-Sar** [comment]
yeah if that ends up really happening in time for 1.13

**Comment by Hypsellis** [comment]
Oh I don't think, 1.13 will be a fucking huge update, Minecraft will be almost totally rewritten, and it will be a fucking pain for Forge and modders to update to this version. Anyway now the java version developpment is down due to the developpment of the better together and 4K update, so the 1.13 won't be released soon. I hope it will enable the 1.12 to become the next stable version for modding like 1.7 has been.

**Comment by An-Sar** [comment]
I hope that's the case both for the life span of 1.12 and the chunk format updates.
