### ISSUE TITLE
Firepit doesn't stay on fire

### ISSUE THREAD

**Issue by davqvist** [An-Sar/PrimalCore#72]
MC 1.12.1
Forge 2459
PC 0.5.7

I add a stack of sticks and timber to the firepit and light it on fire with the firebow, it lights up, but the fire extinguishes after a few seconds.

**Comment by An-Sar** [comment]
fire pit is going to get reworking a bit in up coming versions, so fixes to the current issues will be pending until that time.

**Comment by An-Sar** [comment]
i believe this has been fixed in a PR from @kitsushadow , not 100% sure on that

**Comment by kitsushadow** [comment]
This has been fixed but confirmation would be great
