### ISSUE TITLE
crafting recipe removal options don't work

### ISSUE THREAD

**Issue by Efimero** [An-Sar/PrimalCore#75]
Using 0.5.8 version of PrimalCore on 1.12 Minecraft.
The settings to disable vanilla recipes for planks and slabs do nothing.
The extra recipes are there, but the regular recipes are also still there (eg.: the vanilla "oak_planks" named recipe).
This means changing these options doesn't turn up the difficulty. =/

**Comment by An-Sar** [comment]
This should be fixed by the next release 0.5.9
