### ISSUE TITLE
Crash Seemingly Caused By Steppe Wolf

### ISSUE THREAD

**Issue by ChiefLogan3010** [An-Sar/PrimalCore#77]
[crash-2017-09-15_01.28.00-server.txt](https://github.com/An-Sar/PrimalCore/files/1304951/crash-2017-09-15_01.28.00-server.txt)
[crash-2017-09-15_01.34.07-server.txt](https://github.com/An-Sar/PrimalCore/files/1304953/crash-2017-09-15_01.34.07-server.txt)

**Comment by An-Sar** [comment]
Do you have any idea what was happening when the crash occurred. also a mod list/world type etc would be useful.

This is the same crash reported in https://github.com/An-Sar/PrimalCore/issues/76

**Comment by ChiefLogan3010** [comment]
After reading through that thread I'm pretty sure it's caused by a conflict with harder farming. when a world is loaded with that mod in the first few minutes it will crash, presumably upon the first spawn of one of primal's mobs. without harder farming there is no crash.

**Comment by An-Sar** [comment]
i will add that to my dev environment and see if i can recreate here

**Comment by An-Sar** [comment]
I crashed immediately so safe to say that is def the source of the conflict.

**Comment by An-Sar** [comment]
This has already been reported on the ReasonableRealism issue tracker, it seems that changes to the aging code don't take into account EntityAnimals that also attack things, but the issue is being worked on.
