### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [An-Sar/PrimalCore#78]
Version 0.5.8
MC 1.12
Forge 2443

https://pastebin.com/Ht4u6jbQ

**Comment by An-Sar** [comment]
Looks like you're out of block IDs. Primal uses a lot of IDs but it's something I am working on.

corail_pillar.core.PillarManager.addPillar(PillarManager.java:109)
pillar_extension_chisel.Main.registerBlocks(Main.java:214)

Makes it seem possible that the Corail Pillar chisel support could be adding additional pillar types but I'm not certain about that.

**Comment by Nexusdog** [comment]
Thanks for the heads up. It's s redundant mod now that archtecturecraft has a similar function so I've removed the Corail Pillar mod.
