### ISSUE TITLE
stone age saw?

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#8]
Would a pre iron saw, either with copper (yes I know you don't use copper), flint, barkstripper, or a cordsaw of some sort be feasible to add? 

Doesn't have to provide the full set of planks, I'd in fact prefer if it wouldn't.

**Comment by An-Sar** [comment]
I've thought about similar options, a cordsaw is an interesting idea that I haven't considered before. 

My first impulse was to do a flint saw but then a combination of delaying access to planks and flint as a material not feeling like a good match kept me from doing it.

Also I am planning to add copper eventually. It definitely seems like there should be something for this.

**Comment by kitsushadow** [comment]
We should look into chipping Obsidian with a Gahallager.

- [ ] Charge Gahallager
- [ ] 2-4 Cracked States for obsidian
- [ ] Final Hit breaks the obsidian into Obsidian Dust and knappable pieces

**Comment by An-Sar** [comment]
We added a flint saw, so will close this issue for now. Will possibly be looking for other options down the line but for now I think this is good. Thank You
