### ISSUE TITLE
Hibachi crash when returning from nether to location with one.

### ISSUE THREAD

**Issue by Divineaspect** [An-Sar/PrimalCore#80]
https://pastebin.com/qrNCLdBS

**Comment by An-Sar** [comment]
Hibachi isn't fully implemented. It will show up for real sometime in the upcoming 0.6.x branch.
I should most likely just remove it from 0.5.x

**Comment by An-Sar** [comment]
the crash has been fixed, hibachi is still not actually functional, but that is coming soon tm
