### ISSUE TITLE
[1.12.1] primalcore overriding betterwithmods log-punching settings.

### ISSUE THREAD

**Issue by jonqrandom** [An-Sar/PrimalCore#83]
both primalcore and betterwithmods have settings for what should happen if the player punches logs. if primalcore's setting "DROPS_LOGS_REQUIRE_TOOLS" is set to false and BTM's "HCLumber" is true, punching logs should drop a plank, and some bark and sawdust. it appears as though primal is preventing BTM from seeing the event at all, as the actual result of punching wood with the above settings is a dropped log.

**Comment by An-Sar** [comment]
Which version of PrimalCore are you using?

**Comment by An-Sar** [comment]
BWMs disables it's log drops when Primal is installed.

We are going to look at hooking into the configs so players can choose which mod's behavior they want to use.

**Comment by jonqrandom** [comment]
wow, right, sorry about that - so are you already talking to beeto, or should i raise the issue on the BWM tracker?

**Comment by An-Sar** [comment]
nothing to be sorry about =D I was talking briefly with prime so we should be good to see what needs to be done from there.

**Comment by jonqrandom** [comment]
awesome, thanks muchly for looking into it! :)

**Comment by AdaraChristine** [comment]
Hello, Did anything come from this? This would be a helpful config option. Thanks
