### ISSUE TITLE
canSustainPlant called on the wrong block

### ISSUE THREAD

**Issue by josephcsible** [An-Sar/PrimalCore#84]
ItemEvents.onItemDespawn is calling Block.canSustainPlant, but passing it block states that don't belong to the block that it's calling that method on. Note the two method calls that look like this:
```java
plant.canSustainPlant(world.getBlockState(pos.down()), /* ... the rest of the arguments */);
```
The problem is that `world.getBlockState(pos.down()).getBlock()` is a different block than `plant` is, but `canSustainPlant` assumes that these are the same. This causes a few problems:
* Most crops won't grow at all with this method, because the checks that `canSustainPlant` does against `this` will always fail. For example, for nether wart, it checks if `this == net.minecraft.init.Blocks.SOUL_SAND`, but we're passing `this` to be the nether wart itself, so it will never work. (It happens to work fine for cactus and sugarcane, since they can grow on top of each other, so they have a test specifically to see if the "ground" is themselves.)
* The game will crash if a modded crop assumes that the given state has one of its block properties (which it won't, because it's the ground and not the crop), such as in josephcsible/Oreberries#6.

To fix this issue, change this:
```java
plant.canSustainPlant(world.getBlockState(pos.down()), /* ... the rest of the arguments */);
```
to this:
```java
world.getBlockState(pos.down()).getBlock().canSustainPlant(world.getBlockState(pos.down()), /* ... the rest of the arguments */);
```
(You can also create a local variable with that block if you want. The important part is to make sure you call canSustainPlant on the "ground" block, and not on the block of the thing you want to grow.)

**Comment by An-Sar** [comment]
This code has been rewritten already in the dev version, i will test with ore berries to make sure this isn't still happening.

**Comment by An-Sar** [comment]
yup looks like the new code was having the same issue, testing the fix now and will include in the next release. 

Thank you for the detailed bug report.

**Comment by josephcsible** [comment]
Looks like 0.5.12 does indeed now handle this correctly.
