### ISSUE TITLE
PrimalCore overriding other mod ores, pink&black textures, fail to craft into ingots

### ISSUE THREAD

**Issue by Nexusdog** [An-Sar/PrimalCore#85]
For example, smelling Forestry copper ore, it will convert to PrimalCore nuggets which then display as pink&black missing texture grid and also fail to craft into ingots.

Major bummer, dude!

**Comment by An-Sar** [comment]
Do you have Better With Mods installed also? 
I seems to be a BWMs feature to replace smelting output with nuggets.

In testing the nugget that gets returned seems to be based on mods that are installed, maybe whichever nugget is registered to the dictionary last or something along those lines... I'm looking into this further.

**Comment by An-Sar** [comment]
I reached out to prime and am reviewing the way primal nuggets/ingots are coded...

In the meantime you could try disabling the BWM feature by setting "HCOres=false"

**Comment by An-Sar** [comment]
This turned out to be a simple fix with how primal was registering the items to the ore dictionary. Next release will correct the issue.

**Comment by Divineaspect** [comment]
I love when I'm about to report something and you've already resolved it.

**Comment by An-Sar** [comment]
I released 0.5.13 should fix the issue

**Comment by An-Sar** [comment]
I'm thinking the same ore dict issue was likely interacting poorly with other mods as well
