### ISSUE TITLE
Fire Bow endless durability

### ISSUE THREAD

**Issue by Thyriel** [An-Sar/PrimalCore#86]
Fire bow durability goes negative after zero so it's useable forever

**Comment by An-Sar** [comment]
which version are you using?

**Comment by Thyriel** [comment]
PrimalCore-1.12.2-0.5.13
Forge  14.23.0.2501

**Comment by An-Sar** [comment]
I couldn't quite reproduce this, but I noticed I wasn't checking sides while damaging the bow, this could be the cause.

**Comment by Thyriel** [comment]
Maybe a server-client issue ? (playing in multiplayer)

**Comment by An-Sar** [comment]
that's what I'm thinking yeah, I've added checks to only apply damage on the server

**Comment by Thyriel** [comment]
Btw today with like -90 or so durability the bow finaly broke

**Comment by An-Sar** [comment]
that's pretty bad, do you want to test a build with the side detection?

**Comment by An-Sar** [comment]
do you have discord? my handle is **_An Sar#2894_**

**Comment by Thyriel** [comment]
No. You can send me a PM on curseforge: https://minecraft.curseforge.com/members/thyriel27

**Comment by An-Sar** [comment]
this should be resolved
