### ISSUE TITLE
Picking up Lit Torch gives me vanilla torch

### ISSUE THREAD

**Issue by davqvist** [An-Sar/PrimalCore#87]
MC 1.12.1 (will switch to 1.12.2 in a few days)
Forge 2485
PC 0.5.13

Shift right clicking a lit torch gives me a vanilla torch instead of a lit torch. I don't think that is intended, is it? (with B:REPLACE_VANILLA_TORCHES=true)

**Comment by An-Sar** [comment]
Actually it is, since it also automatically replaces vanilla torched on world placement.. the entire approach to torches and torch replacement could likely use some review/feedback.

**Comment by davqvist** [comment]
Well then you always have a mix of vanilla and lit torches on you, I don't see a reason why you should get a vanilla torch.

**Comment by Divineaspect** [comment]
torches in hand/inventory should always be vanilla. Torches in world should always be Primal.

**Comment by davqvist** [comment]
I would be cool with that, but right clicking unlit torches on lit torches in the world, gives me Lit Torches. I just don't want to have two kinds of torches in my inventory.

**Comment by An-Sar** [comment]
going with what Divineaspect said, is how i think the torches should function when the replacement feature is enabled.

**Comment by Thyriel** [comment]
Imho getting vanilla torches this way is good for mod compatibilty. E.g. would be hard using Prinalcore and Minecolonies (needs vanilla torches as building material) when there would be no way of getting them.

**Comment by davqvist** [comment]
Any news on that? Pack is getting closer and closer to release and I would love to see this fixed.
Basically what Divineaspect said above. Should be an easy fix. Just change that if you right click with an unlit torch an in world torch, change it to a Torch not a Lit Torch and this should be done.

**Comment by An-Sar** [comment]
0.6.56 torches should only result in the vanilla item
