### ISSUE TITLE
Flint&Steel never breaks when lighting torches

### ISSUE THREAD

**Issue by davqvist** [An-Sar/PrimalCore#88]
MC 1.12.2
Forge 2512
PrimalCore 0.5.13

Lighting a torch with Flint&Steel uses durability, but never breaks, instead goes into the negatives.

**Comment by An-Sar** [comment]
A dev build, PrimalCore-1.12.2-0.5.13.2, is up in the dropbox with a possible fix for this

**Comment by Thyriel** [comment]
I think it's the same bug as #86 
Indeed now that you say that it's happening on lighting torches, i'm pretty sure my endless durability firebow finally broke when i used it to lit a charcoal pit from Forestry mod and i'm sure i never used it before for anything else then torches.

**Comment by davqvist** [comment]
Dev build fixed it, thanks

**Comment by An-Sar** [comment]
Thank you for testing
