### ISSUE TITLE
Better Questing: All quests complete when crafting a Basin

### ISSUE THREAD

**Issue by Krhymez** [An-Sar/PrimalCore#89]
I am having an issue with compatibility with PrimalCore and Better Questing. When i craft a "Basin" it completes all the quests in the book.

Modpack:  Primal

Link to issue posted on Better Questing GitHub: https://github.com/Funwayguy/BetterQuesting/issues/247

**Comment by An-Sar** [comment]
this is a strange one, as i have never used better questing i'm not quite sure were to start debugging,

**Comment by Krhymez** [comment]
I did a fix but its "hacky".  I just disabled the "stone basin" recipe and now require a "Pestle, item, rock"

Like you grind it on a rock with a pestle.

Worst case, maybe a rewrite of the items code? I dont know how many lines it is.

**Comment by Thyriel** [comment]
Happens for me too. The strange thing is also, it doesn't even stop to finish quests when deleting the stone basin and resetting quests with "/bq_admin reset all". You can watch then how one by one gets finished again.

**Comment by Krhymez** [comment]
@Thyriel Do you use "Roots 2" in your pack?  if so i can share the script i used to "Remove this" and add recipes for all the items it added.


@An-Sar When it doubt... toss it out.  Some times it is easier to start over, than try to fix it.  What i mean by that is... just remove the Basin from the mod. Then add a "Mortar/ pestle"   Maybe have it so you place the motar in the world, put in the item, then right click with pestle.

**Comment by An-Sar** [comment]
Yeah actually the basin item was always a filler pending a quern block that has yet to be implemented, so now might just be the time. Provided there aren't other items that have a similar issue..

**Comment by Thyriel** [comment]
@Krhymez: Thx but i already wrote a script for crafttweaker.

@An-sar: Just a guess but i think what differs the basin from other items you added is that it's returned on crafting. So maybe there's something odd in that part of the code. But imho the main bug lays on Better questings side, as it's obviously hanging up in some weird loop. BQM has quite a lot bugs and badly atm there's nothing done about these.

**Comment by Thyriel** [comment]
Btw as we're talking about Primalcore /BQM bugs: There's another weird interaction bug: Some items being crafted on Primalcores crafting tables aren't recognized in better questings crafting quests. Not a big problem as BQMs crafting quests anyway have their own problems so i don't use them anymore. 
Just if you want to look into that: A crafting quest to craft all minimum items for a tinker smeltery should do it.

**Comment by Krhymez** [comment]
This happens when you shift click craft.  If you single click craft, it works. I had the same issue.

**Comment by Thyriel** [comment]
That would explain that weird behavior

**Comment by Krhymez** [comment]
@An-Sar I switched over to HQM and it does not have this issue. SO it is not an issue with your code. It must be "Better Questing Mod".

I would not focus on this too much. 0.6.+  is more important.
