### ISSUE TITLE
Any non-Primalcore recipe that uses an axe duplicates the axe, doesn't use any ingredients

### ISSUE THREAD

**Issue by belathus** [An-Sar/PrimalCore#9]
These two images show what I'm talking about: http://imgur.com/a/GdpCG
It also works with EnderIO's Slice'n'splice.

**Comment by An-Sar** [comment]
Thanks for the bug report. For now I have removed normal axes from the primal crafting handler, and moved their recipes to hatchets and work blades, this should avoid the issue until I can work on a better alternative. This will be released with 0.2.0.

**Comment by An-Sar** [comment]
This has been released. Thank you
