### ISSUE TITLE
Gators spawn count low.

### ISSUE THREAD

**Issue by Krhymez** [An-Sar/PrimalCore#90]
I have set the spawn to 35, but they are still really rare.

Not sure if they are set to spawn in "rivers" but i seem to not find any.
May not be a bug, may be an oversight by me but it would be cool if they were made to spawn in rivers more.

Do i need to increase the limit even higher?

**Comment by An-Sar** [comment]
They should spawn in river biomes, i haven't tried increasing spawn amounts so i might need to do some testing on this..

**Comment by Krhymez** [comment]
I would have them spawn in "beach, river, swamp"  They do not seem to be spawning in rivers at all, but rather on land around. I have seen one today but i have the spawns all the way up to 100. This has me to believe something is not right.  The Steppe wolf is set to 6 yet it spawns "groups".

If possible, could you make it so gators spawn in groups. 2-3 similar to the wolves.
