### ISSUE TITLE
JEI support Crafting Table

### ISSUE THREAD

**Issue by Krhymez** [An-Sar/PrimalCore#91]
Any chance you can add "Shift click" crafting from jei in the crafting table.

Again, not sure if an issue, but would be nice to have.

**Comment by An-Sar** [comment]
Yes I definitely want to add this. 

Hopefully proper JEI support is going to fit into the upcoming 0.6.x release, lots of big changes that need to get solidified first but once it's playable again I plan on looking into JEI and CraftTweaker.

I encourage testing the current dev builds if you are into that kind of thing.

**Comment by Krhymez** [comment]
Great.  I am working hard on the pack i am making. So i will report any bugs i find. 

People are really enjoying the pack and mod.

**Comment by An-Sar** [comment]
this should now be working in 0.6.10
