### ISSUE TITLE
JEI integration for recipes (Or guide book)

### ISSUE THREAD

**Issue by Krhymez** [An-Sar/PrimalCore#92]
I have been getting request about the "Leather" recipe and how JEI does not show it.
People are asking for a guide book. Are there any plans to add a "Primal Survival Guide"?
I think this would be a great feature for the mod.

If not, some JEI support for recipes would be nice.

**Comment by An-Sar** [comment]
I've started working on JEI support in 0.6.x

**Comment by An-Sar** [comment]
JEI support has been added to the Drying Rack for 0.6.10, more blocks will follow suit shortly

**Comment by An-Sar** [comment]
JEI has been added to the new Cauldron block, i believe this issue or more or less satisfied, more blocks will get support as need.

**Comment by Chinthor** [comment]
Let me know if I'm missing something, but what can Pigman Leather be used for? Either I'm dense, or this falls under a JEI failure. I'm playing Forever Stranded: Lost Souls, and can see everything one can do with Raw Pigman Hide. It can be salted, then dried, then tanned, then dried again into Pigman Leather... that has no uses in JEI. True, I could just try it in some shaped recipes, but with that many steps? Your average player is not inclined to bother. Am I wrong?

**Comment by An-Sar** [comment]
There are some specialized uses that have not been fully implemented.

However this made me realize it is suppose to be in the Ore Dictionary to be compatible with normal leather recipes, this is an oversight on my part. i have just added the dictionary name, so the next update should make it more useful.

Thank you

**Comment by Chinthor** [comment]
Thank _you_, Sir. This mod is shaping up to be a must-have for any "start-from-the-stoneage" pack. So much so, that I think I'd like to piece one together myself. 

Cheers!

**Comment by Chinthor** [comment]
Kudos on fixing the leather ore dictionary on the last update. Ran into a snag tho. Now salted pigman hide has no recipe. Tried just crafting it in a variety of ways. No dice. Is this due to a change you made, or something broken in the Lost Souls pack? I could see that happening as well.

**Comment by An-Sar** [comment]
that's a bug, will fix for 0.6.33

**Comment by Chinthor** [comment]
1.) Good to know
2.) I'm sure you will. Rock on

**Comment by An-Sar** [comment]
0.6.33 has been released, hopefully its working now =P
