### ISSUE TITLE
Bark output

### ISSUE THREAD

**Issue by Krhymez** [An-Sar/PrimalCore#93]
It seems that when using a Work Knife with a log, you get 1 bark.. no matter the level of the tool tool.

I think that should be increased. Maybe depending on tool level. 4 bark would be a nice base number. then more depending on the tool

**Comment by An-Sar** [comment]
It's meant to be a variable output of 1-4 or 2-5, something similar. will do some testing...

**Comment by An-Sar** [comment]
This has been fixed in 0.6.x

**Comment by Krhymez** [comment]
When you strip the log in a crafting grid, you do not get any "Striped logs" back.  I feel that you should.

**Comment by An-Sar** [comment]
it should be possible to leave a stripped log behind in the crafting grid by way of the crafting event..

**Comment by Krhymez** [comment]
I can add a Craft tweaker recipe, but it would be nice if it was part of the mod.
Also, no need to have it left in crafting grid, just placed to your inventory.
