### ISSUE TITLE
Rush leaving roots (config to disable)

### ISSUE THREAD

**Issue by Krhymez** [An-Sar/PrimalCore#94]
There is a config option to disabled vanilla tall grass from leaving roots. But rush leaves them even when this is disabled. 

Is it possible that you can add a config to also disable this for rush also?

**Comment by An-Sar** [comment]
There is a config option PLANTS_ARE_PERENNIAL, which disables roots for all the relevant primal plants: rushes, nether grass, void grass, sinuous weed, .. i might be forgetting one or two.

However, pretty sure i added this option in 0.6.x so currently not available in the 0.5.x versions.

**Comment by An-Sar** [comment]
out of curiosity, is this the type of feature you would globally disable or are per plant configs useful?

**Comment by Krhymez** [comment]
I would just have an "disable all" feature. No need to pick and choose. I think players will either want it or not.
