### ISSUE TITLE
Kitsu's  silk touch pick used on a poor grade charcoal stack gives charcoal and stack

### ISSUE THREAD

**Issue by kiwifrogg** [An-Sar/PrimalCore#95]
As per title, using a silk touch(in our case kitsu's one) we get the stack back and the charcoal, you can replace the stack and do the same over and over. So it is a item dupe.   It can be seen in cscotplays last live stream.   We have not tried other grades.

**Comment by kitsushadow** [comment]
ill look into it

**Comment by An-Sar** [comment]
This is an issue with any form of silk touch, not just KFC tools, related to how the drops where being managed, a dev build is up for 0.6.x branch, and 0.5.15 has been pushed live with a fix.

**Comment by kitsushadow** [comment]
thanks for the response @An-Sar

**Comment by kiwifrogg** [comment]
Cool thanks,  I had no other silk touch to test, Sorry kitsu to blame just yours :)

**Comment by An-Sar** [comment]
No, it's completely correct as default to blame Kitsu, blame and ask questions later i always say =D

**Comment by kitsushadow** [comment]
Hahahahaha that's unfortunately a proper default XD
