### ISSUE TITLE
block suggestions

### ISSUE THREAD

**Issue by Hypsellis** [An-Sar/PrimalCore#97]
I just wanted to suggest to add some blocks that really miss to the mod.
- Stone stair, slab, wall
- Diorite stair, slab, wall
- Andesite stair, slab, wall
- Granite stair, slab, wall
- Moss stone stair, slab
- Mossy stone brick stair, slab, wall
- Stone brick wall
- Cracked stone brick stair, slab, wall
- Chiseled stone brick stair, slab, wall
- Sandstone stair, slab, wall
- Chiseled sandstone  stair, slab, wall
- Smooth sandstone  stair, slab, wall
- Brick wall
- Quartz wall
- Chiseled quartz stair, slab, wall
- Pilliar quartz stair, slab, wall
- Obsidian stair, slab, wall
- Prismarin stair, slab, wall
- Dark Prismarin stair, slab, wall
- Prismarin bricks stair, slab, wall
- Netherrack stair, slab, wall
- Magma stair, slab, wall
- Nether brick wall
- Red nether brick  stair, slab, wall
- End stone stair, slab, wall
- End stone bricks stair, slab, wall
- Purpur wall
- Purpur pilliar stair, slab, wall
- Terracotta stair, slab, wall
- Concrete stair, slab, wall
- Dirt stair, slab, wall
- Grass stair, slab, wall
- Coarse dirt stair, slab, wall
- Podzol stair, slab, wall
- Mycelium stair, slab, wall
- Dirt path stair, slab, wall
- Iron stair, slab, wall
- Gold stair, slab, wall
- Diamond stair, slab, wall
- Emerald stair, slab, wall
- Lapis lazuli stair, slab, wall
- Redstone stair, slab, wall
- Coal stair, slab, wall
- Wool stair, slab, wall
- Glass stair, slab, wall
- Snow stair, slab, wall
- Packed ice stair, slab, wall
- Bone stair, slab, wall
- Soulsand stair, slab, wall
- Nether wart stair, slab, wall

**Comment by kiwifrogg** [comment]
Can't you already make all these things with little tiles or any other microblock style mods?

**Comment by Krhymez** [comment]
There are already many mods that add this. As long as there is a config to disable them. If not, there will be a lot of duplicates.

**Comment by Hypsellis** [comment]
Microblocks still didn't update for 1.12.2. Little tiles and chisel and bits work highly differently, it doesn't create any stair, slab or wall blocks, it enables to modify blocks tiles by tiles for giving them anyway shape.

**Comment by Krhymez** [comment]
@Hypsellis Thank me later: https://mods.curse.com/mc-mods/minecraft/278882-blockcraftery

Covers all your "needs". its like carpenter blocks but for 1.12.2

**Comment by Hypsellis** [comment]
Yeah I know this mod, and it's exactly what I told, it doesn't work at the same way. You justify features mustn't be added in a mod because there is already something similar in another mod. So you can tell that to all the techs mods that copy them and look the same. XD

**Comment by An-Sar** [comment]
more blocks will be possible in 1.13
