### ISSUE TITLE
.19 flint tools durability very very low

### ISSUE THREAD

**Issue by kiwifrogg** [An-Sar/PrimalCore#99]
All flint tools break in 4 or 5 uses as off .19

**Comment by An-Sar** [comment]
fixed it 0.5.20

**Comment by cScotPlay** [comment]
I think this a deliberate adjustment to see how one can cope with the challenges of a mod.  Continue to bring it! :)

**Comment by An-Sar** [comment]
=D I can confirm nothing @cScotPlay
